"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { ArrowRight, BookOpen } from "lucide-react";
import { listPublishedJournalArticles, type JournalArticle } from "@/lib/hq-articles";

export default function JournalPage() {
  const [items, setItems] = useState<JournalArticle[]>([]);
  const [category, setCategory] = useState("all");
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  useEffect(() => { listPublishedJournalArticles().then(setItems).catch((cause: unknown) => setError(cause instanceof Error ? cause.message : "記事を読み込めませんでした。")).finally(() => setLoading(false)); }, []);
  const categories = useMemo(() => Array.from(new Map(items.filter((item) => item.category).map((item) => [item.category!.id, item.category!])).values()), [items]);
  const visible = category === "all" ? items : items.filter((item) => item.category_id === category);
  return <main className="min-h-screen bg-[#f7f5ef] text-[var(--mikke-text)]"><header className="border-b border-[var(--mikke-line)] bg-white"><div className="mx-auto flex max-w-6xl items-center justify-between gap-4 px-5 py-4"><Link href="/home" className="font-black text-[var(--mikke-primary)]">mikkeOS</Link><span className="text-xs font-black tracking-[0.18em] text-[var(--mikke-muted)]">JOURNAL</span></div></header><div className="mx-auto max-w-6xl px-5 py-10 sm:py-16"><section className="max-w-3xl"><p className="text-xs font-black tracking-[0.18em] text-[var(--mikke-primary)]">mikkeOS JOURNAL</p><h1 className="mt-4 text-4xl font-black leading-tight text-[var(--mikke-ink)] sm:text-6xl">つくっている途中も、<br />ちゃんと残していく。</h1><p className="mt-6 text-base leading-8 text-[var(--mikke-muted)]">アップデート、新しいアプリ、お知らせ、そしてmikkeOSができるまでの思いを届けます。</p></section>
      {categories.length ? <nav className="mt-10 flex flex-wrap gap-2" aria-label="カテゴリー">{[{ id: "all", name: "すべて", color: "#3f4eb5" }, ...categories].map((item) => <button key={item.id} type="button" onClick={() => setCategory(item.id)} className={`rounded-full border px-4 py-2 text-xs font-bold transition ${category === item.id ? "border-transparent text-white" : "border-[var(--mikke-line)] bg-white text-[var(--mikke-muted)]"}`} style={category === item.id ? { backgroundColor: item.color } : undefined}>{item.name}</button>)}</nav> : null}
      {loading ? <div className="grid min-h-64 place-items-center text-sm font-bold text-[var(--mikke-muted)]">記事を読み込んでいます…</div> : error ? <div className="mt-10 rounded-2xl border border-red-200 bg-red-50 p-5 text-sm text-red-700">{error}</div> : visible.length === 0 ? <div className="mt-10 grid min-h-64 place-items-center rounded-3xl border border-dashed border-[var(--mikke-line)] bg-white p-8 text-center"><div><BookOpen className="mx-auto text-[var(--mikke-primary)]" /><p className="mt-4 font-bold">公開中の記事はまだありません</p><p className="mt-2 text-sm text-[var(--mikke-muted)]">本部から記事が公開されると、ここに並びます。</p></div></div> : <div className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{visible.map((article) => <Link key={article.id} href={`/journal/${article.slug}`} className="group overflow-hidden rounded-3xl border border-[var(--mikke-line)] bg-white shadow-sm transition hover:-translate-y-1 hover:shadow-lg">{article.cover_image_url ? <img src={article.cover_image_url} alt="" className="aspect-[16/10] w-full object-cover" /> : <div className="grid aspect-[16/10] place-items-center bg-[var(--mikke-primary-soft)] text-xs font-black tracking-[0.16em] text-[var(--mikke-primary)]">mikkeOS JOURNAL</div>}<div className="p-5"><div className="flex items-center gap-2 text-[11px] font-bold text-[var(--mikke-muted)]">{article.category ? <span className="rounded-full px-2 py-1 text-white" style={{ backgroundColor: article.category.color }}>{article.category.name}</span> : null}<time>{new Date(article.published_at ?? article.updated_at).toLocaleDateString("ja-JP")}</time></div><h2 className="mt-4 text-xl font-black leading-snug text-[var(--mikke-ink)]">{article.title}</h2>{article.excerpt ? <p className="mt-3 line-clamp-3 text-sm leading-6 text-[var(--mikke-muted)]">{article.excerpt}</p> : null}<span className="mt-5 inline-flex items-center gap-1 text-xs font-black text-[var(--mikke-primary)]">続きを読む<ArrowRight size={14} className="transition group-hover:translate-x-1" /></span></div></Link>)}</div>}
    </div></main>;
}
