"use client";
import { useState } from "react";
import { AcademyImageUploader } from "./AcademyImageUploader";
import styles from "./academy-course-input.module.css";
export function AcademyCourseImages({ images, onChange }: { images: string[]; onChange: (images: string[]) => void }) {
  const [editing, setEditing] = useState<number | "new" | null>(null);
  function move(from: number, to: number) { if (to < 0 || to >= images.length) return; const next = [...images]; [next[from], next[to]] = [next[to], next[from]]; onChange(next); setEditing(null); }
  return <div className={styles.images}>{images.map((url, index) => <div className={styles.imageRow} key={`${index}:${url}`}><img src={url} alt={`講座画像 ${index + 1}`} /><div className={styles.imageActions}><small>{index === 0 ? "1枚目・サムネイル" : `${index + 1}枚目`}</small><button className={styles.plainButton} type="button" onClick={() => setEditing(editing === index ? null : index)}>画像変更</button><button className={styles.plainButton} type="button" onClick={() => { onChange(images.filter((_, i) => i !== index)); setEditing(null); }}>画像削除</button><button className={styles.plainButton} type="button" disabled={!index} aria-label={`画像${index + 1}を前へ`} onClick={() => move(index, index - 1)}>←</button><button className={styles.plainButton} type="button" disabled={index === images.length - 1} aria-label={`画像${index + 1}を次へ`} onClick={() => move(index, index + 1)}>→</button></div>{editing === index && <div className={styles.picker}><AcademyImageUploader compact onUploaded={next => { onChange(images.map((image, i) => i === index ? next : image)); setEditing(null); }} /></div>}</div>)}{images.length < 6 && <button className={styles.plainButton} type="button" onClick={() => setEditing(editing === "new" ? null : "new")}>＋ 画像を追加</button>}{editing === "new" && images.length < 6 && <div className={styles.picker}><AcademyImageUploader compact onUploaded={url => { onChange([...images, url]); setEditing(null); }} /></div>}<small className={styles.note}>最大6枚。1枚目がサムネイルになり、講座カードでは5秒ごとに切り替わります。</small></div>;
}
