"use client";
import {useCallback,useEffect,useRef,useState} from 'react';
import {useAuth} from '@/components/AuthGate';
import {getOwnedHeadquarters} from '@/lib/academy/headquarters';
import {listCourses} from '@/lib/academy/courses';
import {rosterAction,type RosterEntry,type RosterCertification} from '@/lib/academy/roster-local';
import type {AcademyCourse} from '@/types/database';
import styles from './academy-roster.module.css';

export function AcademyRosterDrafts(){
 const {profile}=useAuth();const [hq,setHq]=useState(''),[courses,setCourses]=useState<AcademyCourse[]>([]),[rows,setRows]=useState<RosterEntry[]>([]),[selected,setSelected]=useState<RosterEntry|null>(null),[name,setName]=useState(''),[number,setNumber]=useState(''),[certs,setCerts]=useState<RosterCertification[]>([]),[id,setId]=useState(''),[handle,setHandle]=useState(''),[email,setEmail]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[newCert,setNewCert]=useState<RosterCertification>({courseId:'',certifiedAt:null,renewalDue:null});
 const loadVersion=useRef(0);
 const refresh=useCallback(async()=>{const version=++loadVersion.current;setLoading(true);setError('');try{const owned=await getOwnedHeadquarters(profile.user_id);if(!owned)throw Error('管理する本部が見つかりません。');const [entries,found]=await Promise.all([rosterAction<RosterEntry[]>('list',{p_hq:owned.id}),listCourses(owned.id)]);if(version!==loadVersion.current)return;setHq(owned.id);setRows(entries);setCourses(found);}catch(e){if(version===loadVersion.current)setError(e instanceof Error?e.message:'読み込めませんでした。');}finally{if(version===loadVersion.current)setLoading(false);}},[profile.user_id]);
 useEffect(()=>{void refresh();return()=>{loadVersion.current+=1;};},[refresh]);
 function edit(row:RosterEntry|null){setSelected(row);setName(row?.full_name??'');setNumber(row?.instructor_number??'');setCerts(row?.certifications??[]);setId(row?.id??crypto.randomUUID());setHandle(row?.target_handle??'');setEmail(row?.contact_email??'');setError('');setNotice('');setNewCert({courseId:'',certifiedAt:null,renewalDue:null});}
 async function run(action:string,data:Record<string,unknown>){if(busy)return;setBusy(true);setError('');setNotice('');try{const next=await rosterAction<RosterEntry>(action,{p_hq:hq,p_id:id,p_version:selected?.version??null,p_data:data});const entries=await rosterAction<RosterEntry[]>('list',{p_hq:hq});setRows(entries);edit(entries.find(x=>x.id===next.id)??next);setNotice(action==='set_contact'?'連絡先を保存しました。案内は下のボタンから作成できます。':action==='invite_email'?'本人確認の案内を受け付けました。通知ログで送信状況を確認できます。':action==='reissue_email'?'以前のリンクを無効にして、新しい案内を受け付けました。':action==='register'?'正式登録しました。登録講師1人として数えます。':action==='withdraw'?'登録を解除しました。':action==='add_certification'?'認定講座を追加しました。':action==='save'?'名簿の下書きを保存しました。':action==='request_link'?'本人確認用のリンクを作りました。':'確認依頼を取り消しました。');}catch(e){setError(e instanceof Error?e.message:'処理できませんでした。');}finally{setBusy(false);}}
 const dirty=Boolean(selected)&&(name!==selected?.full_name||number!==selected?.instructor_number||JSON.stringify(certs)!==JSON.stringify(selected?.certifications));const formal=Boolean(selected?.registered_at),withdrawn=Boolean(selected?.withdrawn_at);const locked=Boolean(selected?.request_id)||formal;
 return <div className={styles.root}><header><h1>mikke IDがない先生の登録</h1><p>mikke IDがない先生も、氏名と認定情報を先に保存できます。</p><p className={styles.note}>下書き保存の後に正式登録すると、登録講師1人として数えます。複数の認定講座は同じ先生に追加してください。</p></header>
 {error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
 <div className={styles.actions}><button disabled={busy||loading||!hq} onClick={()=>edit(null)}>名簿に追加</button><button disabled={busy||loading} onClick={()=>{setSelected(null);setId('');setNotice('');void refresh();}}>再読み込み</button></div>
 {loading?<p>名簿を読み込み中…</p>:<ul className={styles.list}>{rows.map(row=><li key={row.id}><button onClick={()=>edit(row)} disabled={busy}><strong>{row.full_name}</strong><span>{row.instructor_number||'番号未設定'}</span><small>{row.withdrawn_at?'登録解除済み':row.registered_at?(row.confirmed_at?'本人連携済み':'正式登録・ID未連携'):row.confirmed_at?'下書き・本人確認済み':'下書き'}</small></button></li>)}</ul>}
 {!loading&&!rows.length&&<p>「名簿に追加」から先生の情報を入力してください。</p>}
 {id&&<section className={styles.card} aria-label="名簿の編集"><h2>{selected?'保存した名簿を編集':'先生の情報を入力'}</h2><fieldset disabled={busy||locked}><label>氏名<input required maxLength={200} value={name} onChange={e=>setName(e.target.value)}/></label><label>講師番号（正式登録時に必要）<input maxLength={80} value={number} onChange={e=>setNumber(e.target.value)}/></label>
 <h3>認定情報</h3>{certs.map((cert,i)=><div className={styles.cert} key={i}><label>認定講座<select value={cert.courseId} onChange={e=>setCerts(certs.map((x,j)=>j===i?{...x,courseId:e.target.value}:x))}><option value="">選択してください</option>{courses.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label><div className={styles.dates}><label>認定日<input type="date" value={cert.certifiedAt??''} onChange={e=>setCerts(certs.map((x,j)=>j===i?{...x,certifiedAt:e.target.value}:x))}/></label><label>更新期限（任意）<input type="date" value={cert.renewalDue??''} onChange={e=>setCerts(certs.map((x,j)=>j===i?{...x,renewalDue:e.target.value}:x))}/></label></div><button onClick={()=>setCerts(certs.filter((_,j)=>j!==i))}>この認定情報を外す</button></div>)}<button onClick={()=>setCerts([...certs,{courseId:'',certifiedAt:null,renewalDue:null}])}>認定講座を追加</button><button className={styles.primary} onClick={()=>void run('save',{name,number,certifications:certs})}>名簿を保存する</button></fieldset>
 {selected&&!withdrawn&&<section className={styles.link}><h3>先生へのメール案内</h3><p>本人が受け取るメールアドレスを確認して入力してください。メールアドレスがなくても正式登録できます。</p><label>連絡先メールアドレス（任意）<input type="email" maxLength={254} value={email} disabled={busy} onChange={e=>setEmail(e.target.value)}/></label><button disabled={busy||email===(selected.contact_email??'')} onClick={()=>void run('set_contact',{email})}>連絡先を保存する</button>{formal&&!selected.confirmed_at&&<>{!selected.contact_email?<p className={styles.note}>案内要確認：連絡先を保存してから本人確認の案内を作成してください。</p>:<><p>このメールアドレスを確認済みのmikkeアカウントで、先生自身に連携を承諾してもらいます。リンクの有効期限は7日間です。</p><button disabled={busy||email!==(selected.contact_email??'')} onClick={()=>void run('invite_email',{})}>{selected.email_invitation_pending?'同じ案内の受付状態を確認する':'本人確認の案内を作成する'}</button>{selected.email_invitation_pending&&<button disabled={busy||email!==(selected.contact_email??'')} onClick={()=>{if(window.confirm('以前の本人確認リンクを無効にして案内を作り直しますか？'))void run('reissue_email',{});}}>リンクを無効にして再発行する</button>}</>}</>}</section>}
 {selected&&!selected.confirmed_at&&!withdrawn&&<section className={styles.link}><h3>本人のmikke IDと連携する</h3><p>先生がmikkeに登録したら、本人のIDを確認して入力してください。リンクは指定した本人だけが承諾できます。</p><label>本人のmikke ID<input value={handle} onChange={e=>setHandle(e.target.value)} disabled={busy||Boolean(selected.request_id)} placeholder="@mikke_id"/></label>{!selected.request_id?<button disabled={busy||!handle.trim()} onClick={()=>void run('request_link',{handle})}>本人確認リンクを作る</button>:<><p>有効期限は作成から7日間です。</p><label>本人へ渡す確認リンク<input readOnly value={typeof window==='undefined'?'':`${window.location.origin}/academy/instructor-link/${selected.request_id}`}/></label><button disabled={busy} onClick={()=>void run('cancel_link',{})}>確認依頼を取り消す</button></>}</section>}
 {selected&&!formal&&<section className={styles.link}><p>正式登録した時点から登録講師1人として数えます。講師番号と認定日を確認してください。</p><button disabled={busy||dirty} className={styles.primary} onClick={()=>void run('register',{})}>正式登録する</button>{dirty&&<p>変更を保存してから正式登録してください。</p>}</section>}
 {formal&&!withdrawn&&<section className={styles.link}><h3>この先生の認定講座を追加</h3><label>認定講座<select value={newCert.courseId} onChange={e=>setNewCert({...newCert,courseId:e.target.value})}><option value="">選択してください</option>{courses.filter(c=>!selected?.certifications.some(x=>x.courseId===c.id)).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>認定日<input type="date" value={newCert.certifiedAt??''} onChange={e=>setNewCert({...newCert,certifiedAt:e.target.value})}/></label><label>更新期限（任意）<input type="date" value={newCert.renewalDue??''} onChange={e=>setNewCert({...newCert,renewalDue:e.target.value})}/></label><button disabled={busy||!newCert.courseId||!newCert.certifiedAt} onClick={()=>void run('add_certification',{certification:newCert})}>認定講座を追加する</button>{!selected?.confirmed_at&&<button disabled={busy} onClick={()=>{if(window.confirm('この先生の正式登録を解除しますか？認定情報は残ります。'))void run('withdraw',{});}}>登録を解除する</button>}</section>}
 {selected?.confirmed_at&&<p className={styles.note}>{formal?'本人との連携が完了しました。現在の登録状況・活動設定・登録解除は講師一覧で確認できます。':'本人確認済みです。正式登録はまだ行っていません。'}</p>}</section>}
 </div>;
}

