"use client";
import type {ReactNode} from "react";
import type {MikkeContentBlock as Block} from "@/lib/mikkeos/content/types";
export type ContentImagePicker=(value:string,onChange:(url:string)=>void)=>ReactNode;
const input="mt-2 w-full rounded-lg border border-[var(--mikke-line)] bg-white p-3 text-sm";
export function MikkeLayoutFields({block,onChange,pickImage}:{block:Block;onChange:(block:Block)=>void;pickImage:ContentImagePicker}) {
  const field=(label:string,key:"title"|"text"|"buttonLabel"|"url")=><label className="block text-sm">{label}{key==="text"?<textarea className={input} value={block[key]??""} onChange={e=>onChange({...block,[key]:e.target.value})}/>:<input className={input} value={block[key]??""} onChange={e=>onChange({...block,[key]:e.target.value})}/>}</label>;
  if(block.type==="image-text")return <div className="space-y-4"><label className="text-sm">画像の位置<select aria-label="画像の位置" className={input} value={block.imageSide??"left"} onChange={e=>onChange({...block,imageSide:e.target.value as "left"|"right"})}><option value="left">左</option><option value="right">右</option></select></label>{pickImage(block.imageUrl??"",imageUrl=>onChange({...block,imageUrl}))}<label className="block text-sm">画像のリンク先URL（任意）<input type="url" placeholder="https://" className={input} value={block.imageLink??""} onChange={e=>onChange({...block,imageLink:e.target.value})}/></label>{field("見出し","title")}{field("文章","text")}<label className="block text-sm">画像の説明<input className={input} value={block.alt??""} onChange={e=>onChange({...block,alt:e.target.value})}/></label></div>;
  if(block.type==="gallery")return <div className="space-y-4"><label>列数<select aria-label="画像グリッドの列数" value={block.columns??3} onChange={e=>onChange({...block,columns:Number(e.target.value) as 2|3})} className={input}><option value={2}>2列</option><option value={3}>3列</option></select></label>{(block.images??[]).map((image,index)=><div key={index} className="rounded-lg border border-[var(--mikke-line)] p-3">{pickImage(image.url,url=>onChange({...block,images:block.images!.map((item,i)=>i===index?{...item,url}:item)}))}<label className="block text-sm">画像 {index+1} の説明<input className={input} value={image.alt} onChange={e=>onChange({...block,images:block.images!.map((item,i)=>i===index?{...item,alt:e.target.value}:item)})}/></label><label className="block text-sm">画像 {index+1} のリンク先URL（任意）<input type="url" placeholder="https://" className={input} value={image.href??""} onChange={e=>onChange({...block,images:block.images!.map((item,i)=>i===index?{...item,href:e.target.value}:item)})}/></label><div className="mt-2 flex gap-4"><button disabled={index===0} onClick={()=>{const images=[...block.images!];[images[index-1],images[index]]=[images[index],images[index-1]];onChange({...block,images});}} type="button" className="disabled:opacity-30">前へ</button><button type="button" onClick={()=>onChange({...block,images:block.images!.filter((_,i)=>i!==index)})}>画像を削除</button></div></div>)}<button type="button" onClick={()=>onChange({...block,images:[...(block.images??[]),{url:"",alt:""}]})}>＋ 画像を追加</button></div>;
  if(block.type==="links")return <div className="space-y-4">{field("リンク集の見出し","title")}{(block.links??[]).map((link,index)=><div key={index} className="rounded-lg border border-[var(--mikke-line)] p-3"><label className="block text-sm">リンク名<input className={input} value={link.label} onChange={e=>onChange({...block,links:block.links!.map((item,i)=>i===index?{...item,label:e.target.value}:item)})}/></label><label className="block text-sm">リンク先URL<input className={input} value={link.url} onChange={e=>onChange({...block,links:block.links!.map((item,i)=>i===index?{...item,url:e.target.value}:item)})}/></label><button type="button" className="mt-2 text-sm" onClick={()=>onChange({...block,links:block.links!.filter((_,i)=>i!==index)})}>リンクを削除</button></div>)}<button type="button" onClick={()=>onChange({...block,links:[...(block.links??[]),{label:"",url:""}]})}>＋ リンクを追加</button></div>;
  return <div className="space-y-4">{field("見出し","title")}{field("説明文","text")}{field("ボタンの文字","buttonLabel")}{field("ボタンのリンク先URL","url")}</div>;
}
