import type {ComponentType} from "react";
import type {MikkeContentBlock as MediaBlock} from "@/lib/mikkeos/content/types";
type ImageProps={src:string;alt:string;className?:string};
function safeHref(value:string){if(/[\s\\]/.test(value))return false;if(/^\/(?!\/)/.test(value))return true;try{return ["https:","http:"].includes(new URL(value).protocol);}catch{return false;}}
function LinkedImage({href,Image,...props}:ImageProps & {href?:string;Image:ComponentType<ImageProps>}) {const image=<Image {...props}/>;return href&&safeHref(href)?<a href={href} target="_blank" rel="noopener noreferrer" className={"block "+(props.className?.includes("sm:order-2")?"sm:order-2":"")}>{image}</a>:image;}
function RichText({block}:{block:MediaBlock}) { return <>{(block.richText ?? [{text:block.text??""}]).map((run,index)=>{const text=<span style={{fontWeight:run.bold?700:undefined,textDecoration:run.strike?"line-through":undefined}}>{run.text}</span>;return run.href&&safeHref(run.href)?<a key={index} href={run.href} target="_blank" rel="noopener noreferrer" className="text-[var(--mikke-primary)] underline underline-offset-4">{text}</a>:<span key={index}>{text}</span>;})}</>; }

function Block({ block, Image, LinkCard }: { block: MediaBlock; Image: ComponentType<ImageProps>; LinkCard: ComponentType<{block:MediaBlock}> }) {
  if(block.type === "image-text")return <section className="my-8 grid gap-6 sm:grid-cols-2 sm:items-center">{block.imageUrl?<LinkedImage Image={Image} href={block.imageLink} src={block.imageUrl} alt={block.alt??""} className={"w-full rounded-xl object-contain "+(block.imageSide==="right"?"sm:order-2":"")}/>:null}<div>{block.title?<h3 className="text-xl font-bold">{block.title}</h3>:null}<p className="mt-3 whitespace-pre-wrap leading-8">{block.text}</p></div></section>;
  if(block.type === "gallery")return <div className={"my-8 grid grid-cols-2 gap-4 "+(block.columns===2?"":"sm:grid-cols-3")}>{(block.images??[]).filter(image=>image.url).map((image,index)=><figure key={index}><LinkedImage Image={Image} href={image.href} src={image.url} alt={image.alt} className="aspect-square w-full rounded-lg object-cover"/>{image.caption?<figcaption className="mt-2 text-xs">{image.caption}</figcaption>:null}</figure>)}</div>;
  if(block.type === "links")return <section className="my-7">{block.title?<h3 className="mb-3 font-bold">{block.title}</h3>:null}<ul className="space-y-2">{(block.links??[]).filter(link=>safeHref(link.url)).map((link,index)=><li key={index}><a href={link.url} target="_blank" rel="noopener noreferrer" className="block rounded-lg border border-[var(--mikke-line)] p-3">{link.label||link.url} ↗</a></li>)}</ul></section>;
  if(block.type === "cta")return <section className="my-8 rounded-xl bg-[var(--mikke-surface-soft)] p-6 text-center">{block.title?<h3 className="text-xl font-bold">{block.title}</h3>:null}{block.text?<p className="mt-3 whitespace-pre-wrap leading-7">{block.text}</p>:null}{safeHref(block.url??"")?<a href={block.url} target="_blank" rel="noopener noreferrer" className="mt-4 inline-block rounded-full bg-[var(--mikke-primary)] px-6 py-3 font-bold text-white">{block.buttonLabel||"詳しく見る"}</a>:null}</section>;
  if (block.type === "heading") return block.level === 3 ? <h3 style={{textAlign:block.align}} className="mt-9 text-xl font-black"><RichText block={block}/></h3> : <h2 style={{textAlign:block.align}} className="mt-11 text-2xl font-bold"><RichText block={block}/></h2>;
  if (block.type === "image") return block.imageUrl ? <figure className="my-8"><LinkedImage Image={Image} href={block.imageLink} src={block.imageUrl} alt={block.alt ?? ""} className="max-h-[680px] w-full rounded-2xl object-contain" />{block.caption ? <figcaption className="mt-2 text-center text-xs text-[var(--mikke-muted)]">{block.caption}</figcaption> : null}</figure> : null;
  if (block.type === "quote") return !block.text?.trim() ? null : <blockquote className="my-7 border-l-4 border-[var(--mikke-primary)] bg-[var(--mikke-primary-soft)] px-5 py-4 text-base font-semibold leading-8"><p className="whitespace-pre-wrap"><RichText block={block}/></p>{block.attribution ? <cite className="mt-2 block text-xs not-italic text-[var(--mikke-muted)]">— {block.attribution}</cite> : null}</blockquote>;
  if (block.type === "list") return <ul className="my-5 list-disc space-y-2 pl-6 leading-8">{(block.items ?? []).filter(Boolean).map((item, index) => <li key={`${block.id}_${index}`}>{item}</li>)}</ul>;
  if (block.type === "divider") return <hr className="my-9 border-0 border-t-2 border-[var(--mikke-muted)]" />;
  if (block.type === "link" || block.type === "video") return <LinkCard block={block}/>;
  return <p style={{textAlign:block.align}} className="my-4 break-words whitespace-pre-wrap text-base leading-8 [overflow-wrap:anywhere] sm:text-[17px]"><RichText block={block}/></p>;
}

export function MikkeContentRenderer({blocks,Image,LinkCard}:{blocks:MediaBlock[];Image:ComponentType<ImageProps>;LinkCard:ComponentType<{block:MediaBlock}>}) {return <>{blocks.map(block=><Block key={block.id} block={block} Image={Image} LinkCard={LinkCard}/>)}</>;}
