"use client";
import {useEffect,useRef,type ComponentType} from "react";
import type {MikkeContentBlock as MediaBlock} from "@/lib/mikkeos/content/types";
import {MikkeLayoutFields} from "./MikkeLayoutFields";
import {MikkeRichWriting} from "./MikkeRichWriting";
export type ContentImagePickerProps={currentUrl?:string;onSelect:(asset:{publicUrl:string;id?:string;originalName?:string})=>void};
const inputClass="mt-2 w-full rounded-xl border border-[var(--mikke-line)] bg-white px-3 py-2 text-sm";
function WritingArea({ value, onChange, label, placeholder, title = false, heading, onSplit, onUrlPaste }: { value: string; onChange: (value: string) => void; label: string; placeholder: string; title?: boolean; heading?: 2 | 3; onSplit?: (start:number,end:number)=>void; onUrlPaste?: (url:string)=>void }) {
  const ref = useRef<HTMLTextAreaElement>(null);
  useEffect(() => { if (ref.current) { ref.current.style.height = "0px"; ref.current.style.height = ref.current.scrollHeight + "px"; } }, [value]);
  return <textarea ref={ref} onKeyDown={event=>{if(onSplit && event.key==="Enter" && !event.shiftKey && !event.nativeEvent.isComposing && event.keyCode!==229){event.preventDefault();onSplit(event.currentTarget.selectionStart,event.currentTarget.selectionEnd);}}} onPaste={event=>{const text=event.clipboardData.getData("text/plain").trim();if(!value.trim()&&onUrlPaste&&/^https:\/\/\S+$/.test(text)){try{new URL(text);event.preventDefault();onUrlPaste(text);}catch{}}}} style={{ fontSize: title ? "clamp(1.5rem, 3vw, 2rem)" : heading === 2 ? "1.5rem" : heading === 3 ? "1.25rem" : "1.0625rem", fontWeight: title || heading ? 700 : 400, lineHeight: title || heading ? 1.6 : 2 }} aria-label={label} value={value} placeholder={placeholder} rows={1} onChange={(event) => onChange(event.target.value)} className="w-full resize-none overflow-hidden border-0 bg-transparent py-3 outline-none placeholder:text-[var(--mikke-muted)]" />;
}

export function MikkeBlockFields({ block, onChange, onSplit, ImagePicker, LinkEditor }: {ImagePicker:ComponentType<ContentImagePickerProps>;LinkEditor:ComponentType<{block:MediaBlock;onChange:(block:MediaBlock)=>void}>; block: MediaBlock; onChange: (block: MediaBlock) => void; onSplit:(start:number,end:number)=>void }) {
  if (["links","image-text","gallery","cta"].includes(block.type)) return <MikkeLayoutFields block={block} onChange={onChange} pickImage={(url,choose)=><ImagePicker currentUrl={url} onSelect={asset=>choose(asset.publicUrl,asset.id)}/>}/>;
  if (block.type === "divider") return <hr className="my-9 border-0 border-t-2 border-[var(--mikke-muted)]" />;
  if (block.type === "image") return <div className="space-y-3"><ImagePicker currentUrl={block.imageUrl} onSelect={(asset) => onChange({ ...block, imageUrl: asset.publicUrl, imageAssetId: asset.id, alt: block.alt || asset.originalName })} /><label className="block text-xs font-bold">画像のリンク先URL（任意）<input type="url" placeholder="https://" value={block.imageLink ?? ""} onChange={event=>onChange({...block,imageLink:event.target.value})} className={inputClass}/></label><label className="block text-xs font-bold">画像の内容（読み上げ用）<input value={block.alt ?? ""} onChange={(event) => onChange({ ...block, alt: event.target.value })} className={inputClass} /></label><label className="block text-xs font-bold">写真の下に表示するひとこと（任意）<input value={block.caption ?? ""} onChange={(event) => onChange({ ...block, caption: event.target.value })} className={inputClass} /></label></div>;
  if (block.type === "paragraph" || block.type === "heading") return <MikkeRichWriting block={block} onChange={onChange} onSplit={onSplit} onUrlPaste={url=>onChange({id:block.id,type:"link",url,title:""})}/>;
  if (block.type === "quote") return <div><p className="mb-3 text-xs text-[var(--mikke-muted)]">他の文章を引用するときに使います。</p><blockquote className="border-l-4 border-[var(--mikke-primary)] bg-[var(--mikke-primary-soft)] px-5 py-4"><WritingArea label="引用文" placeholder="引用する文章" value={block.text ?? ""} onChange={text => onChange({...block,text})}/><input aria-label="引用元" placeholder="引用元の名前やURL" value={block.attribution ?? ""} onChange={(event) => onChange({ ...block, attribution: event.target.value })} className={inputClass}/></blockquote></div>;
  if (block.type === "list") return <div><ul className="my-5 list-none space-y-2 pl-1 leading-8">{(block.items?.length ? block.items : [""]).map((item,index) => <li key={index} className="flex items-start gap-3"><span aria-hidden="true" className="shrink-0 leading-8">•</span><textarea aria-label={`箇条書き ${index+1}`} rows={1} value={item} placeholder="項目を入力" className="block min-w-0 flex-1 resize-y border-0 bg-transparent p-0 text-[17px] leading-8 outline-none" onChange={event => {const items=[...(block.items?.length ? block.items : [""])];items.splice(index,1,...event.target.value.split("\n"));onChange({...block,items});}}/></li>)}</ul><button type="button" className="text-sm text-[var(--mikke-primary)]" onClick={()=>onChange({...block,items:[...(block.items?.length ? block.items : [""]),""]})}>＋ 項目を追加</button></div>;
  if (block.type === "link" || block.type === "video") return <LinkEditor block={block} onChange={onChange}/>;
  return <WritingArea onSplit={onSplit} onUrlPaste={url=>onChange({id:block.id,type:"link",url,title:""})} label="本文の文章" value={block.text ?? ""} onChange={(text) => onChange({ ...block, text })} placeholder="本文を書いてみましょう" />;
}
