export type ReaderProfile={name:string;icon:string;avatar:string;bio:string;destination:"none"|"profile"|"media"};
export type MyMediaState={version:1;profile:ReaderProfile;following:string[];notifyReplies:boolean};
export const MY_MEDIA_EVENT="media-my-changed";
export function defaultMyMedia():MyMediaState{return {version:1,profile:{name:"読者の見本",icon:"🌱",avatar:"",bio:"",destination:"none"},following:[],notifyReplies:true};}
export function myMediaKey(account:string){return "mikke.media.my.demo.v1:"+account;}
export function readMyMedia(account:string):MyMediaState{const raw=localStorage.getItem(myMediaKey(account));if(!raw)return defaultMyMedia();const value=JSON.parse(raw);if(value.version!==1||!value.profile||typeof value.profile.name!=="string"||typeof value.profile.icon!=="string"||typeof value.profile.avatar!=="string"||typeof value.profile.bio!=="string"||!Array.isArray(value.following)||!value.following.every((id:unknown)=>typeof id==="string")||typeof value.notifyReplies!=="boolean")throw Error("My Mediaを読み込めませんでした。");return value;}
export function saveMyMedia(account:string,value:MyMediaState){const name=value.profile.name.trim();if(!name||name.length>40)throw Error("名前は1〜40文字で入力してください。");if(value.profile.bio.length>200)throw Error("ひとことは200文字以内で入力してください。");if(value.profile.avatar&&!/^data:image\/(png|jpeg|webp);base64,[a-zA-Z0-9+/=]+$/.test(value.profile.avatar))throw Error("アイコンの画像を選び直してください。");if(value.profile.avatar.length>100000)throw Error("アイコンの画像が大きすぎます。");const next={...value,profile:{...value.profile,name},following:[...new Set(value.following)]};localStorage.setItem(myMediaKey(account),JSON.stringify(next));window.dispatchEvent(new Event(MY_MEDIA_EVENT));return next;}
export function toggleFollow(account:string,siteId:string){const state=readMyMedia(account);return saveMyMedia(account,{...state,following:state.following.includes(siteId)?state.following.filter(id=>id!==siteId):[...state.following,siteId]});}
export function commentBoardKey(scope:string){return "mikke.media.comments.demo.v1:"+scope;}
