"use client";
import {useCallback,useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {supabase} from '@/lib/supabase/client';
import {mediaSocialRpc,type SocialBoard,type ReaderComment,type ReaderProfile} from '@/lib/media-app/social-cloud';
import styles from './MediaCloudSocial.module.css';

export function useMediaReaderIdentity(){
 const [subject,setSubject]=useState<string|null|undefined>(undefined);
 useEffect(()=>{let alive=true;let revision=0;const {data:listener}=supabase.auth.onAuthStateChange((_event,session)=>{revision++;if(alive)setSubject(session?.user&&!session.user.is_anonymous?session.user.id:null);});const captured=revision;void supabase.auth.getUser().then(({data})=>{if(alive&&captured===revision)setSubject(data.user&&!data.user.is_anonymous?data.user.id:null);});return()=>{alive=false;listener.subscription.unsubscribe();};},[]);
 return subject;
}
export function MediaReaderAvatar({profile}:{profile:Pick<ReaderProfile,'avatar'|'icon'|'name'>}){return profile.avatar?<img src={profile.avatar} alt="" className={styles.avatar}/>:<span className={styles.avatar} aria-hidden>{profile.icon||profile.name.slice(0,1)}</span>;}
async function measure(site:string,article:string,kind:'read'|'share'){await fetch('/api/media/measure',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({site,article,kind}),keepalive:true});}
export function MediaCloudSocial({siteSlug,articleSlug}:{siteSlug:string;articleSlug?:string}){
 const subject=useMediaReaderIdentity();const [board,setBoard]=useState<SocialBoard|null>(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[body,setBody]=useState(''),[reply,setReply]=useState<ReaderComment|null>(null),[attempt,setAttempt]=useState(0);
 const generation=useRef(0);const pending=useRef(false);const input=useRef<HTMLTextAreaElement>(null);
 useEffect(()=>{const current=++generation.current;setBoard(null);setBusy(false);pending.current=false;setMessage('');setBody('');setReply(null);if(subject===undefined)return;void mediaSocialRpc<SocialBoard|null>('media_social_read',{p_site:siteSlug,p_article:articleSlug??null},subject).then(result=>{if(current===generation.current){setBoard(result);if(!result)setMessage('この記事は現在公開されていません。');}}).catch(e=>{if(current===generation.current)setMessage(e.message);});return()=>{generation.current++;};},[subject,siteSlug,articleSlug,attempt]);
 useEffect(()=>{if(!articleSlug)return;const timer=setTimeout(()=>{void measure(siteSlug,articleSlug,'read').catch(()=>{});},1500);return()=>clearTimeout(timer);},[siteSlug,articleSlug]);
 async function act(action:string,payload:Record<string,unknown>,success='保存しました。'){
  if(!subject||pending.current)return false;pending.current=true;const current=generation.current;setBusy(true);setMessage('');
  try{const result=await mediaSocialRpc<SocialBoard>('media_social_action',{p_site:siteSlug,p_article:articleSlug??null,p_action:action,p_payload:payload},subject);if(current!==generation.current)return false;setBoard(result);setMessage(success);return true;}catch(e){if(current===generation.current)setMessage(e instanceof Error?e.message:'保存できませんでした。');return false;}finally{if(current===generation.current){pending.current=false;setBusy(false);}}
 }
 async function share(){try{const url=window.location.href.split('#')[0];if(navigator.share)await navigator.share({url});else await navigator.clipboard.writeText(url);setMessage('共有リンクを用意しました。');if(articleSlug)void measure(siteSlug,articleSlug,'share').catch(()=>{});}catch{setMessage('共有を取り消しました。');}}
 function row(c:ReaderComment){return <article id={`comment-${c.id}`} className={styles.comment} key={c.id}><div className={styles.byline}>{c.author.href?<Link href={c.author.href}><MediaReaderAvatar profile={c.author}/></Link>:<MediaReaderAvatar profile={c.author}/>}<strong>{c.author.name}</strong>{c.owner?<span>発信者</span>:null}<time>{new Date(c.createdAt).toLocaleDateString('ja-JP')}</time>{subject&&!c.mine&&c.status==='visible'?<button className={styles.report} disabled={busy} onClick={()=>void act('report',{id:c.id},'運営に通報を送りました。')}>通報</button>:null}</div>{c.held?<p className={styles.muted}>運営が確認中のため公開されません</p>:null}{c.status==='pending'?<p className={styles.muted}>発信者の確認後に公開されます</p>:c.status==='hidden'?<p className={styles.muted}>非表示</p>:null}{c.replyTo?<p className={styles.muted}>{board?.comments.find(x=>x.id===c.replyTo)?.author.name??'コメント'}さんへの返信</p>:null}<p className={styles.body}>{c.status==='deleted'?'このコメントは削除されました。':c.body}</p><div className={styles.actions}>{c.status==='visible'&&!c.held?<><button disabled={!subject||busy} aria-pressed={c.thanked} onClick={()=>void act('thanks',{id:c.id,value:!c.thanked},c.thanked?'ありがとうを取り消しました。':'ありがとうを伝えました。')}>♡ ありがとう {c.thanks||''}</button>{board?.mode!=='closed'&&!board?.blocked&&!c.closed&&!board?.comments.find(x=>x.id===c.rootId)?.closed&&(!c.rootId||board?.comments.some(x=>x.id===c.rootId&&['visible','deleted'].includes(x.status)))?<button disabled={!subject||busy} onClick={()=>{setReply(c);input.current?.focus();}}>返信</button>:null}</>:null}{c.mine&&c.status!=='deleted'?<button disabled={busy} onClick={()=>{if(window.confirm('このコメントを削除しますか？'))void act('delete',{id:c.id},'コメントを削除しました。');}}>削除</button>:null}{board?.owner?<>{!c.held&&(c.status==='pending'||c.status==='hidden')?<button disabled={busy} onClick={()=>void act('approve',{id:c.id},'コメントを公開しました。')}>承認して表示</button>:c.status==='visible'?<button disabled={busy} onClick={()=>void act('hide',{id:c.id},'非表示にしました。')}>非表示</button>:null}{!c.rootId?<button disabled={busy} onClick={()=>void act('close',{id:c.id,value:!c.closed})}>{c.closed?'返信を再開':'返信を締め切る'}</button>:null}{!c.owner?<><button disabled={busy} onClick={()=>void act('block',{id:c.id,value:true},'この読者からの投稿を停止しました。')}>投稿を停止</button><button disabled={busy} onClick={()=>void act('block',{id:c.id,value:false},'投稿の停止を解除しました。')}>停止を解除</button></>:null}</>:null}</div></article>;}
 const login=`/login?next=${encodeURIComponent(`/media/${siteSlug}${articleSlug?`/${articleSlug}`:''}`)}`;
 return <section className={styles.panel} id="media-comments">{board?<><div className={styles.actions}>{articleSlug?<><button disabled={!subject||busy} aria-pressed={board.favorite} onClick={()=>void act('favorite',{value:!board.favorite})}>♡ お気に入り</button><button disabled={!subject||busy} aria-pressed={board.saved} onClick={()=>void act('saved',{value:!board.saved})}>{board.saved?'保存済み':'あとで読む'}</button><button onClick={()=>void share()}>共有</button></>:null}<button disabled={!subject||busy} aria-pressed={board.following} onClick={()=>void act('follow',{value:!board.following})}>{board.following?'フォロー中':'フォロー'}</button><Link href="/apps/media/my">My Media</Link></div>{!subject?<p className={styles.muted}><Link href={login}>mikkeIDでログイン</Link>すると、保存やフォロー、コメントができます。</p>:null}{articleSlug?<><h2 className="my-4 font-bold">コメント</h2>{board.owner?<label className={styles.muted}>コメントの受付 <select value={board.mode} disabled={busy} onChange={e=>void act('mode',{mode:e.target.value})}><option value="review">確認してから表示</option><option value="open">すぐに表示</option><option value="closed">受け付けない</option></select></label>:null}{board.comments.filter(c=>!c.rootId||!board.comments.some(root=>root.id===c.rootId)).map(c=><div key={c.id}>{row(c)}<div className={styles.reply}>{board.comments.filter(x=>x.rootId===c.id).map(row)}</div></div>)}{!board.comments.length?<p className={styles.muted}>まだコメントはありません。</p>:null}{subject&&board.mode!=='closed'&&!board.blocked?<form className={styles.form} onSubmit={async e=>{e.preventDefault();if(await act('comment',{body,replyTo:reply?.id??null},board.mode==='review'&&!board.owner?'コメントを送りました。確認後に公開されます。':'コメントを公開しました。')){setBody('');setReply(null);}}}>{reply?<div>{reply.author.name}さんへ返信 <button type="button" onClick={()=>setReply(null)}>取り消す</button></div>:null}<textarea ref={input} required maxLength={2000} aria-label="コメント" placeholder="感想や伝えたいことをどうぞ" value={body} onChange={e=>setBody(e.target.value)}/><div className={styles.actions}><button className={styles.primary} disabled={busy||!body.trim()}>コメントを送る</button><Link href="/apps/media/my?tab=profile">名前・アイコンを設定</Link></div></form>:board.mode==='closed'?<p className={styles.muted}>現在コメントを受け付けていません。</p>:null}</>:null}</>:!message?<p className={styles.muted}>読み込んでいます…</p>:null}{message?<p role="status" className={styles.muted}>{message}{!board?<button onClick={()=>setAttempt(x=>x+1)}>再読み込み</button>:null}</p>:null}</section>;
}
export function MediaCloudFollow({siteSlug}:{siteSlug:string}){return <MediaCloudSocial siteSlug={siteSlug}/>;}

export function MediaCloudAnalytics({siteId}:{siteId:string}){
 const subject=useMediaReaderIdentity();const [stats,setStats]=useState<Record<string,number>|null>(null),[error,setError]=useState(false);
 const refresh=useCallback(()=>{if(!subject)return()=>{};let live=true;setStats(null);setError(false);void mediaSocialRpc<Record<string,number>>('media_owner_analytics',{p_site:siteId},subject).then(x=>{if(live)setStats(x);}).catch(()=>{if(live)setError(true);});return()=>{live=false;};},[subject,siteId]);useEffect(refresh,[refresh]);
 return <section className={styles.panel}><h2 className="mb-3 font-bold">記事に届いた反応</h2>{error?<p role="alert">集計を読み込めませんでした。</p>:<div className={styles.stats}>{[['read','読まれた'],['saved','保存'],['favorite','お気に入り'],['share','共有']].map(([key,label])=><div key={key}><span className="text-xs">{label}</span><strong>{stats?.[key]??'—'}</strong></div>)}</div>}<p className={styles.muted}>閲覧・共有は同じ接続とブラウザで1日1回を数える参考値です。保存・お気に入りは現在の件数です。</p></section>;
}
