"use client";
import {useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {useSearchParams} from 'next/navigation';
import {useAuth} from '@/components/AuthGate';
import {mediaSocialRpc,readerAvatar,type ReaderHome,type ReaderProfile} from '@/lib/media-app/social-cloud';
import {useMediaRepository} from './MediaRepository';
import {MyMediaLocal} from './MyMediaLocal';
import {MediaReaderAvatar} from './MediaCloudSocial';
import styles from './MediaCloudSocial.module.css';

const tabs=[['saved','保存した記事'],['favorite','お気に入り'],['following','フォロー中'],['notices','返信通知'],['profile','プロフィール']];
export function MyMedia(){const repository=useMediaRepository();return repository.cloud?<CloudMyMedia/>:<MyMediaLocal/>;}
export function MyMediaProfile(){const repository=useMediaRepository();return repository.cloud?<CloudMyMedia/>:<MyMediaLocal publicProfile/>;}
function CloudMyMedia(){
 const {profile}=useAuth();const subject=profile.user_id;const params=useSearchParams();
 const [home,setHome]=useState<ReaderHome|null>(null),[form,setForm]=useState<ReaderProfile|null>(null),[tab,setTab]=useState(tabs.some(([key])=>key===params.get('tab'))?params.get('tab')!:'saved'),[query,setQuery]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[attempt,setAttempt]=useState(0);
 const generation=useRef(0),file=useRef<HTMLInputElement>(null);
 useEffect(()=>{const id=++generation.current;setHome(null);setForm(null);setMessage('');setBusy(false);void mediaSocialRpc<ReaderHome>('media_reader_home',{},subject).then(x=>{if(id===generation.current){setHome(x);setForm(x.profile);}}).catch(e=>{if(id===generation.current)setMessage(e.message);});return()=>{generation.current++;};},[subject,attempt]);
 async function update(action:string,payload:Record<string,unknown>,success='保存しました。'){
  if(busy)return;const id=generation.current;setBusy(true);setMessage('');try{const next=await mediaSocialRpc<ReaderHome>('media_reader_home',{p_action:action,p_payload:payload},subject);if(id===generation.current){setHome(next);if(action==='profile')setForm(next.profile);setMessage(success);}}catch(e){if(id===generation.current)setMessage(e instanceof Error?e.message:'保存できませんでした。');}finally{if(id===generation.current)setBusy(false);}
 }
 async function choose(selected?:File){if(!selected)return;const id=generation.current;setBusy(true);try{const avatar=await readerAvatar(selected);if(id===generation.current)setForm(f=>f?{...f,avatar}:f);}catch(e){if(id===generation.current)setMessage(e instanceof Error?e.message:'画像を選び直してください。');}finally{if(id===generation.current)setBusy(false);}}
 if(!home||!form)return <main className={styles.panel}><h1 className="text-xl font-bold">My Media</h1><p role={message?'alert':undefined}>{message||'読み込んでいます…'}</p>{message?<button onClick={()=>setAttempt(x=>x+1)}>もう一度読み込む</button>:null}</main>;
 const articles=home.articles.filter(x=>x.kind===tab&&x.title.toLocaleLowerCase().includes(query.toLocaleLowerCase()));
 return <main className={styles.panel}><header className={styles.actions}><h1 className="text-xl font-bold">My Media</h1><Link href="/apps/media">発信者のホーム</Link></header><div className={`${styles.actions} my-4`}><MediaReaderAvatar profile={home.profile}/><strong>{home.profile.name}</strong></div><div className={styles.tabs} role="tablist" aria-label="My Media">{tabs.map(([key,label])=><button role="tab" aria-selected={tab===key} aria-pressed={tab===key} key={key} onClick={()=>{setTab(key);setMessage('');}}>{label}{key==='notices'&&home.notices.some(x=>!x.read)?` ${home.notices.filter(x=>!x.read).length}`:''}</button>)}</div>
 {(tab==='saved'||tab==='favorite')?<><input className="my-3" aria-label="記事を検索" placeholder="タイトルで探す" value={query} onChange={e=>setQuery(e.target.value)}/>{articles.map(x=><div className={styles.card} key={x.id}><Link href={x.href}><strong>{x.title}</strong><p className={styles.muted}>{x.site}</p></Link><button disabled={busy} onClick={()=>void update('remove',{id:x.id,kind:tab},'一覧から外しました。')}>外す</button></div>)}{!articles.length?<p className={styles.muted}>{query?'条件に合う記事がありません。':'気に入った記事をここから読み返せます。'}</p>:null}</>:null}
 {tab==='following'?<>{home.following.map(x=><div className={styles.card} key={x.id}><Link href={x.href}>{x.name}</Link><button disabled={busy} onClick={()=>void update('unfollow',{id:x.id},'フォローを解除しました。')}>解除</button></div>)}{home.following.length?<><h2 className="mt-5 font-bold">フォロー中の新着記事</h2>{home.feed.map(x=><div className={styles.card} key={x.id}><Link href={x.href}><strong>{x.title}</strong><p className={styles.muted}>{x.site}</p></Link></div>)}</>:<p className={styles.muted}>また読みたい発信者をフォローしてみてください。</p>}</>:null}
 {tab==='notices'?<><label className="my-4 flex items-center gap-2"><input style={{width:'auto'}} type="checkbox" disabled={busy} checked={home.notifyReplies} onChange={e=>void update('notifications',{value:e.target.checked})}/>自分への返信を通知する</label>{home.notices.map(x=><div className={styles.card} key={x.id}><Link href={x.href}>{x.read?'既読':'未読'} · {x.name}さんから返信</Link></div>)}{!home.notices.length?<p className={styles.muted}>新しい返信はここに届きます。</p>:<button disabled={busy} onClick={()=>void update('read_notices',{},'確認済みにしました。')}>すべて確認済みにする</button>}</>:null}
 {tab==='profile'?<form className={styles.form} onSubmit={e=>{e.preventDefault();void update('profile',form,'プロフィールを保存しました。コメントにも反映されます。');}}><label htmlFor="reader-name">コメントに表示する名前</label><input id="reader-name" required maxLength={40} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><label>アイコン</label><div className={styles.actions}><MediaReaderAvatar profile={form}/>{['🌱','🌼','☕','📚','🐈','🎨'].map(icon=><button type="button" key={icon} aria-label={`${icon}のアイコン`} aria-pressed={!form.avatar&&form.icon===icon} onClick={()=>setForm({...form,icon,avatar:''})}>{icon}</button>)}</div><input ref={file} hidden type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>{void choose(e.target.files?.[0]);e.target.value='';}}/><button type="button" disabled={busy} onClick={()=>file.current?.click()}>自分の画像を選ぶ</button><label htmlFor="reader-bio">ひとこと（任意）</label><textarea id="reader-bio" maxLength={200} value={form.bio} onChange={e=>setForm({...form,bio:e.target.value})}/><label htmlFor="reader-destination">コメントのアイコンから開くページ</label><select id="reader-destination" value={form.destination} onChange={e=>setForm({...form,destination:e.target.value as ReaderProfile['destination']})}><option value="none">リンクを表示しない</option><option value="profile">自分のプロフィール</option><option value="media">自分のMedia</option></select><p className={styles.muted}>保存・お気に入り・フォロー・通知の一覧は、あなたにだけ見えます。</p><button className={styles.primary} disabled={busy}>プロフィールを保存</button>{home.profile.destination!=='none'?<Link href={`/media-reader/${home.profile.id}`}>公開プロフィールを見る</Link>:null}</form>:null}
 {message?<p role="status" className={styles.muted}>{message}</p>:null}</main>;
}
