"use client";
import {useEffect,useRef,useState} from "react";
import {useSearchParams} from "next/navigation";
import {useAuth} from "@/components/AuthGate";
import {useMediaRepository} from "./MediaRepository";
import {MediaLink} from "./MediaNavigation";
import {readReactions,updateReaction,type LocalReaction} from "@/lib/media-app/local-analytics";
import {commentBoardKey,defaultMyMedia,MY_MEDIA_EVENT,readMyMedia,saveMyMedia,toggleFollow,type MyMediaState} from "@/lib/media-app/my-media";
import {emptyBoard,visibleNotices,type CommentBoard} from "@/lib/media-app/comment-threads";
import type {MediaSite,MediaArticle} from "@/lib/media-app/types";
import styles from "./MyMedia.module.css";
const tabs=[{id:"saved",label:"保存した記事"},{id:"favorite",label:"お気に入り"},{id:"following",label:"フォロー中"},{id:"notices",label:"返信通知"},{id:"profile",label:"プロフィール"}] as const;
export function ReaderAvatar({avatar,icon}:{avatar:string;icon:string}){return avatar?<img className={styles.avatar} src={avatar} alt=""/>:<span className={styles.avatar} aria-hidden>{icon}</span>;}
export function MyMediaLocal({publicProfile=false}:{publicProfile?:boolean}){
 const params=useSearchParams();
 const {profile}=useAuth();const repository=useMediaRepository();const account=profile.id;
 const [state,setState]=useState<MyMediaState>(defaultMyMedia),[form,setForm]=useState(defaultMyMedia().profile),[site,setSite]=useState<MediaSite|null>(null),[articles,setArticles]=useState<MediaArticle[]>([]),[reactions,setReactions]=useState<Record<string,LocalReaction>>({}),[board,setBoard]=useState<CommentBoard>(emptyBoard),[ready,setReady]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState(""),[tab,setTab]=useState<string>(tabs.some(t=>t.id===params.get("tab"))?params.get("tab")!:"saved"),[query,setQuery]=useState(""),[busy,setBusy]=useState(false);
 const [loadedAccount,setLoadedAccount]=useState("");
 const file=useRef<HTMLInputElement>(null);
 useEffect(()=>{let alive=true;setReady(false);setError("");if(repository.cloud)return;async function refresh(){try{const next=readMyMedia(account);const found=await repository.getOwnedMedia(account);const items=found?await repository.listMediaArticles(found.id):[];if(!alive)return;setState(next);setSite(found);setArticles(items.filter(a=>a.publishedSnapshot));if(found){const scope=found.ownerProfileId+":"+found.id;setReactions(readReactions(scope));const raw=localStorage.getItem(commentBoardKey(scope));setBoard(raw?JSON.parse(raw):emptyBoard());}else{setReactions({});setBoard(emptyBoard());}setLoadedAccount(account);setReady(true);setError("");}catch{if(alive){setReady(false);setError("My Mediaを読み込めませんでした。ページを開き直してください。");}}}void refresh();const sync=()=>void refresh();window.addEventListener("storage",sync);window.addEventListener(MY_MEDIA_EVENT,sync);window.addEventListener("media-reactions-changed",sync);return()=>{alive=false;window.removeEventListener("storage",sync);window.removeEventListener(MY_MEDIA_EVENT,sync);window.removeEventListener("media-reactions-changed",sync);};},[account,repository]);
 useEffect(()=>{if(ready)setForm(state.profile);},[ready,account]);
 function update(next:MyMediaState,text="保存しました。"){try{setState(saveMyMedia(account,next));setMessage(text);}catch(e){setMessage(e instanceof Error?e.message:"保存できませんでした。");}}
 async function image(file?:File){if(!file)return;setBusy(true);try{if(!/^image\/(jpeg|png|webp)$/.test(file.type)||file.size>15*1024*1024)throw Error("15MB以下のJPG・PNG・WebPを選んでください。");const bitmap=await createImageBitmap(file);try{const canvas=document.createElement("canvas");canvas.width=canvas.height=128;const context=canvas.getContext("2d");if(!context)throw Error("画像を読み込めませんでした。");const size=Math.min(bitmap.width,bitmap.height);context.drawImage(bitmap,(bitmap.width-size)/2,(bitmap.height-size)/2,size,size,0,0,128,128);setForm(p=>({...p,avatar:canvas.toDataURL("image/webp",.8)}));}finally{bitmap.close();}}catch(e){setMessage(e instanceof Error?e.message:"画像を選び直してください。");}finally{setBusy(false);}}
 const scope=site?site.ownerProfileId+":"+site.id:"";
 const notices=visibleNotices(board,"demo-reader","demo-writer").filter(n=>articles.some(a=>a.id===board.comments.find(c=>c.id===n.commentId)?.articleId));
 if(repository.cloud)return <main className={styles.page}><h1>My Media</h1><p>mikkeIDで保存した記事や返信を見返す機能は準備中です。</p><MediaLink href="/apps/media">Mediaに戻る</MediaLink></main>;
 if(!ready||loadedAccount!==account)return <main className={styles.page}><p role={error?"alert":undefined}>{error||"My Mediaを開いています…"}</p></main>;
 if(publicProfile)return <main className={styles.page}><header className={styles.header}><h1>プロフィール</h1><MediaLink href="/apps/media/my">My Media</MediaLink></header><p className={styles.muted}>公開プロフィールの見本です。外部には公開されません。</p>{state.profile.destination==="none"?<p className={styles.empty}>プロフィールは公開されていません。</p>:<><div className={styles.intro}><ReaderAvatar avatar={state.profile.avatar} icon={state.profile.icon}/><strong>{state.profile.name}</strong></div><p className={styles.bio}>{state.profile.bio}</p>{site&&articles.length?<MediaLink className={styles.profileLink} href="/apps/media/reader">{site.name}を読む →</MediaLink>:null}</>}</main>;
 const listed=articles.filter(a=>reactions[a.id]?.[tab==="favorite"?"favorite":"saved"]&&a.publishedSnapshot!.title.toLocaleLowerCase().includes(query.toLocaleLowerCase()));
 return <main className={styles.page}><header className={styles.header}><h1>My Media</h1><MediaLink href="/apps/media/reader">Mediaを読む</MediaLink><MediaLink href="/apps/media">発信者のホーム</MediaLink></header><p className={styles.muted}>このブラウザ内の見本です。端末間の同期・実際の読者との共有は未接続です。</p><div className={styles.intro}><ReaderAvatar avatar={state.profile.avatar} icon={state.profile.icon}/><div><strong>{state.profile.name}</strong><p>好きな記事と、大切にしたいつながりを。</p></div></div><div className={styles.tabs} role="tablist" aria-label="My Media">{tabs.map(t=><button key={t.id} role="tab" aria-selected={tab===t.id} onClick={()=>{setTab(t.id);setMessage("");if(t.id==="profile")setForm(state.profile);}}>{t.label}{t.id==="notices"&&notices.some(n=>!n.read)?` ${notices.filter(n=>!n.read).length}`:""}</button>)}</div>
 {(tab==="saved"||tab==="favorite")?<><input className={styles.search} aria-label={tab==="favorite"?"お気に入りを検索":"保存した記事を検索"} placeholder="タイトルで探す" value={query} onChange={e=>setQuery(e.target.value)}/>{listed.length?listed.map(a=><div key={a.id} className={styles.card}><MediaLink href={`/apps/media/reader?published=1&article=${a.id}`}>{a.publishedSnapshot!.coverImageUrl?<img className={styles.thumb} src={a.publishedSnapshot!.coverImageUrl} alt=""/>:null}<div><strong>{a.publishedSnapshot!.title}</strong><small>{site?.authorName} · {new Date(a.publishedSnapshot!.publishedAt).toLocaleDateString("ja-JP")}</small></div></MediaLink><button onClick={()=>{try{updateReaction(scope,a.id,tab==="favorite"?"favorite":"saved");setMessage("一覧から外しました。");}catch{setMessage("変更を保存できませんでした。");}}}>外す</button></div>):<p className={styles.empty}>{query?"条件に合う記事がありません。":tab==="favorite"?"お気に入りの記事がここに集まります。":"読み返したい記事で「あとで読む」を押すと、ここに残せます。"}</p>}</>:null}
 {tab==="following"?<>{site&&state.following.includes(site.id)?<><div className={styles.card}><MediaLink href="/apps/media/reader"><div><strong>{site.authorName}</strong><small>{site.name}</small></div></MediaLink><button onClick={()=>{try{setState(toggleFollow(account,site.id));}catch{setMessage("フォローを変更できませんでした。");}}}>フォロー解除</button></div><h2 className="mt-5 font-bold">フォロー中の新着記事</h2>{[...articles].sort((a,b)=>b.publishedSnapshot!.publishedAt.localeCompare(a.publishedSnapshot!.publishedAt)).slice(0,12).map(a=><div className={styles.card} key={a.id}><MediaLink href={`/apps/media/reader?published=1&article=${a.id}`}><strong>{a.publishedSnapshot!.title}</strong></MediaLink></div>)}</>:<p className={styles.empty}>また読みたい発信者をフォローすると、ここから新着記事を読めます。</p>}</>:null}
 {tab==="notices"?<><label><input type="checkbox" checked={state.notifyReplies} onChange={e=>update({...readMyMedia(account),notifyReplies:e.target.checked},"返信通知の設定を保存しました。")}/> 自分への返信を通知する</label><p className={styles.muted}>記事ごとの設定は不要です。承認された返信をここで確認できます。</p>{notices.length?notices.map(n=>{const c=board.comments.find(c=>c.id===n.commentId)!;return <div className={styles.notice} key={n.id}><strong>{n.read?"既読":"未読"} · {c.author.name}さんから返信</strong><MediaLink href={`/apps/media/reader?published=1&article=${c.articleId}#media-comments`}>返信を見る →</MediaLink></div>;}):<p className={styles.empty}>新しい返信が届くと、ここに表示されます。</p>}{notices.some(n=>!n.read)?<button className={styles.button} onClick={()=>{try{const current=JSON.parse(localStorage.getItem(commentBoardKey(scope))??"null") as CommentBoard|null;if(!current)return;current.notices.filter(n=>n.recipient==="demo-reader").forEach(n=>n.read=true);localStorage.setItem(commentBoardKey(scope),JSON.stringify(current));setBoard(current);setMessage("確認済みにしました。");}catch{setMessage("通知を更新できませんでした。");}}}>すべて確認済みにする</button>:null}</>:null}
 {tab==="profile"?<form className={styles.form} onSubmit={e=>{e.preventDefault();update({...readMyMedia(account),profile:form},"プロフィールを保存しました。コメントにも反映されます。");}}><label>アイコン</label><ReaderAvatar avatar={form.avatar} icon={form.icon}/><div className={styles.icons}>{["🌱","🌼","☕","📚","🐈","🎨"].map(icon=><button type="button" key={icon} aria-label={`${icon}のアイコン`} aria-pressed={!form.avatar&&form.icon===icon} onClick={()=>setForm({...form,icon,avatar:""})}>{icon}</button>)}</div><input type="file" ref={file} hidden accept="image/png,image/jpeg,image/webp" onChange={e=>{void image(e.target.files?.[0]);e.target.value="";}}/><button type="button" className={styles.button} disabled={busy} onClick={()=>file.current?.click()}>{busy?"画像を読み込み中…":"自分の画像を選ぶ"}</button><label htmlFor="reader-name">コメントに表示する名前</label><input id="reader-name" required maxLength={40} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><label htmlFor="reader-bio">ひとこと（任意）</label><textarea id="reader-bio" maxLength={200} value={form.bio} onChange={e=>setForm({...form,bio:e.target.value})}/><label htmlFor="reader-destination">コメントのアイコンから開くページ</label><select id="reader-destination" value={form.destination} onChange={e=>setForm({...form,destination:e.target.value as typeof form.destination})}><option value="none">リンクを表示しない</option><option value="profile">自分のプロフィール</option>{site&&articles.length?<option value="media">自分のMedia</option>:null}</select><p className={styles.muted}>プロフィールの名前・アイコン・ひとことだけを表示します。保存やお気に入りの一覧は見せません。現在は非公開の見本です。</p><button className={styles.save} disabled={busy}>プロフィールを保存</button>{state.profile.destination!=="none"?<MediaLink className={styles.profileLink} href="/apps/media/my/profile">プロフィールの見本を見る →</MediaLink>:null}</form>:null}
 {message?<p className={styles.muted} role="status">{message}</p>:null}</main>;
}
