import Link from "next/link";
import { MediaArticleRenderer } from "./MediaArticleRenderer";
import { MediaPublicFooter } from "./MediaPublicFooter";
import type { MediaPublicArticleDTO, MediaPublicSiteDTO } from "@/lib/media-app/public-contract";

export function PublicMediaArticle({site,article}:{site:MediaPublicSiteDTO;article:MediaPublicArticleDTO}) {
 const path=`/media/${site.slug}/${article.slug}`;
 return <main className="min-h-screen bg-white text-[var(--mikke-text)]"><header className="border-b border-[var(--mikke-line)] px-5 py-7"><div className="mx-auto flex max-w-5xl flex-wrap items-center justify-between gap-4"><Link href={`/media/${site.slug}`} className="text-xl font-bold tracking-wide">{site.name}</Link><a href="#media-about" className="text-sm text-[var(--mikke-muted)]">このメディアについて</a></div></header><div className="mx-auto max-w-3xl px-5 py-10 sm:py-16"><MediaArticleRenderer article={{...article,category:article.categoryName}}/><div className="mt-9 flex items-center gap-3 border-b border-[var(--mikke-line)] pb-8"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-full bg-[var(--mikke-primary-soft)] font-bold text-[var(--mikke-primary)]" aria-hidden>{site.authorName.slice(0,1)}</span><div><p className="text-xs text-[var(--mikke-muted)]">この記事を書いた人</p><a href="#media-about" className="mt-1 block font-semibold">{site.authorName}</a></div></div><section id="media-about" className="scroll-mt-6 py-9"><h2 className="text-lg font-bold">{site.name}について</h2><p className="mt-3 whitespace-pre-wrap text-sm leading-8 text-[var(--mikke-muted)]">{site.description}</p><p className="mt-4 text-sm">書き手：{site.authorName}</p></section><Link href={`/media/${site.slug}`} className="text-sm underline">記事一覧へ戻る</Link></div><MediaPublicFooter name={site.name} articlePath={path}/></main>;
}
