"use client";
import Link from "next/link";
import {useState} from "react";
import type {PublicMediaPageData,PublicMediaPageFilters} from "@/lib/media-app/public-page";
import type {MediaPublicSiteDTO} from "@/lib/media-app/public-contract";
import {MediaPublicFooter} from "./MediaPublicFooter";
import {MediaCloudFollow} from "./MediaCloudSocial";
import styles from "./MediaReaderLibrary.module.css";
export function PublicMediaHome({site,data,filters}:{site:MediaPublicSiteDTO;data:PublicMediaPageData;filters:PublicMediaPageFilters}){
 const [expanded,setExpanded]=useState(false);
 const p=site.presentation, current=filters.page, pages=Math.max(1,Math.ceil(data.total/12));
 const pageUrl=(page:number)=>{const params=new URLSearchParams({page:String(page),q:filters.query,category:filters.category,month:filters.month,collection:filters.collection});return `/media/${site.slug}?${params}`;};
 return <PublicFrame title={site.name}><div className={styles.root}>{p?.bannerImageUrl?<div className={styles.banner}><img src={p.bannerImageUrl} alt="" className={styles.bannerImage} style={{objectPosition:`center ${p.bannerPosition}%`}}/></div>:null}<div className={styles.layout}><aside className={styles.about}><div className={styles.identity}>{p?.logoImageUrl?<img className={styles.logo} src={p.logoImageUrl} alt=""/>:<span className={styles.avatar}>{site.name.slice(0,1)}</span>}<h1>{site.name}</h1></div>{site.description?<div className={styles.intro}><p className={expanded?styles.fullIntro:styles.shortIntro}>{site.description}</p>{site.description.length>70?<button onClick={()=>setExpanded(!expanded)}>{expanded?"閉じる":"もっと見る"}</button>:null}</div>:null}<MediaCloudFollow siteSlug={site.slug}/>{p?.authorBio?<details className={styles.bio}><summary>発信者について</summary><p>{p.authorBio}</p>{p.storyUrl?<a href={p.storyUrl}>STORYを見る ↗</a>:null}</details>:null}</aside><section className={styles.articles} aria-label="記事一覧"><div className={styles.navigation}><h2>記事</h2><span>{data.total}件</span><details className={styles.filters}><summary>検索・絞り込み</summary><form action={`/media/${site.slug}`} method="get" className={styles.filterFields}><label>検索<input name="q" defaultValue={filters.query} placeholder="記事を検索" maxLength={200}/></label><label>カテゴリー<select name="category" defaultValue={filters.category}><option value="">すべて</option>{site.categories.map(c=><option key={c}>{c}</option>)}</select></label><label>月別<input type="month" name="month" defaultValue={filters.month}/></label>{p?.collections.length?<label>特集<select name="collection" defaultValue={filters.collection}><option value="">すべて</option>{p.collections.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>:null}<button type="submit">この条件で表示</button><Link href={`/media/${site.slug}`}>解除</Link></form></details></div><div className={styles.grid}>{data.items.map(({article:a,categories,pinned,displayDate})=><Link className={styles.card} href={`/media/${site.slug}/${a.slug}`} key={a.slug}><div className={styles.thumbnail}>{a.coverImageUrl?<img src={a.coverImageUrl} alt=""/>:<span>{site.name}</span>}</div><div className={styles.cardText}>{pinned?<span className="text-xs font-semibold">上部固定</span>:null}<h3>{a.title}</h3><p className={styles.metadata}>{categories.join("・")} · <time>{new Date(displayDate).toLocaleDateString("ja-JP")}</time></p></div></Link>)}</div>{!data.total?<p className="py-8 text-sm">条件に合う記事はありません。</p>:null}<nav aria-label="記事一覧のページ" className="flex justify-center items-center gap-5 py-6">{current>1?<Link href={pageUrl(current-1)}>前へ</Link>:<span className="opacity-40">前へ</span>}<span>{current} / {pages}</span>{current<pages?<Link href={pageUrl(current+1)}>次へ</Link>:<span className="opacity-40">次へ</span>}</nav></section></div></div><MediaPublicFooter name={site.name}/></PublicFrame>;
}
export function PublicFrame({title,children}:{title:string;children:React.ReactNode}){return <main className="min-h-screen bg-white text-[var(--mikke-text)]"><header className="border-b border-[var(--mikke-line)]"><div className="mx-auto flex max-w-6xl items-center justify-between px-4 py-3"><span className="font-semibold">{title}</span><Link href="/apps/media/my" className="text-xs font-semibold">My Media</Link></div></header>{children}</main>;}
