"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { ArrowRight, BookOpen } from "lucide-react";
import type { MediaPublicArticleSummaryDTO, MediaPublicSiteDTO } from "@/lib/media-app/public-contract";

export function PublicMediaHome({ site, articles }: { site: MediaPublicSiteDTO; articles: MediaPublicArticleSummaryDTO[] }) {
  const [category, setCategory] = useState("すべて");
  const categories = useMemo(() => ["すべて", ...new Set(articles.map((item) => item.categoryName).filter(Boolean))], [articles]);
  const visible = category === "すべて" ? articles : articles.filter((item) => item.categoryName === category);
  return <PublicFrame title={site.name}><section className="max-w-3xl py-8 sm:py-14"><p className="text-xs font-black tracking-[0.16em] text-[var(--mikke-primary)]">MEDIA</p><h1 className="mt-4 break-words text-4xl font-black leading-tight sm:text-6xl">{site.name}</h1>{site.description ? <p className="mt-5 text-base leading-8 text-[var(--mikke-muted)]">{site.description}</p> : null}<p className="mt-4 text-xs font-bold text-[var(--mikke-muted)]">編集：{site.authorName}</p></section>{categories.length > 1 ? <nav className="flex flex-wrap gap-2 pb-7" aria-label="カテゴリー">{categories.map((item) => <button key={item} type="button" onClick={() => setCategory(item)} className={`rounded-full px-4 py-2 text-xs font-bold ${category === item ? "bg-[var(--mikke-primary)] text-white" : "border border-[var(--mikke-line)] bg-white text-[var(--mikke-muted)]"}`}>{item}</button>)}</nav> : null}{visible.length === 0 ? <div className="grid min-h-64 place-items-center rounded-3xl border border-dashed border-[var(--mikke-line)] bg-white text-center"><div><BookOpen className="mx-auto text-[var(--mikke-primary)]" /><p className="mt-4 font-bold">公開中の記事はまだありません</p></div></div> : <div className="grid gap-5 pb-12 md:grid-cols-2 lg:grid-cols-3">{visible.map((article) => <Link key={`${article.locale}:${article.slug}`} href={`/media/${site.slug}/${article.slug}`} className="group overflow-hidden rounded-3xl border border-[var(--mikke-line)] bg-white shadow-sm transition hover:-translate-y-1 hover:shadow-lg">{article.coverImageUrl ? <img src={article.coverImageUrl} alt="" className="aspect-[16/10] w-full object-cover" /> : <div className="grid aspect-[16/10] place-items-center bg-[var(--mikke-primary-soft)] text-xs font-black tracking-[0.14em] text-[var(--mikke-primary)]">{site.name}</div>}<div className="p-5"><div className="flex items-center gap-2 text-[11px] font-bold text-[var(--mikke-muted)]">{article.categoryName ? <span className="rounded-full bg-[var(--mikke-primary-soft)] px-2 py-1 text-[var(--mikke-primary)]">{article.categoryName}</span> : null}<time>{new Date(article.updatedAt).toLocaleDateString(article.locale)}</time></div><h2 className="mt-4 break-words text-xl font-black leading-snug">{article.title}</h2>{article.excerpt ? <p className="mt-3 line-clamp-3 text-sm leading-6 text-[var(--mikke-muted)]">{article.excerpt}</p> : null}<span className="mt-5 inline-flex items-center gap-1 text-xs font-black text-[var(--mikke-primary)]">続きを読む<ArrowRight size={14} /></span></div></Link>)}</div>}<p className="pb-8 text-center text-[11px] text-[var(--mikke-muted)]">Media Free ローカルpilot表示</p></PublicFrame>;
}

export function PublicFrame({ title, children }: { title: string; children: React.ReactNode }) { return <main className="min-h-screen overflow-x-hidden bg-[#f7f5ef] text-[var(--mikke-text)]"><header className="border-b border-[var(--mikke-line)] bg-white"><div className="mx-auto flex max-w-6xl items-center justify-between gap-4 px-4 py-4 sm:px-5"><span className="min-w-0 break-words font-black text-[var(--mikke-primary)]">{title}</span><Link href="/home" className="shrink-0 text-xs font-black tracking-[0.14em] text-[var(--mikke-muted)]">mikkeOS</Link></div></header><div className="mx-auto max-w-6xl px-4 sm:px-5">{children}</div></main>; }
