-- Invoked inside BEGIN with the disposable fixture and unmodified migration.
set local role authenticated;
select set_config('request.jwt.claim.sub',test.uid(1)::text,true);
insert into public.academy_offerings(id,headquarters_id,title,course_ids,price,status)
values(test.uid(301),test.uid(100),'Bundle',array[test.uid(101),test.uid(102)],2400,'published');
select test.denied($q$insert into public.academy_offerings(headquarters_id,title,course_ids,price) values(test.uid(100),'Bad',array[test.uid(201)],100)$q$);
select test.denied($q$update public.academy_offerings set headquarters_id=test.uid(200) where id=test.uid(301)$q$);
select set_config('request.jwt.claim.sub',test.uid(2)::text,true);
select test.ok((select count(*)=0 from public.academy_offerings),'cross HQ cannot select');
select test.denied($q$insert into public.academy_offerings(headquarters_id,title,course_ids,price) values(test.uid(100),'Bad',array[test.uid(101)],100)$q$);
reset role;
set local role anon;
select test.ok(public.academy_get_public_offering(test.uid(301))->>'title'='Bundle','anon public projection');
select test.ok(not (public.academy_get_public_offering(test.uid(301)) ? 'created_by'),'public creator excluded');
select test.ok(not ((public.academy_get_public_offering(test.uid(301))->'courses'->0) ? 'learner_access_mode'),'access config excluded');
select test.denied('select * from public.academy_offerings');
select test.denied('select * from public.academy_offering_applications');
select test.denied($q$select public.academy_submit_offering_application(test.uid(301),test.uid(401),'Learner','l@example.invalid','bank',2400)$q$);
reset role;
set local role authenticated;
select set_config('request.jwt.claim.sub',test.uid(3)::text,true);
select test.denied($q$select public.academy_submit_offering_application(test.uid(301),test.uid(401),'Learner','l@example.invalid','bank',1)$q$);
select test.denied($q$select public.academy_submit_offering_application(test.uid(301),test.uid(401),'Learner','l@example.invalid','stripe',2400)$q$);
select public.academy_submit_offering_application(test.uid(301),test.uid(401),'Learner','l@example.invalid','bank',2400);
select public.academy_submit_offering_application(test.uid(301),test.uid(401),'Learner','l@example.invalid','bank',2400);
select public.academy_submit_offering_application(test.uid(301),test.uid(402),'Learner','l@example.invalid','bank',2400);
select test.ok((select count(*)=1 from public.academy_offering_applications),'retry and new-token duplicate');
select test.ok((select price=2400 and cardinality(course_ids)=2 from public.academy_offering_applications),'server price and bundle');
select test.ok(exists(select 1 from public.academy_list_my_contexts() where academy_id=test.uid(100) and 'learner'=any(roles)),'pending context visible');
select test.denied($q$update public.academy_offering_applications set status='paid'$q$);
select test.denied($q$select public.academy_confirm_offering_payment((select id from public.academy_offering_applications limit 1))$q$);
select set_config('request.jwt.claim.sub',test.uid(4)::text,true);
select test.ok((select count(*)=0 from public.academy_offering_applications),'other learner cannot read');
select set_config('request.jwt.claims','{"is_anonymous":true}',true);
select test.denied($q$select public.academy_submit_offering_application(test.uid(301),test.uid(403),'Anon','a@example.invalid','bank',2400)$q$);
select set_config('request.jwt.claims','{}',true);
select set_config('request.jwt.claim.sub',test.uid(1)::text,true);
update public.academy_offerings set price=9900,title='Changed' where id=test.uid(301);
select test.ok((select price=2400 and offering_title='Bundle' from public.academy_offering_applications),'snapshot preserved after edit');
select public.academy_confirm_offering_payment((select id from public.academy_offering_applications limit 1));
select public.academy_confirm_offering_payment((select id from public.academy_offering_applications limit 1));
select test.ok((select count(*)=2 from public.academy_offering_application_grants),'grant bridge idempotent');
reset role;
select test.ok((select count(*)=2 from public.academy_course_access_grants),'two grants exactly');
select test.ok((select g.ends_at=a.created_at+interval '30 days' from public.academy_course_access_grants g cross join public.academy_offering_applications a where g.course_id=test.uid(102)),'enrollment duration starts at application');
select test.denied($q$update public.academy_offering_applications set price=1$q$);
set local role authenticated;
select set_config('request.jwt.claim.sub',test.uid(3)::text,true);
select test.ok((select count(*)=2 from public.academy_courses),'paid learner course metadata');
select test.ok((select count(*)=2 from public.academy_offering_application_grants),'own grant bridge readable');
reset role;
-- Expired fixed window and malformed duration fail closed before a new application.
update public.academy_courses set learner_access_mode='fixed_end',learner_access_fixed_end_at=now()-interval '1 day' where id=test.uid(101);
set local role authenticated;
select set_config('request.jwt.claim.sub',test.uid(4)::text,true);
select test.denied($q$select public.academy_submit_offering_application(test.uid(301),test.uid(404),'Learner','l@example.invalid','bank',9900)$q$);
reset role;
update public.academy_courses set learner_access_mode='days_after_payment',learner_access_days=null where id=test.uid(101);
set local role authenticated;
select set_config('request.jwt.claim.sub',test.uid(4)::text,true);
select test.denied($q$select public.academy_submit_offering_application(test.uid(301),test.uid(405),'Learner','l@example.invalid','bank',9900)$q$);
reset role;
-- Transaction rollback is performed by the runner, including all fixture/migration DDL.
