-- Runs after all-at-once tests in the same disposable transaction.
reset role;
update public.academy_courses set learner_access_mode='unlimited',learner_access_days=null where id=test.uid(101);
set local role authenticated;
select set_config('request.jwt.claim.sub',test.uid(1)::text,true);
insert into public.academy_offerings(id,headquarters_id,title,course_ids,price,status,purchase_mode,stage_prices)
values(test.uid(501),test.uid(100),'Sequential',array[test.uid(101),test.uid(102)],2700,'published','staged',jsonb_build_object(test.uid(101)::text,1200,test.uid(102)::text,1500));
select test.denied($q$insert into public.academy_offerings(headquarters_id,title,course_ids,status,purchase_mode,stage_prices) values(test.uid(100),'Bad',array[test.uid(101),test.uid(102)],'published','staged','{}')$q$);
select test.denied($q$update public.academy_offerings set stage_prices=jsonb_build_object(test.uid(101)::text,0,test.uid(102)::text,-1) where id=test.uid(501)$q$);
select set_config('request.jwt.claim.sub',test.uid(3)::text,true);
select test.denied($q$select public.academy_submit_offering_application(test.uid(501),test.uid(601),'Learner','l@example.invalid','bank',1500)$q$);
select public.academy_submit_offering_application(test.uid(501),test.uid(601),'Learner','l@example.invalid','bank',1200);
select public.academy_submit_offering_application(test.uid(501),test.uid(602),'Learner','l@example.invalid','bank',1200);
select test.ok((select count(*)=1 from public.academy_offering_applications where offering_id=test.uid(501)),'pending new token no duplicate stage');
select test.ok((select stage_index=1 and course_ids=array[test.uid(101)] and price=1200 from public.academy_offering_applications where offering_id=test.uid(501)),'stage 1 only price and course');
select test.denied($q$select public.academy_complete_offering_course((select id from public.academy_offering_applications where offering_id=test.uid(501)))$q$);
select set_config('request.jwt.claim.sub',test.uid(1)::text,true);
update public.academy_offerings set stage_prices=jsonb_build_object(test.uid(101)::text,9000,test.uid(102)::text,9999),completion_mode='hq' where id=test.uid(501);
select public.academy_confirm_offering_payment((select id from public.academy_offering_applications where offering_id=test.uid(501)));
select test.ok((select count(*)=1 from public.academy_offering_application_grants g join public.academy_offering_applications a on a.id=g.application_id where a.offering_id=test.uid(501)),'only first course granted');
select set_config('request.jwt.claim.sub',test.uid(3)::text,true);
select test.denied($q$select public.academy_submit_offering_application(test.uid(501),test.uid(603),'Learner','l@example.invalid','bank',1500)$q$);
select public.academy_complete_offering_course((select id from public.academy_offering_applications where offering_id=test.uid(501)));
select public.academy_complete_offering_course((select id from public.academy_offering_applications where offering_id=test.uid(501)));
select test.denied($q$select public.academy_submit_offering_application(test.uid(501),test.uid(603),'Learner','l@example.invalid','bank',9999)$q$);
select public.academy_submit_offering_application(test.uid(501),test.uid(603),'Learner','l@example.invalid','bank',1500);
select test.ok((select count(*)=2 from public.academy_offering_applications where offering_id=test.uid(501)),'second stage after completion');
select test.ok((select price=1500 and course_ids=array[test.uid(102)] from public.academy_offering_applications where offering_id=test.uid(501) and stage_index=2),'future price fixed');
select public.academy_submit_offering_application(test.uid(501),test.uid(601),'Learner','l@example.invalid','bank',1200);
select test.ok((select count(*)=2 from public.academy_offering_applications where offering_id=test.uid(501)),'old token no advancement');
select set_config('request.jwt.claim.sub',test.uid(1)::text,true);
select public.academy_confirm_offering_payment((select id from public.academy_offering_applications where offering_id=test.uid(501) and stage_index=2));
select public.academy_complete_offering_course((select id from public.academy_offering_applications where offering_id=test.uid(501) and stage_index=2));
select set_config('request.jwt.claim.sub',test.uid(3)::text,true);
select test.denied($q$select public.academy_submit_offering_application(test.uid(501),test.uid(604),'Learner','l@example.invalid','bank',1500)$q$);
select test.ok((select count(*)=2 from public.academy_offering_application_grants g join public.academy_offering_applications a on a.id=g.application_id where a.offering_id=test.uid(501)),'two stage grants exactly');
select set_config('request.jwt.claim.sub',test.uid(4)::text,true);
select public.academy_submit_offering_application(test.uid(501),test.uid(605),'Other','o@example.invalid','bank',9000);
select set_config('request.jwt.claim.sub',test.uid(1)::text,true);
select public.academy_confirm_offering_payment((select id from public.academy_offering_applications where learner_user_id=test.uid(4) and offering_id=test.uid(501)));
select set_config('request.jwt.claim.sub',test.uid(4)::text,true);
select test.denied($q$select public.academy_complete_offering_course((select id from public.academy_offering_applications where offering_id=test.uid(501)))$q$);
select set_config('request.jwt.claim.sub',test.uid(1)::text,true);
select public.academy_complete_offering_course((select id from public.academy_offering_applications where learner_user_id=test.uid(4) and offering_id=test.uid(501)));
reset role;
