-- Invoked within BEGIN; runner always ROLLBACKs all fixture/schema/data changes.
set local role authenticated;
select set_config('request.jwt.claim.sub',test.uid(1)::text,true);
insert into public.academy_offerings(id,headquarters_id,title,course_ids,price,status) values(test.uid(301),test.uid(100),'HQ original',array[test.uid(101),test.uid(102)],2400,'published');
select set_config('request.jwt.claim.sub',test.uid(5)::text,true);
select test.ok((select count(*)=0 from public.academy_list_eligible_instructor_offerings()),'other HQ qualification is not eligible');
select test.denied($q$select public.academy_save_instructor_offering_page(null,test.uid(301),'{"display_name":"Wrong"}','[]','published')$q$);
select set_config('request.jwt.claim.sub',test.uid(4)::text,true);
select test.ok((select count(*)=1 from public.academy_list_eligible_instructor_offerings()),'all-course qualified instructor eligible');
select set_config('test.page',public.academy_save_instructor_offering_page(null,test.uid(301),'{"display_name":"Teacher Four","bio":"Intro"}','[]','published')->>'id',true);
select test.denied($q$update public.academy_instructor_offering_pages set owner_user_id=test.uid(5)$q$);
update public.academy_offerings set title='Instructor override' where id=test.uid(301);
select test.ok(public.academy_get_public_offering(test.uid(301))->>'title'='HQ original','instructor cannot change HQ source');
reset role;
-- A missing/expired certification for just one course fails the entire bundle.
update public.academy_instructors set renewal_due=current_date-1 where user_id=test.uid(4) and course_id=test.uid(102);
set local role authenticated;
select test.ok((select count(*)=0 from public.academy_list_eligible_instructor_offerings()),'one expired course fails bundle');
select test.denied($q$select public.academy_save_instructor_offering_page(current_setting('test.page')::uuid,test.uid(301),'{"display_name":"Changed"}','[]','published')$q$);
reset role;
set local role anon;
select test.ok(public.academy_get_public_instructor_offering(current_setting('test.page')::uuid) is null,'expired public page hidden');
select test.denied('select * from public.academy_instructor_offering_pages');
reset role;
update public.academy_instructors set renewal_due=current_date+30 where user_id=test.uid(4);
set local role authenticated;
select set_config('request.jwt.claim.sub',test.uid(2)::text,true);
select test.ok((select count(*)=0 from public.academy_instructor_offering_pages),'other HQ cannot read pages');
select test.denied($q$select public.academy_save_instructor_offering_page(current_setting('test.page')::uuid,test.uid(301),'{"display_name":"Steal"}','[]','archived')$q$);
select set_config('request.jwt.claim.sub',test.uid(1)::text,true);
select test.ok((select count(*)=1 from public.academy_instructor_offering_pages),'HQ sees usage');
reset role;
select test.denied($q$delete from public.academy_offerings where id=test.uid(301)$q$);
set local role anon;
select test.ok(public.academy_get_public_instructor_offering(current_setting('test.page')::uuid)->'offering'->>'title'='HQ original','original HQ content projected');
select test.ok(not(public.academy_get_public_instructor_offering(current_setting('test.page')::uuid)->'page' ? 'owner_user_id'),'private user ID not public');
reset role;
set local role authenticated;
select set_config('request.jwt.claim.sub',test.uid(3)::text,true);
select set_config('test.application',public.academy_submit_instructor_offering_application(current_setting('test.page')::uuid,test.uid(401),'Learner','learner@example.invalid','bank',2400)->>'id',true);
select public.academy_submit_instructor_offering_application(current_setting('test.page')::uuid,test.uid(401),'Learner','learner@example.invalid','bank',2400);
select test.ok((select count(*)=1 from public.academy_instructor_offering_application_links),'retry creates one immutable attribution');
select test.denied($q$update public.academy_instructor_offering_application_links set owner_user_id=test.uid(5)$q$);
select set_config('request.jwt.claim.sub',test.uid(6)::text,true);
select test.ok((select count(*)=0 from public.academy_instructor_offering_application_links),'unrelated learner cannot read attribution');
select test.ok((select count(*)=0 from public.academy_offering_applications),'unrelated learner cannot read application');
select set_config('request.jwt.claim.sub',test.uid(4)::text,true);
select test.ok((select count(*)=1 from public.academy_offering_applications),'assigned instructor can read application');
select test.denied($q$select public.academy_confirm_offering_payment(current_setting('test.application')::uuid)$q$);
select public.academy_save_instructor_offering_page(current_setting('test.page')::uuid,test.uid(301),'{"display_name":"New Name"}','[]','published');
select test.ok((select instructor_snapshot->'profile'->>'display_name'='Teacher Four' from public.academy_instructor_offering_application_links),'profile edits do not alter application snapshot');
select set_config('request.jwt.claim.sub',test.uid(7)::text,true);
select public.academy_submit_offering_application(test.uid(301),test.uid(407),'Direct','direct@example.invalid','bank',2400);
select test.denied($q$select public.academy_submit_instructor_offering_application(current_setting('test.page')::uuid,test.uid(407),'Direct','direct@example.invalid','bank',2400)$q$);
reset role;
insert into public.academy_instructors(headquarters_id,user_id,registration_status,is_certified,is_active,status,course_id) values(test.uid(100),test.uid(5),'registered',true,true,'active',test.uid(101)),(test.uid(100),test.uid(5),'registered',true,true,'active',test.uid(102));
set local role authenticated;
select set_config('request.jwt.claim.sub',test.uid(5)::text,true);
select set_config('test.otherpage',public.academy_save_instructor_offering_page(null,test.uid(301),'{"display_name":"Teacher Five"}','[]','published')->>'id',true);
select set_config('request.jwt.claim.sub',test.uid(3)::text,true);
select test.denied($q$select public.academy_submit_instructor_offering_application(current_setting('test.otherpage')::uuid,test.uid(401),'Learner','learner@example.invalid','bank',2400)$q$);
reset role;
update public.academy_instructors set registration_status='withdrawn' where user_id=test.uid(4);
set local role authenticated;
select set_config('request.jwt.claim.sub',test.uid(4)::text,true);
select public.academy_save_instructor_offering_page(current_setting('test.page')::uuid,test.uid(301),'{}','[]','archived');
select test.ok((select count(*)=1 from public.academy_instructor_offering_application_links),'withdrawal/archive preserves history');
reset role;
select test.denied($q$delete from public.academy_instructor_offering_pages where id=current_setting('test.page')::uuid$q$);
select test.denied($q$update public.academy_instructor_offering_application_links set instructor_snapshot='{}'$q$);
-- Staged purchases must continue through their original instructor, not the HQ URL.
set local role authenticated;
select set_config('request.jwt.claim.sub',test.uid(1)::text,true);
insert into public.academy_offerings(id,headquarters_id,title,course_ids,price,status,purchase_mode,stage_prices) values(test.uid(302),test.uid(100),'Stages',array[test.uid(101),test.uid(102)],2400,'published','staged',jsonb_build_object(test.uid(101)::text,1200,test.uid(102)::text,1500));
select set_config('request.jwt.claim.sub',test.uid(5)::text,true);
select set_config('test.stagepage',public.academy_save_instructor_offering_page(null,test.uid(302),'{"display_name":"Stage Teacher"}','[]','published')->>'id',true);
select set_config('request.jwt.claim.sub',test.uid(6)::text,true);
select set_config('test.stageapp',public.academy_submit_instructor_offering_application(current_setting('test.stagepage')::uuid,test.uid(406),'Staged Learner','stage@example.invalid','bank',1200)->>'id',true);
select set_config('request.jwt.claim.sub',test.uid(1)::text,true);
select public.academy_confirm_offering_payment(current_setting('test.stageapp')::uuid);
select set_config('request.jwt.claim.sub',test.uid(6)::text,true);
select public.academy_complete_offering_course(current_setting('test.stageapp')::uuid);
select test.denied($q$insert into private.academy_instructor_application_context values(txid_current(),test.uid(6),test.uid(302),current_setting('test.stagepage')::uuid)$q$);
select test.denied($q$select public.academy_submit_offering_application(test.uid(302),test.uid(416),'Staged Learner','stage@example.invalid','bank',1500)$q$);
select public.academy_submit_instructor_offering_application(current_setting('test.stagepage')::uuid,test.uid(416),'Staged Learner','stage@example.invalid','bank',1500);
select test.ok((select count(*)=2 from public.academy_instructor_offering_application_links where learner_user_id=test.uid(6)),'both stages retain instructor');
reset role;
select test.ok((select count(*)=0 from private.academy_instructor_application_context),'no handoff rows retained');
