'use client';
import {useEffect,useRef,useState} from 'react';
import {useSearchParams} from 'next/navigation';
import type {SalesPlanDraftConfiguration as Config} from '@/lib/academy2/sales-plan-drafts';
import {getAfterCourseCapabilities,type AfterCourseCapabilities} from '@/lib/academy2/after-course-capabilities';
import type {PlanExpiry,PlanRenewal} from '@/lib/academy2/sales-plan.mjs';
import {PlanConditionPicker} from './PlanConditionPicker';
import {PlanCommunitySettings} from './PlanCommunitySettings';
import {InstructorManualEditor} from './InstructorManualEditor';
import styles from './SalesPlanDraftEditor.module.css';
import {useLocalReviewVersion} from '@/lib/academy2/local-review';
type After=NonNullable<Config['after']>;
const empty:After={skill_certification:false,commercial_license:false,instructor_license:false};
const yen=(v:number|null|undefined)=>v==null?'金額未設定':`${v.toLocaleString('ja-JP')}円`;
export function suggestedQualification(title:string){const name=title.trim().replace(/(?:講座|コース)$/,'').trim();return name.endsWith('認定')?name:`${name||'講座'}認定`;}
function Cards<T extends string>({label,value,choices,onChange,disabled=false}:{label:string;value:T;choices:readonly (readonly [T,string])[];onChange:(v:T)=>void;disabled?:boolean}){return <div role="group" aria-label={label} className={styles.wizardCards}>{choices.map(([id,text])=><button key={id} type="button" aria-pressed={id===value} disabled={disabled} onClick={()=>onChange(id)}>{text}</button>)}</div>;}
function ExpiryQuestion({value,onChange,instructor=false}:{value:PlanExpiry;onChange:(v:PlanExpiry)=>void;instructor?:boolean}){return <><Cards label="期限の設定" value={value.kind==='months'||value.kind==='years'?'period':value.kind} choices={instructor?[['none','期限なし'],['period','期間を指定']]:[['none','期限なし'],['period','期間を指定'],['date','指定日まで']]} onChange={kind=>onChange({...value,kind:kind==='period'?'months':kind as PlanExpiry['kind']})}/>{(value.kind==='months'||value.kind==='years')&&<><label>期間<input aria-label="有効期間" type="number" min={1} step={1} value={value.count??''} onChange={e=>onChange({...value,count:e.target.value?Number(e.target.value):null})}/></label><Cards label="期間の単位" value={value.kind} choices={[["months","ヶ月"],["years","年"]]} onChange={kind=>onChange({...value,kind})}/></>}{value.kind==='date'&&<label>有効期限の日付<input type="date" value={value.date??''} onChange={e=>onChange({...value,date:e.target.value})}/></label>}</>;}
function RenewalQuestion({value,onChange,instructor=false}:{value:PlanRenewal;onChange:(v:PlanRenewal)=>void;instructor?:boolean}){const choices=instructor?[['hq_review','本部確認'],['update_training','更新講習'],['minimum_events','最低開催回数'],['other','その他']]:[['retraining','再受講'],['update_training','更新講習'],['hq_review','本部確認'],['other','その他']];return <><Cards label="更新の必要性" value={value.enabled?'yes':'no'} choices={[["no","不要"],["yes","必要"]]} onChange={v=>onChange({...value,enabled:v==='yes'})}/>{value.enabled&&<>{choices.map(([id,text])=><label key={id}><input type="checkbox" checked={value.conditions.includes(id)} onChange={e=>onChange({...value,conditions:e.target.checked?[...value.conditions,id]:value.conditions.filter(x=>x!==id)})}/> {text}</label>)}{value.conditions.includes('minimum_events')&&<label>最低開催回数<input type="number" min={1} value={value.minimum_events??''} onChange={e=>onChange({...value,minimum_events:e.target.value?Number(e.target.value):null})}/></label>}{value.conditions.includes('other')&&<label>その他の更新条件<textarea value={value.other??''} maxLength={4000} onChange={e=>onChange({...value,other:e.target.value})}/></label>}</>}</>;}
export function WizardSummary({configuration:c}:{configuration:Config}){const a=c.after??empty;return <section aria-label="受講後の設定結果" className={styles.wizardSummary}><h3>受講後の設定</h3><p>修了：受講状況を本部が確認して記録</p>{a.certificate&&<p>証書：{{digital:'デジタル',physical:'現物を発送',both:'デジタル＋現物'}[a.certificate.delivery]}</p>}{a.skill_certification&&<><p>認定資格：{a.qualification?.name||'名称未設定'}</p><p>資格期限：{expiryText(a.qualification?.expiry)}</p></>}{a.commercial_license&&<><p>商用利用：許可する</p><p>利用範囲：{a.commercial_policy?.rights.map(x=>(({products:'作品販売',workshops:'ワークショップ開催',lessons:'レッスン開催',services:'サービス提供',other:'その他'} as Record<string,string>)[x]??x)).join('・')||'既存条件文書を確認'}</p></>}{a.instructor_license&&<><p>講師活動：条件を満たした後に可</p>{a.registration_fee?.enabled&&<p>登録料：{yen(a.registration_fee.amount)}</p>}{c.dues?.enabled&&<p>会費：{c.dues.interval==='month'?'月額':'年額'}{yen(c.dues.amount)}</p>}<p>講師ライセンス：{expiryText(a.instructor_policy?.expiry)}</p>{c.opening_license?.enabled&&<p>開講ライセンス：{yen(c.opening_license.amount)} / {{initial:'初回',per_event:'開講',renewal:'更新'}[c.opening_license.timing??'initial']}</p>}{(a.manual?.blocks.length||a.instructor_manual_id)&&<p>講師マニュアル：あり</p>}{c.community&&c.community!=='none'&&<p>Community：{c.community==='required'?'必須':'任意'}</p>}{a.instructor_policy?.rights.includes('sales_page')&&<p>営業ページ：利用可</p>}{a.instructor_policy?.website_listing&&<p>本部HP：掲載可</p>}</>}</section>;}
function expiryText(v?:PlanExpiry){return !v||v.kind==='none'?'なし':v.kind==='date'?v.date||'日付未設定':`${v.count??'未設定'}${v.kind==='years'?'年':'ヶ月'}`;}
export function AfterCourseWizard({headquartersId,configuration:c,patch,onComplete}:{headquartersId:string;configuration:Config;patch:(v:Partial<Config>)=>void;onComplete:()=>void}){
 const a=c.after??empty,set=(v:Partial<After>)=>patch({after:{...a,...v}}),q=a.qualification??{name:'',expiry:{kind:'none' as const},renewal:{enabled:false,conditions:[]}},policy=a.instructor_policy??{rights:[],expiry:{kind:'none' as const},renewal:{enabled:false,conditions:[]},website_listing:false};
 const fee=a.registration_fee??{enabled:false,amount:null,payment_method:'academy_card' as const},dues=c.dues??{enabled:false,interval:'month' as const,amount:null},opening=c.opening_license??{enabled:false,amount:null,kit:'none' as const};
 const query=useSearchParams(),manualOpened=useRef(false);
 const [question,setQuestion]=useState(query.get('afterQuestion')??'certificate'),[caps,setCaps]=useState<AfterCourseCapabilities|null>(null),[error,setError]=useState(''),[retry,setRetry]=useState(0),[manual,setManual]=useState(false),[conditions,setConditions]=useState(!!a.skill_definition_id);
 const reviewVersion=useLocalReviewVersion();
 useEffect(()=>{let live=true;getAfterCourseCapabilities(headquartersId).then(v=>{if(live){setCaps(v);setError('');}}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[headquartersId,retry,reviewVersion]);
 const card=caps?.card_contract==='active'&&caps.card_ready;
 const questions=['certificate','qualification',...(a.skill_certification?['qualification_name','qualification_condition','qualification_expiry','qualification_renewal']:[]),...(a.skill_certification||a.commercial_license?['commercial',...(a.commercial_license?['commercial_scope']:[])]:[]),'teaching',...(a.instructor_license&&card?['contract','registration_fee','dues','rights','license_expiry','license_renewal','opening','manual','community','sales_page','listing']:[]),'summary'];
 const index=Math.max(0,questions.indexOf(question)),active=questions[index];
 useEffect(()=>{if(active==='manual'&&query.get('manual')==='1'&&!manualOpened.current){manualOpened.current=true;setManual(true);}},[active,query.toString()]);
 const titles:Record<string,string>={certificate:'証書を発行しますか？',qualification:'認定資格を付与しますか？',qualification_name:'認定資格名を確認してください',qualification_condition:'認定の条件はありますか？',qualification_expiry:'認定資格に有効期限はありますか？',qualification_renewal:'認定資格の更新は必要ですか？',commercial:'認定取得後、学んだ内容を仕事として利用できますか？',commercial_scope:'商用利用できる範囲を選んでください',teaching:'この講座を教えられるようにしますか？',contract:'講師契約を確認',registration_fee:'講師登録料はありますか？',dues:'講師会費はありますか？',rights:'講師ライセンスに含まれる権利を選んでください',license_expiry:'講師ライセンスに有効期限はありますか？',license_renewal:'講師ライセンスの更新は必要ですか？',opening:'講座を開講する際のライセンス料はありますか？',manual:'講師用マニュアルを用意しますか？',community:'講師にCommunity参加を設定しますか？',sales_page:'講師に営業ページを利用させますか？',listing:'本部HPに講師を掲載できますか？',summary:'受講後の設定を確認してください'};
 const yesNo=(label:string,value:boolean,onChange:(v:boolean)=>void,yes='あり',no='なし')=><Cards label={label} value={value?'yes':'no'} choices={[["no",no],["yes",yes]]} onChange={v=>onChange(v==='yes')}/>;
 const rights=[['teach','この講座を開講できる'],['materials','本部教材を使用できる'],['manual','講師マニュアルを閲覧できる'],['sales_page','営業ページを利用できる'],['website','本部HPへ掲載できる'],['community','Communityを利用できる'],['assignments','本部から担当依頼を受けられる'],['kit','キットを講師価格で購入できる'],['other','その他']];
 return <div className={styles.wizard} aria-label="受講後の質問ウィザード"><p className={styles.help}>質問 {index+1} / {questions.length}　回答は最後のSTEPで保存します。</p><h3 tabIndex={-1}>{titles[active]}</h3>
 {active==='certificate'&&<><Cards label="証書の発行" value={a.certificate?.delivery??'none'} choices={[["none","発行しない"],["digital","デジタル"],["physical","現物を発送"],["both","デジタル＋現物"]]} onChange={v=>{if(v==='none'){const next={...a};delete next.certificate;patch({after:next});}else set({certificate:{kind:a.certificate?.kind??'completion',name_rule:a.certificate?.name_rule??'',delivery:v}});}}/>{a.certificate&&<><Cards label="証書の種類" value={a.certificate.kind} choices={[["completion","修了証"],["certification","認定証・デュプロマ"],["other","その他"]]} onChange={kind=>set({certificate:{...a.certificate!,kind}})}/><label>証書記載名ルール<input value={a.certificate.name_rule} onChange={e=>set({certificate:{...a.certificate!,name_rule:e.target.value}})}/></label><p>証書記載名を申込フォームに追加します。現物を発送する場合は住所も取得します。</p></>}</>}
 {active==='qualification'&&yesNo('認定資格の付与',a.skill_certification,v=>set({skill_certification:v,...(v&&!q.name?{qualification:{...q,name:suggestedQualification(c.title)}}:{})}),'付与する','付与しない')}
 {active==='qualification_name'&&<label>認定資格名<input value={q.name} maxLength={200} onChange={e=>set({qualification:{...q,name:e.target.value}})}/></label>}
 {active==='qualification_condition'&&<>{yesNo('認定の条件',conditions,v=>{setConditions(v);if(!v){const next={...a};delete next.skill_definition_id;patch({after:next});}},'条件を設定する','特にない')}{conditions&&<PlanConditionPicker headquartersId={headquartersId} kind="skill" label="認定条件" value={a.skill_definition_id} onChange={id=>set({skill_definition_id:id})}/>}</>}
 {active==='qualification_expiry'&&<ExpiryQuestion value={q.expiry} onChange={expiry=>set({qualification:{...q,expiry}})}/>}
 {active==='qualification_renewal'&&<RenewalQuestion value={q.renewal} onChange={renewal=>set({qualification:{...q,renewal}})}/>}
 {active==='commercial'&&<><p>作品販売・ワークショップ開催・レッスン開催・サービス提供など、この講座で学んだ内容を仕事として利用できる範囲を設定します。</p>{yesNo('商用利用',a.commercial_license,v=>set({commercial_license:v}),'許可する','許可しない')}</>}
 {active==='commercial_scope'&&<>{[['products','作品販売'],['workshops','ワークショップ開催'],['lessons','レッスン開催'],['services','サービス提供'],['other','その他']].map(([id,text])=><label key={id}><input type="checkbox" checked={a.commercial_policy?.rights.includes(id)??false} onChange={e=>{const p=a.commercial_policy??{rights:[],notes:''};set({commercial_policy:{...p,rights:e.target.checked?[...p.rights,id]:p.rights.filter(x=>x!==id)}});}}/> {text}</label>)}<label>利用条件・注意事項<textarea placeholder="この講座で学んだ技術の範囲に限る。本部指定教材の転載禁止。認定名称の使用条件など。" value={a.commercial_policy?.notes??''} maxLength={4000} onChange={e=>set({commercial_policy:{rights:a.commercial_policy?.rights??[],notes:e.target.value}})}/></label><PlanConditionPicker headquartersId={headquartersId} kind="commercial" label="保存済みの利用条件を確認" value={a.commercial_condition_id} onChange={id=>set({commercial_condition_id:id})}/></>}
 {active==='teaching'&&<>{yesNo('講師活動',a.instructor_license,v=>set({instructor_license:v,...(v?{instructor_registration_required:true}:{})}),'する','しない')}{a.instructor_license&&!card&&<div role="status"><p>認定講師制度を利用するにはAcademyカード決済の契約が必要です</p><a href={`/academy/h/${headquartersId}/manage/settings`}>決済設定をする</a><p>保存済みの講師制度の条件は保持します。契約・接続を確認するまで詳細設定と活動開始はロックされます。販売プランの作成は続けられます。</p></div>}{caps?.local_review&&<p>ローカル検証用の契約・接続状態です。実課金は行いません。</p>}</>}
 {active==='contract'&&<><p>本人の活動希望・講師登録・契約同意・料金・その他の条件を確認した後に活動を開始します。</p><PlanConditionPicker headquartersId={headquartersId} kind="instructor" label="条件を見る／編集" value={a.instructor_condition_id} onChange={id=>set({instructor_condition_id:id})}/>{a.required_skill_condition_id&&<PlanConditionPicker headquartersId={headquartersId} kind="skill" label="既存の前提条件" value={a.required_skill_condition_id} onChange={id=>set({required_skill_condition_id:id})}/>}</>}
 {active==='registration_fee'&&<>{yesNo('講師登録料',fee.enabled,enabled=>set({registration_fee:{...fee,enabled}}))}{fee.enabled&&<label>登録料（税込）<input type="number" min={1} step={1} value={fee.amount??''} onChange={e=>set({registration_fee:{...fee,amount:e.target.value?Number(e.target.value):null}})}/></label>}<p>活動開始時の初回費用です。Academyカード決済のみ利用できます。</p></>}
 {active==='dues'&&<>{yesNo('講師会費',dues.enabled,enabled=>patch({dues:{...dues,enabled,payment_method:'academy_card'}}))}{dues.enabled&&<><Cards label="会費の間隔" value={dues.interval} choices={[["month","月額"],["year","年額"]]} onChange={interval=>patch({dues:{...dues,interval}})}/><label>会費（税込）<input type="number" min={1} step={1} value={dues.amount??''} onChange={e=>patch({dues:{...dues,amount:e.target.value?Number(e.target.value):null}})}/></label><label>請求基準日<select value={dues.billing_anchor??''} onChange={e=>patch({dues:{...dues,billing_anchor:e.target.value as 'application'|'first'|'specified'}})}><option value="">請求基準日を選ぶ</option><option value="application">登録日基準</option><option value="first">毎月1日</option><option value="specified">指定日</option></select></label>{dues.billing_anchor==='specified'&&<label>指定日<input type="number" min={1} max={31} value={dues.billing_day??''} onChange={e=>patch({dues:{...dues,billing_day:e.target.value?Number(e.target.value):null}})}/></label>}<label>退会の適用<select value={dues.cancellation??''} onChange={e=>patch({dues:{...dues,cancellation:e.target.value as 'before_next'|'end_of_period'}})}><option value="">退会の適用を選ぶ</option><option value="before_next">次回請求前まで退会可</option><option value="end_of_period">支払い済み期間の終了時</option></select></label><label>未払い時の猶予日数<input type="number" min={0} max={365} value={dues.unpaid_grace_days??''} onChange={e=>patch({dues:{...dues,unpaid_grace_days:e.target.value?Number(e.target.value):null}})}/></label></>}<p>継続活動の費用です。Academyカード決済のみ利用できます。</p></>}
 {active==='rights'&&<>{rights.map(([id,text])=><label key={id}><input type="checkbox" checked={policy.rights.includes(id)} onChange={e=>set({instructor_policy:{...policy,rights:e.target.checked?[...policy.rights,id]:policy.rights.filter(x=>x!==id)}})}/> {text}</label>)}{policy.rights.includes('other')&&<label>その他の権利<textarea value={policy.other??''} maxLength={4000} onChange={e=>set({instructor_policy:{...policy,other:e.target.value}})}/></label>}</>}
 {active==='license_expiry'&&<ExpiryQuestion instructor value={policy.expiry} onChange={expiry=>set({instructor_policy:{...policy,expiry}})}/>}
 {active==='license_renewal'&&<RenewalQuestion instructor value={policy.renewal} onChange={renewal=>set({instructor_policy:{...policy,renewal}})}/>}
 {active==='opening'&&<>{yesNo('開講ライセンス料',opening.enabled,enabled=>patch({opening_license:{...opening,enabled,payment_method:'academy_card'}}))}{opening.enabled&&<><label>開講ライセンス料（税込）<input type="number" min={1} value={opening.amount??''} onChange={e=>patch({opening_license:{...opening,amount:e.target.value?Number(e.target.value):null}})}/></label><Cards label="ライセンス料のタイミング" value={opening.timing??'initial'} choices={[["initial","初回のみ"],["per_event","開講ごと"],["renewal","更新時"]]} onChange={timing=>patch({opening_license:{...opening,timing}})}/><label>講師向け開講用キット<select value={opening.kit} onChange={e=>patch({opening_license:{...opening,kit:e.target.value as 'none'|'included'|'separate_order'}})}><option value="none">なし</option><option value="included">料金に含む</option><option value="separate_order">別途注文</option></select></label></>}<p>Academyカード決済のみ利用できます。</p></>}
 {active==='manual'&&<><Cards label="講師マニュアルの準備" value="later" choices={[["now","今作成する"],["later","後で作成する"]]} onChange={v=>{if(v==='now')setManual(true);}}/>{a.manual?.blocks.length? <button type="button" onClick={()=>setManual(true)}>マニュアルを編集する</button>:null}{a.instructor_manual_id&&<PlanConditionPicker headquartersId={headquartersId} kind="manual" label="保存済みのマニュアル文書" value={a.instructor_manual_id} onChange={id=>set({instructor_manual_id:id})}/>}</>}
 {active==='community'&&<PlanCommunitySettings headquartersId={headquartersId} configuration={c} patch={patch} cards/>}
 {active==='sales_page'&&yesNo('営業ページの利用',policy.rights.includes('sales_page'),v=>set({instructor_policy:{...policy,rights:v?[...new Set([...policy.rights,'sales_page'])]:policy.rights.filter(x=>x!=='sales_page')}}),'ON','OFF')}
 {active==='listing'&&yesNo('本部HP掲載',policy.website_listing,v=>set({instructor_policy:{...policy,website_listing:v,rights:v?[...new Set([...policy.rights,'website'])]:policy.rights.filter(x=>x!=='website')}}),'ON','OFF')}
 {active==='summary'&&<WizardSummary configuration={c}/>}
 {error&&<p role="alert">{error}<button type="button" onClick={()=>setRetry(x=>x+1)}>契約状態を再確認</button></p>}
 <div className={styles.wizardActions}><button type="button" disabled={index===0} onClick={()=>setQuestion(questions[index-1])}>前の質問へ戻る</button><button type="button" onClick={()=>active==='summary'?onComplete():setQuestion(questions[index+1])}>{active==='summary'?'この内容で進む':'次の質問へ'}</button></div>
 {manual&&<InstructorManualEditor reviewContext blocks={a.manual?.blocks??[]} onChange={blocks=>set({manual:{blocks}})} onSave={async()=>({staged:true})} onClose={()=>setManual(false)}/>}
 </div>;
}
