'use client';
import {useEffect,useRef,useState} from 'react';
import {readCourseShipping,saveCourseShipping,type CourseShipping,type CourseShippingRow} from '@/lib/academy2/plan-review';
export function CourseShippingSettings({headquartersId,courseId}:{headquartersId:string;courseId:string}){
 const [row,setRow]=useState<CourseShippingRow|null>(null),[value,setValue]=useState<CourseShipping>({enabled:false,name:'',contents:'',shipping:false,handover:false}),[dirty,setDirty]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[saved,setSaved]=useState(false),[retry,setRetry]=useState(0);const lock=useRef(false);
 useEffect(()=>{let live=true;readCourseShipping(headquartersId,[courseId]).then(rows=>{if(live){setRow(rows[0]);if(!dirty&&rows[0]?.configuration)setValue(rows[0].configuration);}}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[headquartersId,courseId,retry]);
 useEffect(()=>{if(!dirty)return;const warn=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue='';};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty]);
 const change=(v:Partial<CourseShipping>)=>{setValue(x=>({...x,...v}));setDirty(true);setSaved(false);setError('');};
 async function save(){if(lock.current||!row)return;if(value.enabled&&(!value.name.trim()||!value.shipping&&!value.handover))return setError('発送物の名前と受け渡し方法を入力してください。');lock.current=true;setBusy(true);setError('');try{const next=await saveCourseShipping(headquartersId,courseId,row.revision,value);setRow(next);setDirty(false);setSaved(true);}catch(e){setError(e instanceof Error?e.message:'保存できませんでした。');}finally{lock.current=false;setBusy(false);}}
 return <section aria-label="講座の発送物設定" style={{marginTop:20,padding:16,border:'1px solid #d8e6de',borderRadius:12,fontSize:14}}><h3>この講座に発送物がありますか？</h3><fieldset disabled={busy||!row} style={{border:0,padding:0}}><div style={{display:'flex',gap:12}}>{[false,true].map(v=><button key={String(v)} type="button" aria-pressed={value.enabled===v} onClick={()=>change({enabled:v})} style={{minHeight:44,padding:'8px 20px',border:'1px solid #8bc7ad',background:value.enabled===v?'#e3f1e9':'white',borderRadius:8}}>{v?'あり':'なし'}</button>)}</div>{value.enabled&&<div style={{display:'grid',gap:12,marginTop:12}}><label>キット名<input aria-label="講座のキット名" value={value.name} maxLength={200} onChange={e=>change({name:e.target.value})}/></label><label>内容<textarea aria-label="発送物の内容" value={value.contents} maxLength={4000} onChange={e=>change({contents:e.target.value})}/></label><label><input type="checkbox" checked={value.shipping} onChange={e=>change({shipping:e.target.checked})}/> 発送が必要</label><label><input type="checkbox" checked={value.handover} onChange={e=>change({handover:e.target.checked})}/> 対面時に手渡し可能</label></div>}<p>発送先は申込フォームで取得します。講師向け開講用キットとは別の設定です。</p><button type="button" onClick={()=>void save()} disabled={!dirty&&!!row?.configuration} style={{minHeight:44}}>{busy?'保存中…':'発送物設定を保存'}</button></fieldset><p role="status">{saved?'発送物設定を保存しました。':dirty?'発送物設定は未保存です。':!row?'読み込み中…':!row.configuration?'未設定です。「なし」の場合も一度保存してください。':''}</p>{error&&<div role="alert">{error}<button type="button" onClick={()=>setRetry(x=>x+1)}>再確認</button></div>}</section>;
}
