"use client";
import { useEffect, useRef, useState } from 'react';
import Link from 'next/link';
import {useRouter,useSearchParams} from 'next/navigation';
import {CourseShippingSettings} from './CourseShippingSettings';
import {SIX_STEP_REVIEW_PLAN} from '@/lib/academy2/plan-review';
import {getAcademy2CourseSettings,saveAcademy2CourseSettings,type Academy2CourseSettings} from '@/lib/academy2/course-settings';
import { AcademyImageUploader } from '@/components/academy/AcademyImageUploader';
import { readLessons, writeLessons } from '@/lib/academy/lesson-content';
import { toCurrentAcademyContextHref as href } from '@/lib/academy/access-context';
import { courseSampleDraft } from '@/lib/academy2/course-samples';
import type { CourseEditorDocument, CourseEditorInput, CourseEditorSave, CourseEditorSettings } from '@/lib/academy2/course-editor';
import type { AcademyPageBlock } from '@/types/database';
import styles from './course-editor.module.css';

type Props={ headquartersId?:string; initial:CourseEditorDocument|null; sampleId?:string|null; onSave:(input:CourseEditorSave)=>Promise<CourseEditorDocument>; onReload?:(courseId:string)=>Promise<CourseEditorDocument>; onCreated?:(id:string)=>void };
export function CourseEditor({headquartersId,initial,sampleId=null,onSave,onReload,onCreated}:Props){
 const search=useSearchParams();const shippingReview=true;
 const router=useRouter();const [referenceValue,setReferenceValue]=useState(''),[referenceDirty,setReferenceDirty]=useState(false),[referenceState,setReferenceState]=useState<Academy2CourseSettings|null>(null),[referenceLoading,setReferenceLoading]=useState(Boolean(initial&&headquartersId)),[referenceError,setReferenceError]=useState('');
 useEffect(()=>{if(!initial||!headquartersId)return;let live=true;getAcademy2CourseSettings(headquartersId,initial.course.id).then(value=>{if(live){setReferenceState(value);setReferenceValue(value.reference_price==null?'':value.reference_price.toLocaleString('ja-JP'));}}).catch(cause=>{if(live)setReferenceError(cause instanceof Error?cause.message:'単品参考価格を読み込めませんでした。');}).finally(()=>{if(live)setReferenceLoading(false);});return()=>{live=false;};},[initial?.course.id,headquartersId]);
 const seed=courseSampleDraft(sampleId);const [document,setDocument]=useState(initial);
 const [basic,setBasic]=useState<CourseEditorInput>(()=>initial?{name:initial.course.name,subtitle:initial.course.subtitle??'',description:initial.course.description??'',duration_text:initial.course.duration_text??'',main_image_url:initial.course.main_image_url??'',code:initial.course.code}:seed.basic);
 const [settings,setSettings]=useState<CourseEditorSettings>(initial?.settings??seed.settings);
 const [blocks,setBlocks]=useState<AcademyPageBlock[]>(()=>initial?(initial.materials.blocks.length?initial.materials.blocks:writeLessons(readLessons([],initial.materials.curriculum))):seed.blocks);
 const [dirty,setDirty]=useState(!initial);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [saved,setSaved]=useState(false);const [uncertainCreate,setUncertainCreate]=useState(false);
 const pending=useRef(false);const request=useRef<{key:string;id:string}|null>(null);const preview=useRef<HTMLDialogElement>(null);const basicPanel=useRef<HTMLElement>(null);
 const lessons=readLessons(blocks);const materialCount=lessons.reduce((n,item)=>n+item.blocks.length,0);
 useEffect(()=>{if(!dirty&&!referenceDirty)return;const warn=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue='';};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty,referenceDirty]);
 function changeBasic(key:keyof CourseEditorInput,value:string){setBasic(current=>({...current,[key]:value}));setDirty(true);setSaved(false);}
 function changeSettings(next:CourseEditorSettings){setSettings(next);setDirty(true);setSaved(false);}
 function apply(next:CourseEditorDocument){setDocument(next);setBasic({code:next.course.code,name:next.course.name,subtitle:next.course.subtitle??'',description:next.course.description??'',duration_text:next.course.duration_text??'',main_image_url:next.course.main_image_url??''});setSettings(next.settings);setBlocks(next.materials.blocks);setDirty(false);setSaved(true);setUncertainCreate(false);request.current=null;}
 async function save(navigateCreated=true){if(pending.current)return;const amount=referenceValue.trim()===''?null:Number(referenceValue.replaceAll(',',''));if(referenceDirty&&amount!==null&&(!/^\d+$/.test(referenceValue.replaceAll(',',''))||!Number.isSafeInteger(amount))){setError('単品参考価格は0円以上の整数で入力してください。未設定の場合は空欄にします。');return;}if(!basic.name.trim()){setError('講座名を入力してください。');return;}pending.current=true;setBusy(true);setError('');setSaved(false);
 const payload={courseId:document?.course.id??null,expectedUpdatedAt:document?.course.updated_at??null,materialRevision:document?.materials.revision??0,legacyUpdatedAt:document?.materials.legacyUpdatedAt??null,basic,settings,blocks};const key=JSON.stringify(payload);if(!request.current||request.current.key!==key)request.current={key,id:crypto.randomUUID()};
 let savedCourse:CourseEditorDocument|null=null;try{const next=await onSave({...payload,requestId:request.current.id});savedCourse=next;apply(next);if(referenceDirty&&headquartersId){const source=referenceState??await getAcademy2CourseSettings(headquartersId,next.course.id);const reference=await saveAcademy2CourseSettings(headquartersId,next.course.id,source.revision,amount,source.all_courses_eligible);setReferenceState(reference);setReferenceDirty(false);setReferenceError('');}if(!initial&&navigateCreated)onCreated?.(next.course.id);return next;}catch(cause){setError((savedCourse?'講座は保存済みですが、単品参考価格を保存できませんでした。入力内容は残っています。':'')+(cause instanceof Error?cause.message:'保存結果を確認できませんでした。入力内容は残っています。'));if(!savedCourse&&!document&&!['22023','42501','PT409'].includes((cause as {code?:string})?.code??''))setUncertainCreate(true);}finally{pending.current=false;setBusy(false);}}
 async function reload(){if(!document||!onReload||pending.current)return;if((dirty||referenceDirty)&&!window.confirm('入力中の変更を破棄して、保存済みの講座を読み直しますか？'))return;pending.current=true;setBusy(true);setError('');try{const [next,reference]=await Promise.all([onReload(document.course.id),headquartersId?getAcademy2CourseSettings(headquartersId,document.course.id):Promise.resolve(null)]);apply(next);if(reference){setReferenceState(reference);setReferenceValue(reference.reference_price==null?'':reference.reference_price.toLocaleString('ja-JP'));setReferenceDirty(false);setReferenceError('');}}catch(cause){setError(cause instanceof Error?cause.message:'講座を読み直せませんでした。');}finally{pending.current=false;setBusy(false);}}
 async function openMaterials(){if(pending.current||uncertainCreate)return;let next=document;if(dirty||referenceDirty||!next)next=await save(false)??null;if(next)router.push(href('/academy/courses/'+next.course.id+'?tab=lessons'));}
 return <main className={styles.wrap}><Link className={styles.back} href={href('/academy/courses')}>← 講座一覧へ</Link><div className={styles.titlebar}><div className={styles.en}>COURSE EDITOR</div><div className={styles.jp}>講座編集</div></div><div className={styles.head}><div><strong>{basic.name||'新しい講座'}</strong><span>{settings.sampleName?`「${settings.sampleName}」の見本から作成${document?'':'中'}`:'教える内容とレッスン教材を作ります。'}</span></div><button className={styles.save} type="button" disabled={busy} onClick={()=>void save()}>{busy?'保存中…':'保存する'}</button></div>
 {error&&<div className={styles.error} role="alert"><p>{error}</p>{uncertainCreate&&<p>重複作成を防ぐため入力を保っています。「保存する」で同じ内容の保存結果を確認できます。</p>}{document&&onReload&&<button type="button" disabled={busy} onClick={()=>void reload()}>保存済みの内容を読み直す</button>}</div>}
 <p className={styles.status} role="status">{busy?'保存中…':referenceDirty?'単品参考価格は未保存です。':saved?'保存しました。':(dirty||referenceDirty)?'変更内容は未保存です。':'保存済みの講座です。'}</p>
 <div className={styles.salesGuide}><div><strong>金額・販売方法・開催方法は販売プランで設定します。</strong><p>ここでは講座の内容と教材を作ります。保存した講座を販売プランで選んで、募集内容を設定してください。</p></div>{document&&!dirty&&!referenceDirty&&<Link className={styles.salesNext} href={href('/academy/offerings/new')}>販売プランをつくる →</Link>}</div><nav className={styles.tabs} aria-label="講座編集項目"><button className={`${styles.tab} ${styles.on}`} type="button" aria-pressed={true}>基本情報</button><button className={styles.tab} type="button" aria-pressed={false} disabled={busy||uncertainCreate} onClick={()=>void openMaterials()}>レッスン・教材</button></nav>
 <fieldset className={styles.formFields} disabled={busy||uncertainCreate}><div className={styles.layout}><div><section ref={basicPanel} className={styles.card}><h2>基本情報</h2><div className={styles.help}>まずは「何を教える講座なのか」を登録します。実際の販売価格や開催日は販売プランで設定します。</div>
 <div className={styles.field}><label htmlFor="course-name">講座名</label><p className={styles.hint}>受講者が見て、何を学ぶ講座か分かる名前がおすすめです。</p><input id="course-name" className={styles.input} value={basic.name} onChange={e=>changeBasic('name',e.target.value)}/></div>
 <div className={styles.field}><label htmlFor="course-description">この講座では何を学べますか？</label><p className={styles.hint}>例：キャンドル作りが初めての方に向けて、材料の特徴から基本的な作り方まで学びます。</p><textarea id="course-description" className={styles.textarea} value={basic.description} onChange={e=>changeBasic('description',e.target.value)}/></div>
 <div className={styles.field}><label htmlFor="course-audience">こんな方におすすめ</label><p className={styles.hint}>「誰に向いている講座か」を短く書いておくと、あとで販売ページを作る時にも使えます。</p><textarea id="course-audience" maxLength={10000} className={styles.textarea} value={settings.targetAudience} onChange={e=>changeSettings({...settings,targetAudience:e.target.value})}/></div>
 <div className={styles.field}><label htmlFor="course-subtitle">カード用の短い紹介文</label><p className={styles.hint}>販売ページで講座を紹介するときに使います。未入力の場合は講座説明から表示します。</p><input id="course-subtitle" className={styles.input} value={basic.subtitle} onChange={e=>changeBasic('subtitle',e.target.value)}/></div>
 <div className={styles.field}><label htmlFor="course-duration">目安の学習時間</label><input id="course-duration" className={styles.input} placeholder="約 120 分" value={basic.duration_text} onChange={e=>changeBasic('duration_text',e.target.value)}/></div>
 {headquartersId&&<div className={styles.field}><label htmlFor="course-reference-price">単品参考価格</label><p className={styles.hint}>この講座を単体で販売する場合の目安金額です。実際の販売価格は販売プランで設定します。</p><div className={styles.referenceInput}><input id="course-reference-price" className={styles.input} inputMode="numeric" placeholder="未設定" disabled={referenceLoading||Boolean(referenceError)} value={referenceValue} onChange={e=>{setReferenceValue(e.target.value);setReferenceDirty(true);setSaved(false);}} onBlur={()=>{const raw=referenceValue.replaceAll(',','');if(/^\d+$/.test(raw)&&Number.isSafeInteger(Number(raw)))setReferenceValue(Number(raw).toLocaleString('ja-JP'));}}/><span>円</span></div>{referenceError&&<p role="alert">{referenceError}</p>}</div>}
 {document&&<details className={styles.code}><summary>管理コード</summary><label>管理コード<input className={styles.input} value={basic.code??''} onChange={e=>changeBasic('code',e.target.value)}/></label></details>}
 {shippingReview&&document&&headquartersId&&<><CourseShippingSettings headquartersId={headquartersId} courseId={document.course.id}/>{search.get('salesPlanReview')&&<Link href={href('/academy/offerings/'+(search.get('salesPlanReview')==='new'?'new':search.get('salesPlanReview')||''))}>販売プランの確認へ戻る →</Link>}</>}<div className={styles.field}><button className={styles.salesNext} type="button" onClick={()=>void openMaterials()}>レッスン・教材設定へ →</button></div>
 </section>
 </div>
 <aside className={styles['side-note']}><div className={styles.note}><div className={styles['note-title']}>この講座について</div><div className={styles['note-body']}><b>講座は「教える内容」です。</b><br/>ここでは内容と教材だけを作ります。<hr/>この講座をどう売るかは、次に<b>販売プラン</b>で設定します。<div className={styles['not-here']}>ここでは設定しません：<br/>販売価格 / 支払方法 / 開催日時 / 定員 / 認定 / キット / ライセンス</div></div></div>
 <div className={styles.card} style={{marginTop:13}}><h2>サムネイル</h2><div className={styles.help}>講座一覧や販売ページで表示する画像です。</div><AcademyImageUploader compact currentUrl={basic.main_image_url} onUploaded={url=>changeBasic('main_image_url',url)}/></div>
 <div className={`${styles.card} ${styles['preview-card']}`} style={{marginTop:13}} aria-label="講座カードのプレビュー"><div className={styles['preview-image']}>{basic.main_image_url?<img src={basic.main_image_url} alt=""/>:<span>COURSE IMAGE</span>}</div><div className={styles['preview-body']}><div className={styles['preview-no']}>COURSE 01</div><h3>{basic.name||'講座名'}</h3><p>{basic.subtitle||basic.description||'講座の紹介文が表示されます。'}</p><div className={styles['preview-meta']}><span>{basic.duration_text||'時間未設定'}</span><span>{lessons.length}レッスン</span><span>{materialCount}教材</span></div><button type="button" className={`${styles.subtle} ${styles['preview-link']}`} onClick={()=>preview.current?.showModal()}>講座内容を見る →</button><label className={styles['display-row']}><span>販売ページに講座紹介を表示</span><input className={styles.switch} type="checkbox" checked={settings.showIntroduction} onChange={e=>changeSettings({...settings,showIntroduction:e.target.checked})}/></label></div></div>
 </aside></div></fieldset>
 <p className={styles.unsaved}>教材は下書きとして保存します。現在公開中の教材は変更しません。</p>{document&&onReload&&<button className={styles.subtle} type="button" disabled={busy} onClick={()=>void reload()}>保存済みの内容を読み直す</button>}
 <div className={styles['mobile-save']}><span>{busy?'保存中…':(dirty||referenceDirty)?'変更内容は未保存です。':'保存済み'}</span><button type="button" disabled={busy} onClick={()=>void save()}>{busy?'保存中…':'保存する'}</button></div>
 <dialog ref={preview} className={styles.previewDialog} aria-label="講座内容のプレビュー"><h2>{basic.name||'講座名'}</h2><p>{basic.description}</p><h3>こんな方におすすめ</h3><p>{settings.targetAudience||'未入力'}</p><ol>{lessons.map(lesson=><li key={lesson.id}>{lesson.title}（{lesson.blocks.length}教材）</li>)}</ol><button type="button" onClick={()=>preview.current?.close()}>閉じる</button></dialog>
 </main>;
}
