"use client";
import { useRef, useState } from 'react';
import Link from 'next/link';
import { toCurrentAcademyContextHref as href } from '@/lib/academy/access-context';
import type { Academy2Course } from '@/lib/academy2/courses';
import { courseSamples } from '@/lib/academy2/course-samples';
import styles from './course-catalog.module.css';
const updated = (value: string) => Number.isFinite(Date.parse(value)) ? new Intl.DateTimeFormat('ja-JP', { timeZone: 'Asia/Tokyo', month: 'numeric', day: 'numeric' }).format(new Date(value)) : '未確認';
export function CourseCatalog({ courses }: { courses: Academy2Course[] }) {
 const [query, setQuery] = useState(''); const [sort, setSort] = useState('updated'); const modal = useRef<HTMLDialogElement>(null);
 const visible = courses.filter(course => course.name.toLocaleLowerCase().includes(query.trim().toLocaleLowerCase())).slice().sort((a,b) => sort==='name' ? a.name.localeCompare(b.name,'ja') : b.updated_at.localeCompare(a.updated_at));
 return <main className={styles.wrap}><section><div className={styles.titlebar}><div className={styles.en}>COURSES</div><div className={styles.jp}>講座</div></div><div className={styles.headbox}><p>教える内容とレッスン教材を管理します。<br/>価格や販売方法は、あとで「販売プラン」で設定します。</p><button className={styles.create} type="button" onClick={()=>modal.current?.showModal()}>＋ 講座をつくる</button></div></section>
 <div className={styles.tools}><input className={styles.search} aria-label="講座名で検索" placeholder="講座名で検索" value={query} onChange={e=>setQuery(e.target.value)}/><select className={`${styles.filter} ${styles.sort}`} aria-label="講座の並び順" value={sort} onChange={e=>setSort(e.target.value)}><option value="updated">更新が新しい順</option><option value="name">講座名順</option></select></div>
 <section className={styles.list} aria-label="講座一覧">{visible.map((course,index)=><Link key={course.id} className={styles.course} href={href('/academy/courses/'+course.id)}><div className={styles.thumb}>{course.main_image_url?<img src={course.main_image_url} alt=""/>:String(index+1).padStart(2,'0')}</div><div><h3>{course.name}</h3><div className={styles['course-meta']}><span><b>{course.lesson_count??'未確認'}</b> レッスン</span><span><b>{course.material_count??'未確認'}</b> 教材</span><span>更新 {updated(course.updated_at)}</span></div></div><span className={styles.arrow} aria-hidden>›</span></Link>)}</section>
 {!visible.length&&<p className={styles.count}>{courses.length?'条件に合う講座がありません。':'講座はまだありません。見本から始められます。'}</p>}
 <div className={styles['empty-tip']}><div><strong>何から作ればいいか迷ったら</strong><p>ハンドメイド・占い・クッキングなど、近い見本から始められます。</p></div><Link className={styles['text-link']} href={href('/academy/courses/new?view=samples')}>講座見本を見る →</Link></div>
 <dialog ref={modal} className={styles.modalNative} aria-label="講座の作り方"><div className={styles['modal-head']}><strong>CREATE COURSE</strong><small>講座をつくる</small></div><div className={styles['modal-body']}><div className={styles['choice-grid']}><Link className={styles.choice} href={href('/academy/courses/new?view=samples')}><div className={styles['choice-icon']}>▤</div><strong>見本からつくる</strong><p>近い見本を選んで、講座名や内容を書き換えていきます。</p></Link><Link className={styles.choice} href={href('/academy/courses/new?blank=1')}><div className={styles['choice-icon']}>＋</div><strong>まっさらからつくる</strong><p>自分の構成で、講座とレッスンを作り始めます。</p></Link></div><button className={styles.close} type="button" onClick={()=>modal.current?.close()}>閉じる</button></div></dialog>
 </main>;
}
export function CourseSamples() {
 const [filter,setFilter]=useState('すべて');const groups=['すべて',...courseSamples.map(sample=>sample.group)];
 return <main className={`${styles.wrap} ${styles.samplesWrap}`}><Link className={styles.back} href={href('/academy/courses')}>← 講座一覧へ</Link><div className={styles.titlebar}><div className={styles.en}>COURSE SAMPLES</div><div className={styles.jp}>講座見本</div></div><div className={styles.intro}><strong>自分の講座に近いものを選んでください。</strong><p>見本にはレッスン構成と書き方のヒントが入っています。選んだあと、名前も内容も自由に変更できます。</p></div><div className={styles.filters}>{groups.map(group=><button type="button" key={group} aria-pressed={filter===group} onClick={()=>setFilter(group)} className={`${styles.chip} ${filter===group?styles.on:''}`}>{group}</button>)}</div><section className={styles.samples}>{courseSamples.filter(sample=>filter==='すべて'||sample.group===filter).map(sample=><article key={sample.id} className={styles.sample}><div className={styles['sample-top']}><span className={styles['sample-type']}>{sample.type}</span></div><div className={styles['sample-body']}><h3>{sample.name}</h3><div className={styles['sample-desc']}>{sample.description}</div><div className={styles.sampleAudience}><b>こんな方に</b><p>{sample.audience}</p></div><div className={styles.lessons}>{sample.lessons.map((lesson,index)=><div className={styles.lesson} key={lesson}><b>{String(index+1).padStart(2,'0')}</b>{lesson}</div>)}</div><div className={styles.use}><span>{sample.lessons.length}レッスン</span><Link className={styles.sampleUse} href={href('/academy/courses/new?sample='+sample.id)}>この見本を使う →</Link></div></div></article>)}</section><div className={styles.blank}><div><strong>近い見本がなくても大丈夫です。</strong><p>まっさらな講座を作って、自分の構成で始められます。</p></div><Link href={href('/academy/courses/new?blank=1')}>まっさらからつくる →</Link></div></main>;
}
