'use client';
import {useEffect,useRef,useState} from 'react';
import {assignmentCandidates,type AssignmentCandidates} from '@/lib/academy2/instructor-assignments';
import {replaceEventAssignment} from '@/lib/academy2/event-assignment-replacement';
import styles from './event-detail.module.css';
export function EventAssignmentReplacement({headquartersId,eventId,revision,disabled,onReload,onDirtyChange,onBusyChange}:{headquartersId:string;eventId:string;revision:number;disabled:boolean;onReload:()=>void;onDirtyChange:(value:boolean)=>void;onBusyChange:(value:boolean)=>void}){
 const [view,setView]=useState<AssignmentCandidates|null>(null),[instructor,setInstructor]=useState(''),[amount,setAmount]=useState(''),[reason,setReason]=useState(''),[dirty,setDirty]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[saved,setSaved]=useState(false),[loading,setLoading]=useState(true);
 const lock=useRef(false),live=useRef(true),request=useRef<{signature:string;id:string}|null>(null),callbacks=useRef({onReload,onDirtyChange,onBusyChange});callbacks.current={onReload,onDirtyChange,onBusyChange};
 async function refresh(){if(lock.current)return;setLoading(true);setError('');try{const next=await assignmentCandidates(headquartersId,eventId);if(live.current){setView(next);request.current=null;}}catch(e){if(live.current)setError(e instanceof Error?e.message:'担当情報を確認できませんでした。');}finally{if(live.current)setLoading(false);}}
 useEffect(()=>{live.current=true;void refresh();return()=>{live.current=false;callbacks.current.onDirtyChange(false);callbacks.current.onBusyChange(false);};},[headquartersId,eventId]);
 useEffect(()=>{callbacks.current.onDirtyChange(dirty);if(!dirty)return;const guard=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue='';};window.addEventListener('beforeunload',guard);return()=>window.removeEventListener('beforeunload',guard);},[dirty]);
 useEffect(()=>{callbacks.current.onBusyChange(busy);},[busy]);
 const accepted=view?.requests.find(r=>r.status==='accepted'),pending=view?.requests.find(r=>['requested','consulting'].includes(r.status));
 const changed=()=>{setDirty(true);setSaved(false);};
 async function save(){if(!accepted||lock.current||disabled||loading)return;const value=Number(amount);if(!instructor||!amount.trim()||!Number.isSafeInteger(value)||value<0||!reason.trim())return setError('新しい担当講師、担当料、交代理由を入力してください。');
 const input={oldRequestId:accepted.id,oldRevision:accepted.revision,instructorId:instructor,amount:value,reason:reason.trim()};const signature=JSON.stringify({revision,input});if(request.current?.signature!==signature)request.current={signature,id:crypto.randomUUID()};
 lock.current=true;setBusy(true);setError('');try{const next=await replaceEventAssignment(headquartersId,eventId,revision,request.current.id,input);if(!live.current)return;setView(next.assignments);setDirty(false);setSaved(true);request.current=null;callbacks.current.onReload();}catch(e){if(live.current)setError(e instanceof Error?e.message:'保存できませんでした。入力内容は残っています。');}finally{lock.current=false;if(live.current)setBusy(false);}}
 return <div className={styles.section}>{error?<p role="alert" className={styles.error}>{error}</p>:null}{accepted?<details><summary>担当講師を交代する</summary><p className={styles.help}>現在の依頼を取り消し、新しい講師に依頼します。承諾と発送先の指定が済むまでキットを発送できません。以前の発送記録は残ります。</p><fieldset className={styles.shippingForm} disabled={disabled||busy||loading}><label>新しい担当講師<select aria-label="交代する講師" value={instructor} onChange={e=>{setInstructor(e.target.value);changed();}}><option value="">選択してください</option>{view?.candidates.filter(c=>c.id!==accepted.instructorId).map(c=><option key={c.id} value={c.id}>{c.name??'氏名未設定'}</option>)}</select></label><label>新しい担当料（円）<input aria-label="交代後の担当料" type="number" min={0} step={1} value={amount} onChange={e=>{setAmount(e.target.value);changed();}}/></label><label>交代理由<textarea aria-label="担当交代の理由" maxLength={2000} value={reason} onChange={e=>{setReason(e.target.value);changed();}}/></label><button type="button" className={styles.btn} onClick={()=>void save()}>{busy?'交代を保存中…':'交代を依頼する'}</button></fieldset></details>:pending?<p className={styles.help}>{pending.instructorName??'新しい担当講師'}の承諾を待っています。</p>:null}
 {dirty?<button className={styles.btn} disabled={busy||disabled} onClick={()=>{if(window.confirm('保存していない担当交代の入力を取り消しますか？')){setInstructor('');setAmount('');setReason('');setDirty(false);request.current=null;}}}>交代の入力を取り消す</button>:null}
 {accepted||error||dirty?<button className={styles.btn} disabled={busy||loading||disabled} onClick={()=>{void refresh();callbacks.current.onReload();}}>入力を残して担当情報を再確認</button>:null}{saved?<p role="status">新しい講師に交代を依頼しました。承諾を待っています。</p>:null}
 </div>;
}
