'use client';

import {useEffect,useState} from 'react';
import {getHeadquartersSettings,saveHeadquartersBasic,saveHeadquartersDocument,type HeadquartersBasic,type HeadquartersDocumentKind,type HeadquartersSettings} from '@/lib/academy2/headquarters-settings';
import {inviteAcademy2Staff,type Academy2InvitableRole} from '@/lib/academy2/staff-invitations';
import type {Academy2HeadquartersContext} from '@/lib/academy2/context';
import styles from './headquarters-settings.module.css';
import {FirstPublicationSetup} from './FirstPublicationSetup';

const roleNames:Record<string,string>={owner:'本部責任者',administrator:'本部運営担当',learning_operator:'受講運営担当',course_editor:'講座編集担当'};
const documents:{kind:HeadquartersDocumentKind;label:string;description:string}[]=[
 {kind:'application',label:'共通申込規約',description:'全販売タイプで使用する基本規約'},
 {kind:'commerce',label:'特定商取引法に基づく表記',description:'本部販売時の販売者情報・支払条件等'},
 {kind:'cancellation',label:'キャンセル・返金ポリシー',description:'キャンセル・日程変更・返金・無断キャンセル'},
 {kind:'privacy',label:'プライバシーポリシー',description:'受講者情報の取扱い'},
 {kind:'instructor_contract',label:'認定講師契約書',description:'講師契約の本文とバージョン'}
];
const date=(value:string|null|undefined)=>value?new Date(value).toLocaleString('ja-JP',{timeZone:'Asia/Tokyo'}):'未確認';

/** Content grid, card density and fields follow approved UI31. No legacy settings component is mounted. */
export function HeadquartersSettingsPanels({headquarters,tab}:{headquarters:Academy2HeadquartersContext;tab:string}){
 const [saved,setSaved]=useState<HeadquartersSettings|null>(null);
 const [basic,setBasic]=useState<HeadquartersBasic|null>(null);
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[retry,setRetry]=useState(0);
 const [editing,setEditing]=useState<HeadquartersDocumentKind|null>(null),[version,setVersion]=useState(''),[body,setBody]=useState(''),[revision,setRevision]=useState(0);
 const [inviteTarget,setInviteTarget]=useState(''),[inviteRole,setInviteRole]=useState<Academy2InvitableRole>('administrator');
 const canEdit=headquarters.role==='administrator';
 const dirty=!!basic&&!!saved&&JSON.stringify(basic)!==JSON.stringify(saved.basic);
 const docDirty=!!editing&&(version!==(saved?.documents.find(item=>item.kind===editing)?.version??'')||body!==(saved?.documents.find(item=>item.kind===editing)?.body??''));
 useEffect(()=>{let current=true;setBusy(true);setError('');setSaved(null);setBasic(null);setEditing(null);getHeadquartersSettings(headquarters.id).then(value=>{if(current){setSaved(value);setBasic(value.basic);}}).catch(cause=>{if(current)setError(cause.message);}).finally(()=>{if(current)setBusy(false);});return()=>{current=false;};},[headquarters.id,retry]);
 useEffect(()=>{if(!dirty&&!docDirty)return;const warn=(event:BeforeUnloadEvent)=>{event.preventDefault();event.returnValue='';};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty,docDirty]);
 async function saveBasic(){if(!basic||busy)return;setBusy(true);setError('');setMessage('');try{const value=await saveHeadquartersBasic(headquarters.id,basic);setSaved(value);setBasic(value.basic);setMessage('本部情報を保存しました。');}catch(cause){setError(cause instanceof Error?cause.message:'保存できませんでした。');}finally{setBusy(false);}}
 async function saveDocument(){if(!editing||busy)return;setBusy(true);setError('');setMessage('');try{const value=await saveHeadquartersDocument(headquarters.id,editing,revision,version,body);setSaved(value);setRevision(value.documents.find(item=>item.kind===editing)?.revision??revision);setMessage('規約の新しい版を保存しました。');}catch(cause){setError(cause instanceof Error?cause.message:'保存できませんでした。');}finally{setBusy(false);}}
 async function invite(){if(busy)return;setBusy(true);setError('');setMessage('');try{await inviteAcademy2Staff({headquartersId:headquarters.id,channel:'mikke_id',target:inviteTarget,role:inviteRole});const value=await getHeadquartersSettings(headquarters.id);setSaved(value);setMessage('招待を登録しました。承諾後に権限が有効になります。');setInviteTarget('');}catch(cause){setError(cause instanceof Error?'招待を登録できませんでした。mikke IDと既存の招待を確認してください。':'招待できませんでした。');}finally{setBusy(false);}}
 function editDocument(kind:HeadquartersDocumentKind){if(busy)return;if(docDirty&&!window.confirm('編集中の規約は未保存です。別の規約を開きますか？'))return;const value=saved?.documents.find(item=>item.kind===kind);setEditing(kind);setVersion(value?.version??'');setBody(value?.body??'');setRevision(value?.revision??0);setMessage('');setError('');}
 if(tab==='通知メール')return null;
 if(!saved||!basic)return <div className={styles.note}>{busy?<p role="status">本部設定を読み込んでいます…</p>:<><p role="alert">{error}</p><button className={styles.btn} onClick={()=>setRetry(value=>value+1)}>再読み込み</button></>}</div>;
 return <>
 {tab==='本部情報'&&<section className={styles.card}><h2>本部情報</h2><p className={styles.help}>Academy本部として使用する基本情報です。本部HPの本文とは別です。</p><div className={styles.grid2}>{(['name','contact_email'] as const).map(key=><div className={styles.field} key={key}><label>{key==='name'?'本部名':'問い合わせメール'}<input type={key==='contact_email'?'email':'text'} disabled={!canEdit||busy} value={basic[key]} onChange={event=>{setBasic({...basic,[key]:event.target.value});setMessage('');}}/></label></div>)}</div>{(['tagline','default_payment_note'] as const).map(key=><div className={styles.field} key={key}><label>{key==='tagline'?'本部紹介':'支払い案内の既定文'}<textarea disabled={!canEdit||busy} value={basic[key]} onChange={event=>{setBasic({...basic,[key]:event.target.value});setMessage('');}}/></label></div>)}<div className={styles.actions}><button className={`${styles.btn} ${styles.orange}`} disabled={!canEdit||busy||!dirty} onClick={()=>void saveBasic()}>本部情報を保存</button></div><p className={styles.help} role="status">{dirty?'未保存の変更があります。':'保存済みの本部情報です。'}</p><p className={styles.help}>本部表示のロゴ・HERO画像は接続準備中です。</p></section>}
 {tab==='決済'&&<section className={styles.card}><h2>本部の決済方法</h2><p className={styles.help}>共通決済手段を設定します。販売プランごとの金額・外部決済URLは販売プラン側です。</p><div className={styles.method}><div className={styles.methodHead}><strong>銀行振込</strong><span className={styles.status}>入力項目の接続準備中</span></div><p className={styles.help}>現在の支払い案内は本部情報で確認・編集できます。</p></div><div className={styles.method}><div className={styles.methodHead}><strong>カード決済</strong><span className={styles.status}>{saved.connect?.ready?'利用できます':saved.connect?'確認が必要':'未設定'}</span></div><p className={styles.help}>Academy上のカード決済にはStripe Connectを利用します。</p>{saved.connect&&<p className={styles.help}>決済：{saved.connect.charges_enabled?'有効':'確認が必要'} ／ 送金：{saved.connect.payouts_enabled?'有効':'確認が必要'}<br/>確認日時：{date(saved.connect.verified_at)}</p>}<div className={styles.actions}><button className={styles.btn} disabled={busy||dirty||docDirty} onClick={()=>setRetry(value=>value+1)}>接続状態を確認</button></div><p className={styles.help}>Connectの登録・変更画面への接続は準備中です。</p></div></section>}
 {tab==='規約・契約'&&<><section className={styles.card}><h2>受講者向け規約・表示</h2><p className={styles.help}>本部販売や申込で使用する共通テンプレートを管理します。</p><div className={styles.templateList}>{documents.map(item=><div className={styles.templateRow} key={item.kind}><div><strong>{item.label}</strong><p>{item.description} ／ {saved.documents.find(doc=>doc.kind===item.kind)?.version??'未保存'}</p></div><button className={styles.btn} disabled={busy} onClick={()=>editDocument(item.kind)}>{canEdit?'編集':'内容を見る'}</button></div>)}</div><p className={styles.note}>過去の同意内容は変更しません。保存した本文の販売プラン・講師契約への適用は接続準備中です。</p></section>{editing&&<section className={styles.card}><h2>{documents.find(item=>item.kind===editing)?.label}</h2><div className={styles.field}><label>バージョン<input value={version} disabled={!canEdit||busy} onChange={event=>{setVersion(event.target.value);setMessage('');}}/></label></div><div className={styles.field}><label>本文<textarea value={body} disabled={!canEdit||busy} onChange={event=>{setBody(event.target.value);setMessage('');}}/></label></div><div className={styles.actions}><button className={`${styles.btn} ${styles.orange}`} disabled={!canEdit||busy||!docDirty} onClick={()=>void saveDocument()}>保存</button></div><p className={styles.help} role="status">{docDirty?'未保存の変更があります。':'保存済みの本文です。'}</p></section>}</>}
 {tab==='役割・権限'&&<><section className={styles.card}><h2>役割・権限</h2><div className={styles.templateList}>{Object.entries(roleNames).map(([key,label])=><div className={styles.templateRow} key={key}><strong>{label}</strong><p>{key==='owner'?'Connect最上位設定・認定や重大な権限の取消':key==='administrator'?'入金・返金・担当料・認定確定を含む日常運営':key==='learning_operator'?'申込・開催・発送・修了確認などの受講運営':'講座・レッスン教材・公開ページの編集'}</p></div>)}</div></section><section className={styles.card}><h2>本部メンバー</h2>{saved.members.map((member,index)=><div className={styles.linkRow} key={index}><span>{member.handle?`@${member.handle}`:'mikke ID未設定'} ／ {member.active?'利用中':'停止中'}</span><span>{roleNames[member.role]}</span></div>)}{headquarters.role==='owner'&&<><div className={styles.grid2}><div className={styles.field}><label>mikke ID<input placeholder="@username" value={inviteTarget} onChange={event=>setInviteTarget(event.target.value)} disabled={busy}/></label></div><div className={styles.field}><label>役割<select value={inviteRole} onChange={event=>setInviteRole(event.target.value as Academy2InvitableRole)} disabled={busy}>{(['administrator','learning_operator','course_editor'] as const).map(role=><option value={role} key={role}>{roleNames[role]}</option>)}</select></label></div></div><div className={styles.actions}><button className={`${styles.btn} ${styles.orange}`} onClick={()=>void invite()} disabled={busy||!inviteTarget.trim()}>招待</button></div>{saved.invitations.map(item=><p className={styles.help} key={item.id}>{roleNames[item.role]} ／ {item.status==='pending'?'承諾待ち':item.status} ／ 期限 {date(item.expires_at)}</p>)}</>}<p className={styles.help}>メール招待の配信と、スタッフの役割変更・取消は接続準備中です。</p></section></>}
 {tab==='利用料金'&&<section className={styles.card}><h2>Academy利用料金</h2><p className={styles.help}>現行の料金計算・人数計算を維持します。</p>{saved.billing?<><div className={styles.summaryRow}><div className={styles.summaryBox}><b>現行料金表の見積</b><span>{saved.billing.estimate? saved.billing.estimate.catalog_price_yen.toLocaleString('ja-JP')+'円':'確認が必要'}</span></div><div className={styles.summaryBox}><b>課金対象の講師</b><span>{saved.billing.estimate? saved.billing.estimate.registered_instructor_count+'名':'確認が必要'}</span></div><div className={styles.summaryBox}><b>利用状態</b><span>{saved.billing.access?({active:'利用中',trialing:'体験利用中',expired:'期間終了',cancelled:'終了',past_due:'支払い確認中'}[saved.billing.access.status]??'確認が必要'):'確認が必要'}</span></div></div><p className={styles.note}>既存の料金計算が確認できた場合に見積を表示します。割引・既存契約・請求済み金額を変更するものではありません。契約・支払い手続きへの接続は準備中です。</p>{saved.billing.access?.trial_ends_at&&<p className={styles.help}>無料期間の終了：{date(saved.billing.access.trial_ends_at)}</p>}</>:<p className={styles.note}>利用料金と契約は本部責任者が確認します。</p>}<a className={styles.linkRow} href="/legal/academy/billing/2026-09-04-v1" target="_blank" rel="noreferrer">料金・支払い条件を見る</a></section>}
 {tab==='利用料金'&&headquarters.role==='owner'&&<FirstPublicationSetup headquartersId={headquarters.id}/>}
 {['お知らせ','Community'].includes(tab)&&<section className={styles.card}><h2>{tab}</h2><p className={styles.note}>この設定の保存・連携は準備中です。</p></section>}
 {busy&&<p className={styles.help} role="status">処理中です…</p>}{message&&<p className={styles.note} role="status">{message}</p>}{error&&<p className={styles.error} role="alert">{error}</p>}
 </>;
}
