'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {assignmentLabels} from '@/lib/academy2/instructor-assignments';
import {Users} from 'lucide-react';
import {AcademyListTools} from '@/components/academy/AcademyListTools';
import {useAcademy2Headquarters} from './HeadquartersBoundary';
import {listHeadquartersInstructors,type HeadquartersInstructor} from '@/lib/academy2/headquarters-instructors';
import {toAcademyContextHref} from '@/lib/academy/access-context';
import {INSTRUCTOR_REGISTRATION_STATUS_LABELS} from '@/lib/academy/instructors';
const registration=(value:string)=>(INSTRUCTOR_REGISTRATION_STATUS_LABELS as Record<string,string>)[value]??value;
const activity=(value:string)=>(({active:'有効',payment_pending:'支払待ち',leave:'休会',suspended:'休止'} as Record<string,string>)[value]??value);
function Badge({on,label}:{on:boolean;label:string}){return <span className={`rounded-lg border px-2 py-0.5 text-[10px] font-bold ${on?'border-[var(--mikke-success)]/30 bg-[var(--mikke-success-soft)] text-[var(--mikke-success)]':'border-[var(--mikke-line)] bg-[var(--mikke-surface-soft)] text-[var(--mikke-muted)]'}`}>{label}</span>;}
/** Existing instructor page/card geometry, with only the scoped 2.0 read adapter mounted. */
export function HeadquartersInstructorReadOnly({instructorId}:{instructorId?:string}){
 const hq=useAcademy2Headquarters();const [rows,setRows]=useState<HeadquartersInstructor[]|null>(null),[error,setError]=useState(''),[retry,setRetry]=useState(0),[query,setQuery]=useState(''),[filter,setFilter]=useState('all');
 useEffect(()=>{if(!hq)return;let current=true;setRows(null);setError('');listHeadquartersInstructors(hq.id,instructorId??null).then(result=>{if(current)setRows(result);}).catch(cause=>{if(current)setError(cause instanceof Error?cause.message:'講師情報を読み込めませんでした。');});return()=>{current=false;};},[hq?.id,instructorId,retry]);
 if(!hq)return null;const href=(path:string)=>toAcademyContextHref(path,hq.id,'manage');
 if(error)return <div role="alert" className="space-y-3 text-sm"><p>{error}</p><button type="button" onClick={()=>setRetry(value=>value+1)} className="rounded-lg border px-3 py-2">再読み込み</button></div>;
 if(!rows)return <p role="status" className="py-10 text-center text-sm text-[var(--mikke-muted)]">読み込み中…</p>;
 if(instructorId){const ins=rows[0];if(!ins)return <p>この本部の講師情報はありません。</p>;return <div className="space-y-4">
  <section className="flex flex-col gap-4 rounded-2xl border border-[var(--mikke-line)] bg-white p-4 md:flex-row md:items-start md:justify-between"><div><div className="flex items-center gap-2"><h2 className="text-base font-bold text-[var(--mikke-text)]">{ins.name||'（屋号未設定）'}</h2></div><p className="mt-1 text-xs text-[var(--mikke-muted)]">{ins.instructorNumber?`講師番号 ${ins.instructorNumber}`:'講師番号未設定'}</p><p className="mt-2 text-xs font-bold text-[var(--mikke-accent-strong)]">{registration(ins.registrationStatus)}</p></div><div className="flex flex-wrap gap-1"><Badge on={ins.certified} label={ins.certified?'認定済み':'未認定'}/><Badge on={ins.listed} label={ins.listed?'掲載設定あり':'非掲載設定'}/></div></section>
  <section className="space-y-1 rounded-2xl border border-[var(--mikke-line)] bg-white p-4"><p className="text-xs font-bold text-[var(--mikke-text-soft)]">担当講座</p><Link className="text-sm text-[var(--mikke-primary)]" href={href(`/academy/courses/${ins.courseId}`)}>{ins.courseName??'講座を確認'}</Link><p className="text-xs text-[var(--mikke-muted)]">既存の登録状態：{registration(ins.registrationStatus)}</p></section>
  <section className="space-y-3 rounded-2xl border border-[var(--mikke-line)] bg-white p-4"><p className="text-xs font-bold text-[var(--mikke-text-soft)]">講師ライセンス</p>{ins.activities.length?ins.activities.map(item=><div key={item.id} className="space-y-1 border-t border-[var(--mikke-line)] py-2 text-sm"><Link href={href(`/academy/offerings/${item.salesPlanId}`)} className="text-[var(--mikke-primary)]">対象の販売プランを確認 →</Link><p>活動状態：{activity(item.status)}</p><p>講師ライセンス：{item.licenseEffective?'有効':'現在は有効ではありません'}</p>{item.transitionReviewRequired?<p>本部による確認が必要です。</p>:null}</div>):<p className="text-sm">2.0の講師ライセンス登録はありません。認定済みという情報だけで活動権限を付与しません。</p>}</section>
  <section className="space-y-3 rounded-2xl border border-[var(--mikke-line)] bg-white p-4"><p className="text-xs font-bold text-[var(--mikke-text-soft)]">本部からの講師依頼・講座担当料</p><p className="text-xs">カード決済登録：{ins.connectReady?'確認済み':'未確認'}</p><p className="text-xs">本部からの依頼：{ins.acceptHqRequests?'受付中':'受付停止'}</p>{ins.assignmentRequests?.map(r=><div key={r.id} className="border-t border-[var(--mikke-line)] pt-2 text-xs"><Link className="text-[var(--mikke-primary)]" href={href('/academy/classes/'+r.eventId)}>{r.event.title} →</Link><p>{assignmentLabels[r.status]}</p>{r.feeYen!==null?<p>講座担当料 ¥{r.feeYen.toLocaleString('ja-JP')}</p>:null}</div>)}<p className="text-xs text-[var(--mikke-muted)]">担当依頼は開催の詳細から行います。担当料の実送金は未接続です。</p></section>
  <section className="space-y-2 rounded-2xl border border-[var(--mikke-line)] bg-white p-4"><p className="text-xs font-bold text-[var(--mikke-text-soft)]">登録契約</p><p className="text-xs text-[var(--mikke-muted)]">登録申請・更新・取消の操作はまだ接続していません。現在は登録済み情報の確認のみ可能です。</p></section>
  <Link href={href('/academy/instructors')} className="block w-full rounded-xl border border-[var(--mikke-line)] bg-white px-4 py-3 text-center text-sm font-bold text-[var(--mikke-text-soft)]">一覧に戻る</Link>
 </div>;}
 const visible=rows.filter(ins=>`${ins.name??''} ${ins.courseName??''} ${ins.instructorNumber??''}`.toLocaleLowerCase().includes(query.trim().toLocaleLowerCase())&&(filter==='all'||ins.activities.some(item=>item.licenseEffective)));
 return <div className="space-y-4"><div><p className="text-xs text-[var(--mikke-muted)]">{hq.name}</p><h2 className="text-2xl font-bold text-[var(--mikke-text)]">講師</h2><p className="mt-2 text-sm text-[var(--mikke-muted)]">担当講座・登録状態・講師ライセンスを確認できます。件数は講座ごとの登録数です。</p></div>
 <section className="flex flex-wrap items-center justify-between gap-3 rounded-lg border border-[var(--mikke-line)] bg-white p-4"><div className="min-w-0"><p className="text-sm font-bold text-[var(--mikke-text)]">講師を追加する</p><p className="mt-1 text-xs leading-5 text-[var(--mikke-muted)]">登録申請・追加の保存接続を準備中です。既存の講師情報を確認できます。</p></div><button type="button" disabled className="inline-flex w-full items-center justify-center gap-1 rounded-lg bg-[var(--mikke-accent)] px-4 py-2.5 text-sm font-bold text-white opacity-60 sm:w-auto">講師を登録</button></section>
 <AcademyListTools label="講師・担当講座" query={query} onQuery={setQuery} filter={filter} onFilter={setFilter} count={visible.length} options={[{value:'all',label:'すべて',count:rows.length},{value:'active',label:'講師ライセンス有効',count:rows.filter(ins=>ins.activities.some(item=>item.licenseEffective)).length}]}/>
 {!visible.length?<div className="rounded-lg border border-dashed border-[var(--mikke-line)] bg-white p-8 text-center"><Users size={28} className="mx-auto text-[var(--mikke-accent)]"/><p className="mt-2 text-sm text-[var(--mikke-text-soft)]">{rows.length?'条件に合う講師登録がありません。':'まだ講師がいません。'}</p></div>:<ul className="grid gap-2 md:grid-cols-2 lg:grid-cols-3">{visible.map(ins=><li key={ins.id}><Link href={href(`/academy/instructors/${ins.id}`)} className="block border border-[var(--mikke-line)] bg-white p-4"><div className="flex items-start justify-between gap-2"><div className="min-w-0"><p className="truncate text-sm font-bold text-[var(--mikke-text)]">{ins.name||'（屋号未設定）'}</p><p className="mt-0.5 truncate text-xs text-[var(--mikke-muted)]">{ins.courseName}{ins.instructorNumber?` · No.${ins.instructorNumber}`:''}</p></div></div><div className="mt-2 flex flex-wrap gap-1"><Badge on={ins.certified} label={ins.certified?'認定済み':'未認定'}/><Badge on={ins.registrationStatus==='registered'} label={registration(ins.registrationStatus)}/><Badge on={ins.activities.some(item=>item.licenseEffective)} label={ins.activities.some(item=>item.licenseEffective)?'講師ライセンス有効':'講師ライセンスを確認'}/></div><p className="mt-2 text-sm text-[var(--mikke-primary)]">講師情報を確認 →</p></Link></li>)}</ul>}
 <section className="border-t border-[var(--mikke-line)] pt-5"><h3 className="mb-3 text-base font-bold">講師管理の設定</h3><p className="text-xs text-[var(--mikke-muted)]">更新制度・自動採番の設定変更は接続準備中です。既存の設定は保持しています。</p></section>
 </div>;
}
