'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {useAcademy2Headquarters} from './HeadquartersBoundary';
import {getHeadquartersHome,monthCells,shiftMonth,tokyoDate,type HeadquartersHomeData} from '@/lib/academy2/headquarters-home';
import {toAcademyContextHref} from '@/lib/academy/access-context';
import styles from './headquarters-home.module.css';
const c=(...names:(string|false|undefined)[])=>names.filter(Boolean).map(name=>styles[name as string]).join(' ');
const dateTime=(value:string)=>new Intl.DateTimeFormat('ja-JP',{timeZone:'Asia/Tokyo',month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(new Date(value));
const accessLabels:Record<string,string>={active:'Academy利用中',trialing:'体験利用中',expired:'利用期間終了',cancelled:'契約終了',past_due:'支払い確認中'};
function Title({en,jp,href}:{en:string;jp:string;href?:string}){return <div className={c('titlebar')}><div><div className={c('en')}>{en}</div><div className={c('jp')}>{jp}</div></div>{href&&<Link className={c('title-more')} href={href}>もっと見る →</Link>}</div>;}
export function HeadquartersHome(){
 const hq=useAcademy2Headquarters();const today=tokyoDate(new Date());
 const [month,setMonth]=useState(today.slice(0,7)),[day,setDay]=useState(today),[metric,setMetric]=useState<'sales'|'applications'>('sales'),[createOpen,setCreateOpen]=useState(false);
 const [data,setData]=useState<HeadquartersHomeData|null>(null),[error,setError]=useState(''),[retry,setRetry]=useState(0);
 useEffect(()=>{if(!hq)return;let live=true;setData(null);setError('');getHeadquartersHome(hq.id,month).then(value=>{if(live){setData(value);if(!value.permissions.finance)setMetric('applications');}}).catch(cause=>{if(live)setError(cause instanceof Error?cause.message:'本部ホームを読み込めませんでした。');});return()=>{live=false;};},[hq?.id,month,retry]);
 if(!hq)return null;
 const href=(path:string)=>toAcademyContextHref(path,hq.id,'manage');
 if(!data)return <main className={c('wrap')}><div className={c('identity')}><div className={c('my')}>MY ACADEMY</div><div className={c('school')}>{hq.name}</div></div>{error?<section className={c('error')} role="alert"><h1>本部ホームを読み込めませんでした</h1><p>{error}</p><p>取得できない情報を0件・0円として表示していません。</p><button className={c('retry')} onClick={()=>setRetry(n=>n+1)}>もう一度読み込む</button></section>:<p role="status" className={c('empty')}>本部ホームを読み込んでいます…</p>}</main>;
 const apps=data.applications??[];const events=(data.events??[]).filter(e=>e.status!=='cancelled');
 const todo=[{key:'pay',icon:'¥',label:'入金確認',actions:['confirm_payment','confirm_tuition'],path:'/academy/applications',show:data.permissions.finance},{key:'date',icon:'◷',label:'日程待ち',actions:['confirm_schedule'],path:'/academy/applications',show:true},{key:'ship',icon:'▰',label:'発送準備',actions:['set_shipping_destination','record_shipping','ship_kit'],path:'/academy/applications?tab=koushi',show:true},{key:'cert',icon:'✓',label:'認定確認',actions:['confirm_certification','review_outcome'],path:'/academy/certifications',show:true}];
 const selected=events.filter(e=>e.starts_at&&tokyoDate(e.starts_at)===day);
 const upcoming=events.filter(e=>e.starts_at&&new Date(e.starts_at).getTime()>=new Date(data.observedAt).getTime()).sort((a,b)=>a.starts_at!.localeCompare(b.starts_at!)).slice(0,3);
 const pending=events.filter(e=>!e.starts_at).length;
 const monthly=data.monthly??[];const values=monthly.map(row=>metric==='sales'?row.salesYen:row.applications);const max=Math.max(1,...values.filter((v):v is number=>v!==null));const current=values.at(-1);
 const display=(v:number)=>metric==='sales'?`¥${v.toLocaleString('ja-JP')}`:`${v.toLocaleString('ja-JP')}件`;
 const moveMonth=(amount:number)=>{const next=shiftMonth(month,amount);setMonth(next);setDay(next+'-01');};
 const steps=[{key:'course' as const,title:'講座をつくる',path:'/academy/courses/new',allowed:data.permissions.editCourses},{key:'plan' as const,title:'販売をつくる',path:'/academy/offerings/new',allowed:data.permissions.editPages},{key:'page' as const,title:'ページを整える',path:'/academy/front',allowed:data.permissions.editPages},{key:'published' as const,title:'公開する',path:'/academy/offerings',allowed:data.permissions.editPages}];
 const eventView=(event:typeof events[number])=><><div className={c('event-date')}>{event.starts_at?dateTime(event.starts_at):'日程未定'}</div><div className={c('event-name')}>{event.title}</div><div className={c('event-meta')}>{event.format==='online'?'オンライン':'対面'}・{event.application_count} / {event.capacity??'定員未設定'}{event.capacity!==null?'名':''}</div></>;
 return <main className={c('wrap')}>
  <div className={c('identity')}><div className={c('my')}>MY ACADEMY</div><div className={c('school')}>{data.name}</div></div>
  <div className={c('status-row')}><div className={c('status-info')}><div className={c('academy-meta')}><span className={c('status')}>{data.accessStatus?accessLabels[data.accessStatus]??'利用状態を確認':'利用状態の記録なし'}</span>{data.instructorCount!==null&&<span>登録講師 <b>{data.instructorCount}名</b></span>}<span>公開販売ページ <b>{data.publishedPageCount}</b></span>{(hq.role==='owner'||hq.role==='administrator')&&<Link href={href('/academy/settings')}>契約・料金を確認 →</Link>}</div></div><div className={c('status-alert')}>{data.notices.length?data.notices.map(notice=><section key={notice.id} className={c('alert-panel')}><div><strong>{notice.title}</strong><small>{notice.detail}</small></div><Link href={href(notice.path)}>確認する →</Link></section>):<div className={c('status-clear')}>{hq.role==='owner'||hq.role==='administrator'?'利用に影響するお知らせはありません。':'利用状態のお知らせは本部担当が確認します。'}</div>}</div></div>
  <section className={c('hero',!data.heroImageUrl&&'hero-empty')} style={data.heroImageUrl?{backgroundImage:`url(${JSON.stringify(data.heroImageUrl)})`}:undefined} aria-label="本部のHERO画像">{!data.heroImageUrl&&<span>{data.name}</span>}<div className={c('logo')}>{data.logoUrl?<img src={data.logoUrl} alt={`${data.name}のロゴ`}/>:data.name.slice(0,4)}</div>{data.publicHomepagePath&&<div className={c('hero-actions')}><Link className={c('hero-action')} href={data.publicHomepagePath}>ホームページを見る ↗</Link></div>}</section><div className={c('after-hero')}/>
  <div className={c('context-panels')}><section className={c('get-started')}><div className={c('context-kicker')}>GET STARTED</div><div className={c('context-jp')}>はじめてのAcademy</div><div className={c('start-progress')}>{steps.map((step,i)=>{const body=<><span className={c('n')}>STEP {String(i+1).padStart(2,'0')}</span><strong>{step.title}</strong></>;return step.allowed?<Link key={step.key} className={c('start-step',data.setup[step.key]&&'done')} href={href(step.path)} aria-label={`${step.title}${data.setup[step.key]?'（設定済み）':''}`}>{body}</Link>:<div key={step.key} className={c('start-step',data.setup[step.key]&&'done')} aria-disabled="true" title="本部の編集担当が設定します">{body}</div>;})}</div></section></div>
  <div className={c('dashboard')}><div className={c('left')}>
   <section className={c('block')}><Title en="TO DO" jp="やること" href={data.permissions.operations?href('/academy/applications'):undefined}/><div className={c('card','todo-card')}>{data.permissions.operations?todo.filter(t=>t.show).map(t=><Link key={t.key} className={c('todo-item')} href={href(t.path)}><span className={c('todo-left')}><span className={c('icon',t.key)}>{t.icon}</span>{t.label}</span><span className={c('count')}>{apps.filter(a=>t.actions.includes(a.nextAction??'')).length}<small>件</small></span></Link>):<p className={c('empty')}>申込・日程・発送・認定の対応は受講運営担当が確認します。</p>}</div></section>
   <section className={c('section','grid2')}><div className={c('block')}><Title en="NEW APPLICATIONS" jp="最近の申込" href={data.permissions.operations?href('/academy/applications'):undefined}/><div className={c('card','list-card')}>{data.permissions.operations?apps.length?apps.slice(0,3).map(a=><Link className={c('row','row-link')} key={a.applicationId} href={href('/academy/applications/'+a.applicationId)}><div><div className={c('name')}>{a.applicantName}</div><div className={c('meta')}>{a.planTitle}</div></div><span className={c('badge',a.completedAt?'ok':a.nextAction==='confirm_schedule'?'info':undefined)}>{a.statusLabel}</span></Link>):<p className={c('empty')}>まだ申込はありません。</p>:<p className={c('empty')}>この役割では申込情報を表示しません。</p>}</div></div><div className={c('block')}><Title en="UP NEXT" jp="もうすぐ対応"/><div className={c('card','soon')}>{data.upcoming.length?data.upcoming.slice(0,3).map(item=><Link key={item.id} className={c('row','row-link')} href={href(item.path)}><div><div className={c('name')}>{item.title}</div><div className={c('meta')}>{item.detail}</div></div>→</Link>):<p className={c('empty')}>{hq.role==='course_editor'?'対応予定は本部の運営担当が確認します。':'現在、確認が必要な予定はありません。'}</p>}</div></div></section>
   <section className={c('block')}><Title en="SALES" jp="売上"/><div className={c('card','sales')}><div className={c('sales-inner')}>{data.permissions.finance||data.permissions.operations?<><div className={c('sales-head')}><div><span>{month===today.slice(0,7)?'今月':Number(month.slice(5))+'月'}の{metric==='sales'?'売上':'申込数'}</span><br/><strong>{current!==null&&current!==undefined?display(current):'権限外'}</strong></div><div className={c('metric-tabs')}>{data.permissions.finance&&<button type="button" className={c('metric-tab',metric==='sales'&&'active')} aria-pressed={metric==='sales'} onClick={()=>setMetric('sales')}>売上</button>}{data.permissions.operations&&<button type="button" className={c('metric-tab',metric==='applications'&&'active')} aria-pressed={metric==='applications'} onClick={()=>setMetric('applications')}>申込数</button>}</div></div><div className={c('chart')} aria-label="月別の集計">{monthly.map((row,i)=><button type="button" key={row.month} className={c('bar')} style={{height:values[i]!==null?`${values[i]!/max*88}%`:'0%'}} aria-label={`${row.month} ${values[i]!==null?display(values[i]!):'権限外'}`}><span className={c('bar-tip')}>{Number(row.month.slice(5))}月 {values[i]!==null?display(values[i]!):'権限外'}</span></button>)}</div><div className={c('months')}>{monthly.map(row=><span key={row.month}>{Number(row.month.slice(5))}月</span>)}</div><p className={c('metric-note')}>{metric==='sales'?'Academy 2.0の本部販売分。入金確認日で集計した受講料です。講師自身の売上や未入金分は含みません。':'Academy 2.0で管理する本部販売・講師販売の申込を、申込日で集計しています。'}</p></>:<p className={c('empty')}>売上・申込数は担当する役割で確認できます。</p>}</div></div></section>
  </div><aside className={c('right')}><section className={c('block','schedule')}><Title en="CALENDAR" jp="開催カレンダー" href={data.permissions.operations?href('/academy/classes'):undefined}/><div className={c('card','calendar')}><div className={c('cal-inner')}><div className={c('cal-head')}><strong>{month.slice(0,4)}年 {Number(month.slice(5))}月</strong><div><button type="button" aria-label="前の月" onClick={()=>moveMonth(-1)}>‹</button><button type="button" aria-label="次の月" onClick={()=>moveMonth(1)}>›</button></div></div><div className={c('week')}>{['月','火','水','木','金','土','日'].map(w=><span key={w}>{w}</span>)}</div><div className={c('days')}>{monthCells(month).map(d=><button type="button" key={d} aria-label={d} aria-pressed={d===day} className={c('day',d===day&&'active',!d.startsWith(month)&&'outside',events.some(e=>e.starts_at&&tokyoDate(e.starts_at)===d)&&'event')} onClick={()=>setDay(d)}>{Number(d.slice(-2))}</button>)}</div></div><div className={c('events')}><div className={c('selected-event')}><div className={c('selected-label')}>選択した日の予定</div>{data.permissions.operations?selected.length?selected.map(e=><Link key={e.id} className={c('event-link')} href={href('/academy/classes/'+e.id)}>{eventView(e)}</Link>):<p className={c('event-meta')}>{day}の開催予定はありません。</p>:<p className={c('event-meta')}>開催情報は受講運営担当が確認します。</p>}</div><div className={c('upcoming-divider')}><h3>これからの開催</h3>{data.permissions.operations&&<Link className={c('more-link')} href={href('/academy/classes')}>もっと見る →</Link>}</div>{upcoming.map(e=><Link key={e.id} className={c('event','event-link')} href={href('/academy/classes/'+e.id)}>{eventView(e)}</Link>)}{pending>0&&<Link className={c('event','event-link')} href={href('/academy/classes')}><div className={c('event-date')}>日程未定</div><div className={c('event-name')}>個別日程の相談</div><div className={c('event-meta')}>{pending}件の日程を確認</div></Link>}{data.permissions.operations&&!upcoming.length&&!pending&&<p className={c('empty')}>これからの開催はありません。</p>}</div></div></section></aside></div>
  <nav id="home-create-menu" className={c('quick-menu',createOpen&&'open')} aria-label="新しくつくる">{data.permissions.editCourses&&<Link href={href('/academy/courses/new')}>＋ 講座をつくる</Link>}{data.permissions.editPages&&<Link href={href('/academy/offerings/new')}>＋ 販売をつくる</Link>}{data.permissions.operations&&<Link href={href('/academy/classes/new')}>＋ 開催日追加</Link>}</nav>{(data.permissions.editCourses||data.permissions.editPages||data.permissions.operations)&&<button type="button" className={c('quick-fab')} aria-label="新しくつくる" aria-expanded={createOpen} aria-controls="home-create-menu" onClick={()=>setCreateOpen(value=>!value)}>＋</button>}
 </main>;
}



