"use client";
import {useState} from 'react';
import Link from 'next/link';
import type {InstructorApplicationSummary} from '@/lib/academy2/instructor-operations';
import styles from './instructor-application-list.module.css';
const states=['要対応','本部確認待ち','認定済み','すべて'];
const eventDate=(value:string|null)=>value&&Number.isFinite(Date.parse(value))?new Intl.DateTimeFormat('ja-JP',{timeZone:'Asia/Tokyo',month:'numeric',day:'numeric'}).format(new Date(value)):null;
function category(item:InstructorApplicationSummary){return item.certification==='certified'?'認定済み':item.completionReport==='returned'?'要対応':item.completionReport==='submitted'?'本部確認待ち':null;}
export function InstructorCompletionList({items}:{items:InstructorApplicationSummary[]}){const [search,setSearch]=useState('');const [filter,setFilter]=useState('要対応');const reported=items.filter(item=>category(item)!==null);const visible=reported.filter(item=>(filter==='すべて'||category(item)===filter)&&`${item.learnerName} ${item.planTitle}`.toLocaleLowerCase().includes(search.toLocaleLowerCase()));return <section className={`${styles.wrap} ${styles.completionWrap}`}><div className={styles.titlebar}><div className={styles.en}>COMPLETION &amp; CERTIFICATION</div><h1>修了・認定</h1></div><div className={styles.headbox}><p>申込詳細から送信した修了報告と、本部の確認・認定状況をまとめて確認します。ここで同じ内容をもう一度入力する必要はありません。</p></div><div className={styles.summary}>{states.slice(0,3).map(state=><button type="button" key={state} className={styles.summaryCard} onClick={()=>setFilter(state)}><b>{state}</b><strong>{reported.filter(item=>category(item)===state).length}</strong><small>件</small></button>)}</div><div className={styles.tools}><input className={styles.search} aria-label="名前・講座名で検索" placeholder="名前・講座名で検索" value={search} onChange={e=>setSearch(e.target.value)}/>{states.map(state=><button type="button" className={`${styles.filter} ${filter===state?styles.on:''}`} aria-pressed={filter===state} key={state} onClick={()=>setFilter(state)}>{state}</button>)}</div><div className={styles.list}>{visible.map(item=><Link key={item.applicationId} className={styles.application} href={`/academy/instructor-applications/${item.applicationId}`}><span className={styles.avatar}>{Array.from(item.learnerName??'申')[0]}</span><div className={styles.content}><h2>{item.learnerName}</h2><div className={styles.meta}><span>{item.planTitle}</span><span>{eventDate(item.scheduleStartsAt)?`${eventDate(item.scheduleStartsAt)} 開催済み`:'開催日 未確認'}</span><span>{item.certification==='certified'?'認定日 未確認':'修了報告日 未確認'}</span></div></div><div className={styles.right}><span className={`${styles.status} ${category(item)==='認定済み'?styles.statusGreen:category(item)==='本部確認待ち'?styles.statusYellow:styles.statusOrange}`}>{category(item)==='要対応'?'差戻し':category(item)}</span><div className={styles.next}>{category(item)==='要対応'?'申込詳細で確認':category(item)==='認定済み'?'認定完了':'報告日 未確認'}</div></div></Link>)}</div>{!visible.length&&<p className={styles.empty}>該当する修了報告はありません。</p>}<div className={styles.notice}><strong>修了報告は「申込詳細」から行います</strong>この一覧は、送信後の本部確認・認定状況を見るための画面です。差戻しがある場合は該当する申込詳細へ戻って対応します。</div></section>;}
