'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {EventKitDestination} from './EventKitDestination';
import {CalendarCheck} from 'lucide-react';
import {assignmentRequests,assignmentLabels,respondAssignment,myAssignmentPreferences,type AssignmentRequest,type AssignmentPreference} from '@/lib/academy2/instructor-assignments';
const date=(v:string|null)=>v?new Date(v).toLocaleString('ja-JP'):'日程相談';
/** Uses the existing portal/class-requests card structure and density. */
export function InstructorAssignmentRequests(){
 const [requests,setRequests]=useState<AssignmentRequest[]>([]),[preferences,setPreferences]=useState<AssignmentPreference[]>([]),[notes,setNotes]=useState<Record<string,string>>({}),[busy,setBusy]=useState(''),[loading,setLoading]=useState(true),[message,setMessage]=useState('');
 const command=useRef<{body:string;id:string}|null>(null);
 const load=useCallback(async()=>{setLoading(true);try{const [r,p]=await Promise.all([assignmentRequests(),myAssignmentPreferences()]);setRequests(r);setPreferences(p);}catch(e){setMessage(e instanceof Error?e.message:'担当依頼を読み込めませんでした。');}finally{setLoading(false);}},[]);
 useEffect(()=>{void load();},[load]);
 async function respond(r:AssignmentRequest,response:'accepted'|'declined'|'consulting'){if(busy)return;setBusy(r.id);setMessage('');const body=JSON.stringify({id:r.id,revision:r.revision,response,note:notes[r.id]??''});if(command.current?.body!==body)command.current={body,id:crypto.randomUUID()};try{setRequests(await respondAssignment(r,command.current.id,response,notes[r.id]??''));command.current=null;setMessage(response==='accepted'?'担当依頼を承諾しました。':response==='declined'?'担当依頼を辞退しました。':'相談内容を送りました。');}catch(e){setMessage(e instanceof Error?e.message:'回答を保存できませんでした。');}finally{setBusy('');}}
 async function preference(p:AssignmentPreference,value:boolean){setBusy(p.id);setMessage('');try{setPreferences(await myAssignmentPreferences(p.id,value));setMessage('依頼受付の設定を保存しました。');}catch(e){setMessage(e instanceof Error?e.message:'設定を保存できませんでした。');}finally{setBusy('');}}
 return <div className="mx-auto max-w-3xl space-y-5"><section className="rounded-2xl border border-[var(--mikke-line)] bg-white p-5"><div className="flex items-start gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-full bg-[var(--mikke-accent-soft)] text-[var(--mikke-accent)]"><CalendarCheck size={19}/></span><div><h2 className="text-base font-bold text-[var(--mikke-text)]">本部からの担当依頼</h2><p className="mt-1 text-sm text-[var(--mikke-muted)]">依頼内容と講座担当料を確認し、承諾・相談・辞退で回答します。</p></div></div>{message?<p role="status" className="mt-4 text-sm font-bold text-[var(--mikke-accent-strong)]">{message}</p>:null}<button className="mt-3 text-sm underline" type="button" onClick={()=>void load()} disabled={!!busy}>再読み込み</button></section>
 {loading?<p role="status" className="py-12 text-center text-sm text-[var(--mikke-muted)]">担当依頼を確認しています…</p>:requests.length?requests.map(r=><section key={r.id} className="rounded-2xl border border-[var(--mikke-line)] bg-white p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="mt-1 text-base font-bold text-[var(--mikke-text)]">{r.event.title}</h3><p className="mt-2 text-sm text-[var(--mikke-muted)]">{date(r.event.startsAt)}{r.event.endsAt?` 〜 ${date(r.event.endsAt)}`:''}</p><p className="mt-1 text-xs text-[var(--mikke-muted)]">{r.event.format==='online'?'オンライン':'対面'}{r.event.venue?` ・ ${r.event.venue}`:''}</p></div><span className="rounded-full bg-[var(--mikke-surface-soft)] px-3 py-1 text-xs font-bold text-[var(--mikke-text-soft)]">{assignmentLabels[r.status]}</span></div><div className="mt-4 rounded-xl bg-[var(--mikke-surface-soft)] p-3 text-sm text-[var(--mikke-text-soft)]"><p>{r.requestNote||'依頼メモはありません。'}</p>{r.feeYen!==null?<p>講座担当料 ¥{r.feeYen.toLocaleString('ja-JP')}</p>:null}</div>{['requested','consulting'].includes(r.status)?<div className="mt-4 space-y-2"><textarea value={notes[r.id]??''} maxLength={2000} onChange={e=>setNotes(v=>({...v,[r.id]:e.target.value}))} placeholder="本部への回答メモ（任意）" rows={3} className="w-full rounded-xl border border-[var(--mikke-line)] bg-white px-3 py-2 text-sm text-[var(--mikke-text)]"/><div className="grid grid-cols-3 gap-2">{(['declined','consulting','accepted'] as const).map(response=><button type="button" key={response} disabled={!!busy||(response==='accepted'&&!r.canAccept)} onClick={()=>void respond(r,response)} className={`rounded-xl border border-[var(--mikke-line)] px-4 py-2 text-sm font-bold disabled:opacity-50 ${response==='accepted'?'bg-[var(--mikke-primary)] text-white':'bg-white text-[var(--mikke-text-soft)]'}`}>{response==='accepted'?'承諾する':response==='declined'?'辞退する':'相談する'}</button>)}</div>{!r.canAccept?<p className="text-xs text-[var(--mikke-muted)]">承諾には有効な講師契約・権限・カード決済登録が必要です。</p>:null}</div>:null}{r.status==='accepted'?<EventKitDestination requestId={r.id}/>:null}{r.responseNote?<p className="mt-4 text-sm text-[var(--mikke-text-soft)]">回答メモ：{r.responseNote}</p>:null}</section>):<p className="rounded-2xl border border-[var(--mikke-line)] bg-white p-6 text-sm text-[var(--mikke-muted)]">現在、担当依頼はありません。</p>}
 <section className="rounded-2xl border border-[var(--mikke-line)] bg-white p-5"><h3 className="text-base font-bold">依頼受付の設定</h3>{preferences.map(p=><div key={p.id} className="mt-3 text-sm"><p>{p.courseName}</p><label><input type="checkbox" checked={p.acceptRequests} disabled={!!busy} onChange={e=>void preference(p,e.target.checked)}/> 本部から講座依頼を受ける</label><p className="text-xs text-[var(--mikke-muted)]">カード決済登録：{p.connectReady?'確認済み':'未確認（本部の担当候補には表示されません）'}</p></div>)}</section>
 </div>;
}
