"use client";
import {useState} from 'react';
import type {InstructorApplicationSummary} from '@/lib/academy2/instructor-operations';
import styles from './instructor-application-list.module.css';
const filters=['日程相談','開催確定','本日','終了','すべて'];
const hasEnded=(group:InstructorApplicationSummary[])=>group.every(row=>row.completionReport==='submitted'||row.completionReport==='accepted'||row.certification==='certified');
const date=(value:string)=>new Intl.DateTimeFormat('ja-JP',{timeZone:'Asia/Tokyo',month:'numeric',day:'numeric'}).format(new Date(value));
export function InstructorEventList({items}:{items:InstructorApplicationSummary[]}){const [search,setSearch]=useState('');const [filter,setFilter]=useState('すべて');const dayKey=(value:string)=>new Intl.DateTimeFormat('ja-JP',{timeZone:'Asia/Tokyo',year:'numeric',month:'numeric',day:'numeric'}).format(new Date(value));const today=dayKey(new Date().toISOString());const groups=new Map<string,InstructorApplicationSummary[]>();for(const item of items){const key=item.eventId?`${item.headquartersId}:${item.eventId}`:`application:${item.applicationId}`;groups.set(key,[...(groups.get(key)??[]),item]);}const visible=[...groups.values()].filter(group=>{const item=group[0];const ended=hasEnded(group);return `${item.planTitle} ${item.headquartersName}`.toLocaleLowerCase().includes(search.toLocaleLowerCase())&&(filter==='すべて'||filter==='終了'&&ended||filter==='日程相談'&&!item.scheduleStartsAt||filter==='開催確定'&&!!item.scheduleStartsAt&&!ended||filter==='本日'&&!!item.scheduleStartsAt&&dayKey(item.scheduleStartsAt)===today);});return <section className={`${styles.wrap} ${styles.eventsWrap}`}><div className={styles.titlebar}><div className={styles.en}>EVENTS</div><h1>開催</h1></div><div className={`${styles.headbox} ${styles.eventHead}`}><p>開催日程を確認します。日程の調整、出欠・修了報告は対象の申込詳細で進めます。</p><button type="button" className={styles.create} disabled>開催を追加（準備中）</button></div><div className={styles.tools}><input className={styles.search} aria-label="講座名・本部名で検索" placeholder="講座名・本部名で検索" value={search} onChange={e=>setSearch(e.target.value)}/>{filters.map(value=><button type="button" key={value} className={`${styles.filter} ${filter===value?styles.on:''}`} aria-pressed={filter===value} onClick={()=>setFilter(value)}>{value}</button>)}</div><div className={styles.list}>{visible.map(group=>{const item=group[0];return <article className={styles.application} key={item.eventId??item.applicationId}><div className={styles.avatar}>{item.scheduleStartsAt?date(item.scheduleStartsAt):'相談'}</div><div className={styles.content}><h2>{item.planTitle}</h2><div className={styles.meta}><span>{item.scheduleStartsAt?new Intl.DateTimeFormat('ja-JP',{timeZone:'Asia/Tokyo',month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(item.scheduleStartsAt)):'申込後に日程相談'}</span><span>{item.format==='online'?'オンライン':item.format==='in_person'?'対面':''}</span><span>{item.headquartersName}</span></div><div className={styles.eventApplications}>{group.map(row=><a key={row.applicationId} href={`/academy/instructor-applications/${row.applicationId}`}>{row.learnerName}：申込詳細へ</a>)}</div></div><div className={styles.right}><span className={`${styles.status} ${hasEnded(group)?styles.statusGray:item.scheduleStartsAt?styles.statusGreen:styles.statusYellow}`}>{hasEnded(group)?'終了':item.scheduleStartsAt?'開催確定':'日程相談'}</span><div className={styles.next}>申込 {group.length}名</div></div></article>;})}</div>{!visible.length&&<p className={styles.empty}>該当する開催はありません。</p>}</section>;}

