'use client';
import {useEffect,useRef,useState,type CSSProperties,type ReactNode} from 'react';
import {createPortal} from 'react-dom';
import {useAuth} from '@/components/AuthGate';
import type {MikkeMediaAsset} from '@/lib/media/types';
import {uploadMikkeMediaImage,listMikkeMediaAssets} from '@/lib/media/client';
import {AcademyContentRenderer} from '@/components/academy/AcademyContentRenderer';
import {MikkeRichWriting} from '@/components/mikkeos/content/MikkeRichWriting';
import {academyContent,replaceAcademyContent} from '@/lib/academy/content-adapter';
import {createMikkeContentBlock} from '@/lib/mikkeos/content/blocks.js';
import type {MikkeContentBlock,MikkeContentBlockType} from '@/lib/mikkeos/content/types';
import type {LpBlock} from '@/components/mikkeos/page-builder/lp-design';
import type {AcademyLesson} from '@/lib/academy/lesson-content';
import type {AcademyPageBlock} from '@/types/database';
import styles from './lesson-note-editor.module.css';

const choices=[['heading','見出し'],['image','画像'],['gallery','画像グリッド'],['video','動画'],['link','リンク']] as const;
const names:Partial<Record<MikkeContentBlockType,string>>={paragraph:'文章',heading:'見出し',image:'画像',gallery:'画像グリッド',video:'動画',link:'リンク'};
function label(block:MikkeContentBlock){return block.title||block.text?.slice(0,32)||block.caption||names[block.type]||'教材';}
/** Audience-neutral content editor. The caller owns access, draft persistence and publication. */
export function LessonNoteEditor({courseTitle,title,lessonId,lessons,blocks,onChange,onSave,onBack,onLesson,onAddLesson,onMoveLesson,onTitle,saving,dirty,error,navigation,backLabel='← 講座編集へ',outlineLabel='レッスン・教材',savedMessage='保存済みです。'}:{backLabel?:string;outlineLabel?:string;savedMessage?:string;navigation?:ReactNode;courseTitle:string;title:string;lessonId:string;lessons:AcademyLesson[];blocks:AcademyPageBlock[];onChange:(blocks:AcademyPageBlock[])=>void;onSave:()=>void;onBack:()=>void;onLesson:(id:string)=>void;onAddLesson:()=>void;onMoveLesson:(index:number,direction:-1|1)=>void;onTitle:(title:string)=>void;saving:boolean;dirty:boolean;error:string}){
 const root=useRef<HTMLElement>(null),header=useRef<HTMLElement>(null);
 useEffect(()=>{if(!header.current)return;const resize=()=>root.current?.style.setProperty('--editor-panel-top',`${62+Math.ceil(header.current!.getBoundingClientRect().height)+12}px`);const observer=new ResizeObserver(resize);observer.observe(header.current);resize();return()=>observer.disconnect();},[]);
 const items=academyContent(blocks) as LpBlock[];
 const latestItems=useRef(items);latestItems.current=items;
 const [uploading,setUploading]=useState(false);const busy=saving||uploading;
 useEffect(()=>{if(!uploading)return;const warn=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue='';};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[uploading]);
 const [selected,setSelected]=useState<string|null>(null),[drawer,setDrawer]=useState(false),[sheet,setSheet]=useState(false),[insert,setInsert]=useState<number|null>(null);
 const leftPanel=useRef<HTMLElement>(null),drawerPanel=useRef<HTMLElement>(null);
 useEffect(()=>{const panel=drawer?drawerPanel.current:leftPanel.current;if(!panel)return;const active=panel.querySelector<HTMLElement>('[aria-current=page]');if(active)panel.scrollTop+=active.getBoundingClientRect().top-panel.getBoundingClientRect().top-16;},[lessonId,drawer]);
 useEffect(()=>{const close=(e:KeyboardEvent)=>{if(e.key==='Escape'){setDrawer(false);setSheet(false);}};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close);},[]);
 const canvas=useRef<HTMLDivElement>(null),dialog=useRef<HTMLDialogElement>(null),insertFocus=useRef<string|null>(null),blank=useRef(createMikkeContentBlock('paragraph') as LpBlock);
 const selectedIndex=items.findIndex(b=>b.id===selected),current=items[selectedIndex];
 // A virtual last paragraph is only persisted after typing or inserting content.
 const tail=items.at(-1)?.type==='paragraph'&&!items.at(-1)?.text?.trim()?null:blank.current;
 const visible=tail?[...items,tail]:items;
 useEffect(()=>{if(insert!==null)dialog.current?.showModal();else{dialog.current?.close();const id=insertFocus.current;insertFocus.current=null;if(id)requestAnimationFrame(()=>{setSelected(id);const media=canvas.current?.querySelector<HTMLElement>(`[data-block-id="${id}"] [role=button]`);if(media&&window.innerWidth<=820){canvas.current?.closest('main')?.querySelector<HTMLElement>('[aria-label="要素の設定"] button')?.focus();}else if(media){media.focus();media.scrollIntoView({block:'nearest'});}else focus(id);});}},[insert]);
 function change(next:MikkeContentBlock[]){onChange(replaceAcademyContent(blocks,next));}
 function update(index:number,next:LpBlock){change(index===items.length?[...items,next]:items.map((b,i)=>i===index?next:b));}
 function focus(id:string){requestAnimationFrame(()=>{const el=canvas.current?.querySelector<HTMLElement>(`[data-block-id="${id}"] [contenteditable]`);el?.focus();el?.scrollIntoView({block:'nearest'});});}
 function pick(block:LpBlock,settings=false){setSelected(block.id);if(settings)setSheet(true);}
 function add(type:MikkeContentBlockType){if(insert===null)return;const next={...createMikkeContentBlock(type),...(type==='link'?{lessonLinkDisplay:'card' as const}:{}),...(type==='video'?{lessonVideoPreview:true}:{})} as LpBlock,index=insert;const replacing=items[index]?.type==='paragraph'&&!items[index].text?.trim();change([...items.slice(0,index),next,...items.slice(index+(replacing?1:0))]);insertFocus.current=next.id;setInsert(null);setSelected(next.id);setSheet(type!=='heading');}
 function paste(index:number,url:string){const type=/\.(png|jpe?g|gif|webp|svg)(?:[?#]|$)/i.test(url)?'image':/(?:youtube\.com|youtu\.be|vimeo\.com)\//i.test(url)||/\.(mp4|webm|ogg)(?:[?#]|$)/i.test(url)?'video':'link';const next={...createMikkeContentBlock(type),...(type==='image'?{imageUrl:url}:{url}),...(type==='link'?{lessonLinkDisplay:'card' as const}:{}),...(type==='video'?{lessonVideoPreview:true}:{})} as LpBlock;update(index,next);setSelected(next.id);setSheet(false);blank.current=createMikkeContentBlock('paragraph') as LpBlock;}
 function move(index:number,direction:number){const target=index+direction;if(target<0||target>=items.length)return;const next=[...items];[next[index],next[target]]=[next[target],next[index]];change(next);}
 const patch=(delta:Partial<LpBlock>)=>{if(current)update(selectedIndex,{...current,...delta});};
 const media=(delta:NonNullable<NonNullable<LpBlock['lp']>['media']>)=>patch({lp:{...current.lp,media:{...current.lp?.media,...delta}}});
 function jump(id:string){setSelected(id);setDrawer(false);requestAnimationFrame(()=>canvas.current?.querySelector<HTMLElement>(`[data-block-id="${id}"]`)?.scrollIntoView({block:'center'}));}
 const outline=<><h2>{outlineLabel}</h2><p className={styles.muted}>{courseTitle}</p>{lessons.map((lesson,i)=><section key={lesson.id} className={lesson.id===lessonId?styles.activeLesson:styles.lesson}><div className={styles.lessonHeading}><button type="button" className={styles.lessonTitle} aria-current={lesson.id===lessonId?'page':undefined} onClick={()=>{if(lesson.id===lessonId){setSelected(null);setDrawer(false);}else onLesson(lesson.id);}}><span className={styles.lessonNumber}>{String(i+1).padStart(2,'0')}</span>{' '}<span>{lesson.title}</span></button><details className={styles.lessonMoves}><summary aria-label={`${lesson.title}の並び替え`}>…</summary><div><button type="button" aria-label={`${lesson.title}を上へ`} disabled={i===0||busy} onClick={()=>onMoveLesson(i,-1)}>上へ</button><button type="button" aria-label={`${lesson.title}を下へ`} disabled={i===lessons.length-1||busy} onClick={()=>onMoveLesson(i,1)}>下へ</button></div></details></div>{(lesson.id===lessonId?items:academyContent(lesson.blocks)).map((b,index)=><button type="button" key={b.id} className={styles.outlineItem} aria-current={lesson.id===lessonId&&selected===b.id?'location':undefined} onClick={()=>lesson.id===lessonId?jump(b.id):onLesson(lesson.id)}>{index+1}. {label(b)}</button>)}{lesson.id===lessonId&&<button className={styles.outlineAdd} type="button" onClick={()=>{setDrawer(false);setInsert(items.length);}}>＋ 教材を追加</button>}</section>)}<button className={styles.outlineAdd} type="button" disabled={busy} onClick={onAddLesson}>＋ レッスンを追加</button></>;
 const settings=<><h2>{current?`${names[current.type]||'教材'}の設定`:'教材の基本情報'}</h2>{!current?<><label>レッスン名<input value={title} onChange={e=>onTitle(e.target.value)}/></label><p className={styles.muted}>本文は中央で直接入力できます。画像などを選ぶと設定がここに表示されます。</p><p className={styles.muted}>下書き保存です。公開中の教材は変更しません。</p></>:<>
 {(current.type==='heading'||current.type==='paragraph')&&<><label>配置<select value={current.align??'left'} onChange={e=>patch({align:e.target.value as LpBlock['align']})}><option value="left">左寄せ</option><option value="center">中央寄せ</option></select></label>{current.type==='heading'&&<label>見出しの大きさ<select value={current.lp?.desktop?.size??24} onChange={e=>{const size=Number(e.target.value);patch({level:size===24?2:3,lp:{...current.lp,desktop:{...current.lp?.desktop,size},mobile:{...current.lp?.mobile,size}}});}}><option value={24}>大</option><option value={22}>中</option><option value={18}>小</option></select></label>}</>}
 {current.type==='image'&&<><EditorImagePicker onBusyChange={setUploading} currentUrl={current.imageUrl} onUploaded={imageUrl=>change(latestItems.current.map(item=>item.id===current.id?{...item,imageUrl}:item))}/><label>画像URL<input value={current.imageUrl??''} onChange={e=>patch({imageUrl:e.target.value})}/></label><label>キャプション<input value={current.caption??''} onChange={e=>patch({caption:e.target.value})}/></label><label>代替テキスト<input value={current.alt??''} onChange={e=>patch({alt:e.target.value})}/></label><label>画像の幅<select value={current.lp?.media?.width??100} onChange={e=>media({width:Number(e.target.value)})}><option value={100}>100%</option><option value={75}>75%</option><option value={50}>50%</option></select></label><label>画像の配置<select value={current.lp?.media?.align??'center'} onChange={e=>media({align:e.target.value as 'left'|'center'|'right'})}><option value="left">左寄せ</option><option value="center">中央寄せ</option><option value="right">右寄せ</option></select></label></>}
 {(current.type==='link'||current.type==='video')&&<><label>{current.type==='video'?'動画URL':'リンクURL'}<input value={current.url??''} onChange={e=>patch({url:e.target.value})}/></label><label>表示名<input value={current.title??''} onChange={e=>patch({title:e.target.value})}/></label>{current.type==='link'?<><label>説明<textarea value={current.text??''} onChange={e=>patch({text:e.target.value})}/></label><label>リンクの表示<select value={current.lessonLinkDisplay??'card'} onChange={e=>patch({lessonLinkDisplay:e.target.value as 'card'|'text'})}><option value="card">カード</option><option value="text">テキスト</option></select></label></>:<><label>サムネイルURL<input value={current.imageUrl??''} onChange={e=>patch({imageUrl:e.target.value})}/></label><EditorImagePicker onBusyChange={setUploading} currentUrl={current.imageUrl} onUploaded={imageUrl=>change(latestItems.current.map(item=>item.id===current.id?{...item,imageUrl}:item))}/></>}</>}
 {current.type==='gallery'&&<><GalleryUpload onBusyChange={setUploading} onUploaded={urls=>patch({images:[...(current.images??[]),...urls.map(url=>({url,alt:''}))]})}/><label>列数<select value={current.columns??3} onChange={e=>patch({columns:Number(e.target.value) as 2|3})}><option value={2}>2列</option><option value={3}>3列</option></select></label>{(current.images??[]).map((image,i)=><fieldset key={i}><legend>画像 {i+1}</legend><EditorImagePicker onBusyChange={setUploading} currentUrl={image.url} onUploaded={url=>patch({images:current.images!.map((v,j)=>j===i?{...v,url}:v)})}/><label>画像URL<input value={image.url} onChange={e=>patch({images:current.images!.map((v,j)=>j===i?{...v,url:e.target.value}:v)})}/></label><label>キャプション<input value={image.caption??image.alt} onChange={e=>patch({images:current.images!.map((v,j)=>j===i?{...v,caption:e.target.value}:v)})}/></label><div className={styles.row}><button type="button" disabled={i===0} onClick={()=>{const next=[...current.images!];[next[i-1],next[i]]=[next[i],next[i-1]];patch({images:next});}}>上へ</button><button type="button" disabled={i===current.images!.length-1} onClick={()=>{const next=[...current.images!];[next[i+1],next[i]]=[next[i],next[i+1]];patch({images:next});}}>下へ</button><button type="button" onClick={()=>patch({images:current.images!.filter((_,j)=>j!==i)})}>削除</button></div></fieldset>)}<button type="button" onClick={()=>patch({images:[...(current.images??[]),{url:'',alt:''}]})}>画像を追加</button></>}
 {!names[current.type]&&<p className={styles.muted}>以前の形式の教材です。内容を保持して表示しています。</p>}
 </>}</>;
 return <main ref={root} className={styles.root}><header ref={header} className={styles.header}><button type="button" disabled={busy} onClick={onBack}>{backLabel}</button><p className={styles.breadcrumb}>{courseTitle} ＞ {title} ＞ {current?label(current):'教材本文'}</p><button type="button" className={styles.mobileOnly} onClick={()=>setDrawer(true)}>レッスン一覧</button><button type="button" className={styles.save} disabled={busy} onClick={onSave}>{saving?'保存中…':'保存'}</button></header>{navigation&&<fieldset disabled={busy} style={{border:0,padding:0,margin:0}}>{navigation}</fieldset>}{error&&<p role="alert" className={styles.error}>{error}</p>}<p role="status" className={styles.status}>{saving?'保存中…':dirty?'未保存の変更があります。':savedMessage}</p>
 <div className={styles.columns}><aside ref={leftPanel} className={styles.left} aria-label="レッスン構成"><fieldset disabled={busy}>{outline}</fieldset></aside><div ref={canvas} className={styles.canvas} aria-label="教材本文" inert={busy}><h1>{title}</h1>{visible.map((block,index)=><div key={block.id}><div className={styles.insertion}><button type="button" aria-label={`ブロック${index+1}の前に追加`} onMouseDown={e=>e.preventDefault()} onClick={()=>setInsert(index)}>＋</button></div><article data-block-id={block.id} data-selected={selected===block.id} className={styles.block} style={{'--heading-size':`${block.lp?.desktop?.size??(block.level===3?20:24)}px`} as CSSProperties} onFocusCapture={()=>pick(block)}>
 {(block.type==='paragraph'||block.type==='heading')?<><div className={styles.writing}><MikkeRichWriting lineBreakOnEnter allowHttpUrlPaste selectionOnlyToolbar block={block} placeholder={items.length?'続けて教材を書きます…':'ここから教材を書き始めます…'} onChange={next=>{update(index,next);if(index===items.length)blank.current=createMikkeContentBlock('paragraph') as LpBlock;}} onUrlPaste={url=>paste(index,url)}/></div>{!block.text?.trim()&&<button className={styles.emptyPlus} type="button" aria-label="この空行に追加" onMouseDown={e=>e.preventDefault()} onClick={()=>setInsert(index)}>＋</button>}</>:<div className={styles.media} role="button" tabIndex={0} aria-label={`${names[block.type]||'教材'}の設定を開く`} onClick={e=>{if((e.target as Element).closest('a'))e.preventDefault();pick(block,true);}} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();pick(block,true);}}}><AcademyContentRenderer blocks={[block]}/>{block.type==='image'&&!block.imageUrl&&<p className={styles.emptyMedia}>画像を選択してください</p>}{block.type==='gallery'&&!block.images?.some(image=>image.url)&&<p className={styles.emptyMedia}>画像を追加してください</p>}</div>}
 {index<items.length&&<details className={styles.operations}><summary aria-label={`ブロック${index+1}の操作`}>…</summary><div><button type="button" onClick={()=>{pick(block,true);}}>設定</button><button type="button" disabled={index===0} onClick={()=>move(index,-1)}>上へ</button><button type="button" disabled={index===items.length-1} onClick={()=>move(index,1)}>下へ</button><button type="button" onClick={()=>change([...items.slice(0,index+1),{...structuredClone(block),id:crypto.randomUUID()},...items.slice(index+1)])}>複製</button><button type="button" onClick={()=>{change(items.filter((_,i)=>i!==index));setSelected(null);setSheet(false);}}>削除</button></div></details>}
 </article></div>)}</div><aside className={styles.right} aria-label="選択中の設定"><fieldset disabled={busy}>{settings}</fieldset></aside></div>
 {drawer&&<div className={styles.overlay} onClick={()=>setDrawer(false)}><aside ref={drawerPanel} className={styles.drawer} role="dialog" aria-modal="true" aria-label="レッスン一覧" onClick={e=>e.stopPropagation()}><button type="button" autoFocus onClick={()=>setDrawer(false)}>閉じる</button><fieldset disabled={busy}>{outline}</fieldset></aside></div>}
 {sheet&&<div className={styles.sheetOverlay} onClick={()=>setSheet(false)}><aside className={styles.sheet} role="dialog" aria-modal="true" aria-label="要素の設定" onClick={e=>e.stopPropagation()}><button type="button" autoFocus onClick={()=>setSheet(false)}>閉じる</button><fieldset disabled={busy}>{settings}</fieldset></aside></div>}
 <dialog ref={dialog} className={styles.addPanel} aria-label="コンテンツを追加" onClose={()=>setInsert(null)}><h2>ここに追加</h2>{choices.map(([type,name])=><button type="button" key={type} onClick={()=>add(type)}>{name}</button>)}<button type="button" autoFocus onClick={()=>setInsert(null)}>閉じる</button></dialog></main>;
}

function GalleryUpload({onUploaded,onBusyChange}:{onUploaded:(urls:string[])=>void;onBusyChange:(busy:boolean)=>void}){
 const {user}=useAuth(),input=useRef<HTMLInputElement>(null);const [busy,setBusy]=useState(false),[error,setError]=useState('');
 async function upload(files:File[]){if(!files.length||busy)return;setBusy(true);onBusyChange(true);setError('');const urls:string[]=[];try{for(const file of files){const asset=await uploadMikkeMediaImage({userId:user.id,file,sourceApp:'academy'});urls.push(asset.publicUrl);}}catch(cause){setError(cause instanceof Error?cause.message:'画像を追加できませんでした。');}finally{if(urls.length)onUploaded(urls);setBusy(false);onBusyChange(false);if(input.current)input.current.value='';}}
 return <div><button type="button" disabled={busy} onClick={()=>input.current?.click()}>{busy?'画像を保存中…':'複数画像を追加'}</button><input ref={input} type="file" multiple accept="image/jpeg,image/png,image/webp" className="sr-only" onChange={e=>void upload(Array.from(e.target.files??[]))}/>{error&&<p role="alert">{error}</p>}</div>;
}


/** Editor-only picker. Reuses the existing Media upload and asset APIs. */
function EditorImagePicker({currentUrl,onUploaded,onBusyChange}:{currentUrl?:string;onUploaded:(url:string)=>void;onBusyChange:(busy:boolean)=>void}){
 const {user}=useAuth(),input=useRef<HTMLInputElement>(null),trigger=useRef<HTMLButtonElement>(null),panel=useRef<HTMLElement>(null);
 const [uploading,setUploading]=useState(false),[open,setOpen]=useState(false),[loading,setLoading]=useState(false),[assets,setAssets]=useState<MikkeMediaAsset[]>([]),[error,setError]=useState(''),[message,setMessage]=useState('');
 async function refresh(){setLoading(true);setError('');try{setAssets(await listMikkeMediaAssets());}catch(cause){setError(cause instanceof Error?cause.message:'画像を読み込めませんでした。');}finally{setLoading(false);}}
 const close=()=>{setOpen(false);requestAnimationFrame(()=>trigger.current?.focus());};
 useEffect(()=>{if(open){void refresh();requestAnimationFrame(()=>panel.current?.querySelector<HTMLButtonElement>('button')?.focus());}},[open]);
 async function upload(file?:File){if(!file||uploading)return;setUploading(true);onBusyChange(true);setError('');setMessage('');try{const asset=await uploadMikkeMediaImage({userId:user.id,file,sourceApp:'academy'});onUploaded(asset.publicUrl);setAssets(items=>[asset,...items.filter(item=>item.id!==asset.id)]);setMessage('Mikke Mediaに保存しました。次回も選べます。');}catch(cause){setError(cause instanceof Error?cause.message:'画像をアップロードできませんでした。');}finally{setUploading(false);onBusyChange(false);if(input.current)input.current.value='';}}
 return <div className={styles.imagePicker}>{currentUrl&&<img className={styles.imageThumb} src={currentUrl} alt="選択中の画像"/>}<div className={styles.imageActions}><button type="button" disabled={uploading} onClick={()=>input.current?.click()}>{uploading?'画像を保存中…':'画像をアップロード'}</button><button ref={trigger} type="button" disabled={uploading} onClick={()=>setOpen(true)}>Mikke Mediaから選ぶ</button></div><input ref={input} hidden type="file" aria-label="アップロードする画像" accept="image/jpeg,image/png,image/webp" onChange={e=>void upload(e.target.files?.[0])}/><p className={styles.muted}>画像を選ぶと本文に表示されます。URL入力は不要です。</p>{message&&<p role="status" className={styles.muted}>{message}</p>}{error&&!open&&<p role="alert">{error}</p>}
 {open&&createPortal(<div className={styles.libraryOverlay} role="dialog" aria-modal="true" aria-label="Mikke Media画像ライブラリ" onMouseDown={e=>{if(e.target===e.currentTarget)close();}} onKeyDown={e=>{if(e.key==='Escape'){e.preventDefault();e.stopPropagation();close();}if(e.key==='Tab'){const buttons=Array.from(panel.current?.querySelectorAll<HTMLButtonElement>('button:not(:disabled)')??[]),first=buttons[0],last=buttons.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}}}><section ref={panel} className={styles.library}><header><div><h2>Mikke Media</h2><p>以前の画像から選ぶ</p></div><button type="button" onClick={close}>閉じる</button></header>{loading?<p role="status">画像を読み込んでいます…</p>:error?<div role="alert"><p>{error}</p><button type="button" onClick={()=>void refresh()}>もう一度読み込む</button></div>:assets.length?<div className={styles.libraryGrid}>{assets.map(asset=><button type="button" key={asset.id} aria-label={asset.originalName} onClick={()=>{onUploaded(asset.publicUrl);close();}}><img src={asset.publicUrl} alt=""/><span>{asset.originalName}</span></button>)}</div>:<p>保存済みの画像はありません。「画像をアップロード」から追加してください。</p>}</section></div>,document.body)}</div>;
}
