'use client';
import {useEffect,useRef,useState} from 'react';
import {PageBlocks} from '@/components/academy/PageBlocks';
import {AcademyContentRenderer} from '@/components/academy/AcademyContentRenderer';
import {AcademyImageUploader} from '@/components/academy/AcademyImageUploader';
import {MikkeRichWriting} from '@/components/mikkeos/content/MikkeRichWriting';
import {academyContent,replaceAcademyContent} from '@/lib/academy/content-adapter';
import {createMikkeContentBlock} from '@/lib/mikkeos/content/blocks.js';
import {sliceMediaRichText} from '@/lib/mikkeos/content/rich-text';
import type {MikkeContentBlock,MikkeContentBlockType} from '@/lib/mikkeos/content/types';
import type {AcademyPageBlock} from '@/types/database';
import styles from './lesson-article-editor.module.css';
const options:{type:MikkeContentBlockType;label:string}[]=[{type:'heading',label:'見出し'},{type:'paragraph',label:'文章'},{type:'image',label:'画像'},{type:'gallery',label:'画像グリッド'},{type:'video',label:'動画'},{type:'link',label:'リンク'}];
/** Content only: caller owns persistence, audience, access and publication. */
export function LessonArticleEditor({title,blocks,onChange,onSave,onBack,saving,dirty,error}:{title:string;blocks:AcademyPageBlock[];onChange:(next:AcademyPageBlock[])=>void;onSave:()=>void;onBack:()=>void;saving:boolean;dirty:boolean;error:string}){
 const [preview,setPreview]=useState(false),[adding,setAdding]=useState(false);const canvas=useRef<HTMLDivElement>(null),addDialog=useRef<HTMLDialogElement>(null);useEffect(()=>{if(adding)addDialog.current?.showModal();else addDialog.current?.close();},[adding]);const items=academyContent(blocks);
 const change=(next:MikkeContentBlock[])=>onChange(replaceAcademyContent(blocks,next));
 const update=(index:number,block:MikkeContentBlock)=>change(items.map((item,i)=>i===index?block:item));
 function add(type:MikkeContentBlockType){change([...items,createMikkeContentBlock(type)]);setPreview(false);setAdding(false);requestAnimationFrame(()=>canvas.current?.querySelector('article:last-child')?.scrollIntoView({block:'center'}));}
 function split(index:number,start:number,end:number){const item=items[index],next=createMikkeContentBlock('paragraph');next.text=(item.text??'').slice(end);next.richText=sliceMediaRichText(item,end,(item.text??'').length);change([...items.slice(0,index),{...item,text:(item.text??'').slice(0,start),richText:sliceMediaRichText(item,0,start)},next,...items.slice(index+1)]);}
 function move(index:number,direction:number){const target=index+direction;if(target<0||target>=items.length)return;const next=[...items];[next[index],next[target]]=[next[target],next[index]];change(next);}
 const display=(block:MikkeContentBlock)=><AcademyContentRenderer blocks={[block]}/>;
 return <main className={styles.root}><header className={styles.header}><button type="button" onClick={onBack}>← 講座編集へ</button><h1>{title}</h1><button type="button" aria-pressed={preview} onClick={()=>setPreview(!preview)}>{preview?'編集に戻る':'プレビュー'}</button></header>{error&&<p role="alert" className={styles.error}>{error}</p>}<p role="status" className={styles.status}>{saving?'保存中…':dirty?'未保存の変更があります。':'保存済みです。'}</p><p className={styles.hint}>教材は下書きとして保存します。現在公開中の教材は変更しません。</p>
 <div ref={canvas} inert={!preview&&saving} className={styles.canvas} aria-label={preview?'受講者表示プレビュー':'教材本文'}>{preview?<PageBlocks blocks={blocks}/>:<fieldset disabled={saving}>{items.map((block,index)=><article key={block.id} className={styles.block}><details className={styles.operations}><summary aria-label={'ブロック'+(index+1)+'の操作'}>…</summary><div><button type="button" disabled={index===0} onClick={()=>move(index,-1)}>上へ</button><button type="button" disabled={index===items.length-1} onClick={()=>move(index,1)}>下へ</button><button type="button" onClick={()=>change([...items.slice(0,index+1),{...structuredClone(block),id:crypto.randomUUID()},...items.slice(index+1)])}>複製</button><button type="button" onClick={()=>change(items.filter((_,i)=>i!==index))}>削除</button></div></details>
 {(block.type==='paragraph'||block.type==='heading')?<MikkeRichWriting block={block} onChange={next=>update(index,next)} onSplit={(start,end)=>split(index,start,end)}/>:block.type==='image'?<><div>{display(block)}</div><details className={styles.settings}><summary>画像を設定</summary><AcademyImageUploader compact currentUrl={block.imageUrl} onUploaded={imageUrl=>update(index,{...block,imageUrl})}/><label>画像URL<input value={block.imageUrl??''} onChange={e=>update(index,{...block,imageUrl:e.target.value})}/></label><label>説明<input value={block.alt??''} onChange={e=>update(index,{...block,alt:e.target.value})}/></label><label>写真の下の説明<input value={block.caption??''} onChange={e=>update(index,{...block,caption:e.target.value})}/></label></details></>:block.type==='gallery'?<><div>{display(block)}</div><details className={styles.settings}><summary>画像グリッドを設定</summary>{(block.images??[]).map((image,i)=><div key={i}><label>画像 {i+1} URL<input value={image.url} onChange={e=>update(index,{...block,images:block.images!.map((v,j)=>j===i?{...v,url:e.target.value}:v)})}/></label><label>画像 {i+1} の説明<input value={image.alt} onChange={e=>update(index,{...block,images:block.images!.map((v,j)=>j===i?{...v,alt:e.target.value,caption:e.target.value}:v)})}/></label><button type="button" onClick={()=>update(index,{...block,images:block.images!.filter((_,j)=>j!==i)})}>この画像を削除</button></div>)}<button type="button" onClick={()=>update(index,{...block,images:[...(block.images??[]),{url:'',alt:''}]})}>画像を追加</button></details></>:block.type==='video'||block.type==='link'?<><div>{display(block)}</div><LinkFields block={block} onChange={next=>update(index,next)}/></>:<><p className={styles.hint}>以前の形式の教材です。内容は保持されます。</p>{display(block)}</>}
 </article>)}</fieldset>}{!items.length&&<p className={styles.empty}>文章や見出しを追加して、教材を作り始めましょう。</p>}</div>
 <div className={styles.actions}><button type="button" disabled={saving} onClick={()=>{setPreview(false);setAdding(!adding);}} aria-expanded={adding}><span className={styles.pcAdd}>＋ コンテンツを追加</span><span className={styles.mobileAdd}>＋ 追加</span></button><button type="button" className={styles.save} disabled={saving} onClick={onSave}>{saving?'保存中…':'保存'}</button></div>
 <dialog ref={addDialog} className={styles.addPanel} aria-label="コンテンツを追加" onClose={()=>setAdding(false)} onClick={e=>{if(e.target===e.currentTarget){const rect=e.currentTarget.getBoundingClientRect();if(e.clientX<rect.left||e.clientX>rect.right||e.clientY<rect.top||e.clientY>rect.bottom)setAdding(false);}}}><h2>コンテンツを追加</h2><div>{options.map(option=><button type="button" key={option.type} onClick={()=>add(option.type)}>{option.label}</button>)}</div><button type="button" autoFocus onClick={()=>setAdding(false)}>閉じる</button></dialog>
 </main>;
}

function LinkFields({block,onChange}:{block:MikkeContentBlock;onChange:(next:MikkeContentBlock)=>void}){
 const [open,setOpen]=useState(!block.url);
 return <details className={styles.settings} open={open} onToggle={event=>setOpen(event.currentTarget.open)}><summary>{block.type==='video'?'動画':'リンク'}を設定</summary><label>{block.type==='video'?'動画URL':'リンクURL'}<input value={block.url??''} onChange={e=>onChange({...block,url:e.target.value})}/></label><label>表示名<input value={block.title??''} onChange={e=>onChange({...block,title:e.target.value})}/></label></details>;
}
