"use client";
import {useEffect,useRef,useState} from 'react';
import {listPlanConditions,registerPlanCondition,type PlanConditionDocument,type PlanConditionKind} from '@/lib/academy2/plan-condition-documents';
import styles from './SalesPlanDraftEditor.module.css';
export function PlanConditionPicker({headquartersId,kind,label,value,onChange}:{headquartersId:string;kind:PlanConditionKind;label:string;value?:string;onChange:(id:string|undefined)=>void}){
 const [rows,setRows]=useState<PlanConditionDocument[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[creating,setCreating]=useState(false),[busy,setBusy]=useState(false),[retry,setRetry]=useState(0);
 const [title,setTitle]=useState(''),[version,setVersion]=useState(''),[body,setBody]=useState('');const id=useRef('');
 useEffect(()=>{let live=true;setLoading(true);setError('');listPlanConditions(headquartersId,kind).then(data=>{if(live)setRows(data)}).catch(e=>{if(live)setError(e.message)}).finally(()=>{if(live)setLoading(false)});return()=>{live=false};},[headquartersId,kind,retry]);
 async function register(){if(busy||!title.trim()||!version.trim()||!body.trim())return;setBusy(true);setError('');if(!id.current)id.current=crypto.randomUUID();try{const doc=await registerPlanCondition(headquartersId,id.current,kind,title,version,body);setRows(current=>[doc,...current.filter(item=>item.id!==doc.id)]);onChange(doc.id);setCreating(false);setTitle('');setVersion('');setBody('');id.current='';}catch(e){setError(e instanceof Error?e.message:'条件文書を登録できませんでした。')}finally{setBusy(false)}}
 const selected=rows.find(row=>row.id===value);
 return <section className={styles.field} aria-label={label}><div><button type="button" disabled={busy} aria-pressed={!creating} onClick={()=>setCreating(false)}>既存条件を使う</button>{' '}<button type="button" disabled={busy} aria-pressed={creating} onClick={()=>setCreating(true)}>新しく条件を作る</button></div>{!creating&&<label>{label}<select value={value??''} disabled={loading||busy} onChange={e=>onChange(e.target.value||undefined)}><option value="">選択してください</option>{value&&!selected&&<option value={value}>保存済みの条件（内容未確認）</option>}{rows.map(row=><option key={row.id} value={row.id}>{row.title}（{row.version}）</option>)}</select></label>}{selected&&<details><summary>選んだ条件を確認</summary><p style={{whiteSpace:'pre-wrap'}}>{selected.body}</p></details>}{loading&&<p role="status">条件を読み込んでいます…</p>}{error&&<p role="alert">{error}<button type="button" onClick={()=>setRetry(n=>n+1)}>再読み込み</button></p>}{creating&&<div className={styles.conditional}><label>文書名<input disabled={busy} maxLength={200} value={title} onChange={e=>{setTitle(e.target.value);id.current=''}}/></label><label>文書の版<input disabled={busy} maxLength={100} value={version} onChange={e=>{setVersion(e.target.value);id.current=''}}/></label><label>条件の本文<textarea disabled={busy} rows={5} maxLength={20000} value={body} onChange={e=>{setBody(e.target.value);id.current=''}}/></label><p>入力した条件を販売設定に登録します。この操作で契約への同意や資格の付与は行いません。</p><button type="button" disabled={busy||!title.trim()||!version.trim()||!body.trim()} onClick={()=>void register()}>{busy?'登録中…':'登録して選択する'}</button></div>}</section>;
}

