"use client";
import {useEffect,useState} from 'react';
import {supabase} from '@/lib/supabase/client';
import {listMyAcademyCommunityLinkOptions} from '@/lib/academy/community-links';
import {createCommunityAccessClient} from '@/lib/academy/community-access-client';
import type {SalesPlanDraftConfiguration as Config} from '@/lib/academy2/sales-plan-drafts';
import {localReview,useLocalReviewVersion} from '@/lib/academy2/local-review';
import styles from './SalesPlanDraftEditor.module.css';
type Choice={id:string;name:string;mappings:{id:string;rooms:{id:string;name:string}[]}[]};
export function PlanCommunitySettings({headquartersId,configuration:c,patch,cards=false}:{cards?:boolean;headquartersId:string;configuration:Config;patch:(v:Partial<Config>)=>void}){
 const reviewVersion=useLocalReviewVersion(),[local,setLocal]=useState(false);
 const [choices,setChoices]=useState<Choice[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[retry,setRetry]=useState(0);
 useEffect(()=>{let live=true;setLoading(true);setError('');(async()=>{const {data,error:authError}=await supabase.auth.getSession();if(authError||!data.session)throw new Error('ログイン状態を確認してください。');const review=await localReview(headquartersId);if(review){if(live){setLocal(true);setChoices(review.choices);}return;}if(live)setLocal(false);const options=await listMyAcademyCommunityLinkOptions(headquartersId);const client=createCommunityAccessClient(data.session.access_token);const rows=await Promise.all(options.map(async option=>{const overview=await client.read(headquartersId,option.communityId,AbortSignal.timeout(15000));return overview.contract.kind==='available'&&overview.contract.writeAllowed?{id:option.communityId,name:option.communityName,mappings:overview.invitationOptions.items.map(m=>({id:m.mappingId,rooms:m.rooms}))}:null;}));if(live)setChoices(rows.filter((x):x is Choice=>!!x));})().catch(e=>{if(live)setError(e.message||'Communityの契約状態を確認できませんでした。');}).finally(()=>{if(live)setLoading(false)});return()=>{live=false};},[headquartersId,retry,reviewVersion]);
 const link=c.after?.community_link,community=choices.find(x=>x.id===link?.community_id),mapping=community?.mappings.find(x=>x.id===link?.mapping_id),enabled=choices.some(x=>x.mappings.length>0)&&!loading&&!error;
 function setLink(v:NonNullable<NonNullable<Config['after']>['community_link']>){patch({after:{...c.after!,community_link:v}})}
 return <section className={styles.conditional}><h3>Communityへの参加</h3>{local&&<p>ローカル確認用のCommunity・Roomです。保存しても招待や参加権は付与されません。</p>}{cards?<div role="group" aria-label="Communityへの参加条件" style={{display:'flex',flexWrap:'wrap',gap:12}}>{([['none','設定しない'],['optional','任意'],['required','必須']] as const).map(([value,text])=><button key={value} type="button" disabled={value!=='none'&&!enabled} aria-pressed={(c.community??'none')===value} onClick={()=>patch({community:value})}>{text}</button>)}</div>:<label>参加条件<select value={c.community??'none'} onChange={e=>patch({community:e.target.value as 'none'|'optional'|'required'})}><option value="none">なし</option><option value="optional" disabled={!enabled}>任意</option><option value="required" disabled={!enabled}>必須</option></select></label>}{!enabled&&<><p>{loading?'Communityの契約状態を確認中…':choices.length?'契約済みのCommunityにAcademyとの連携設定と対象Roomを登録してください。':'Community連携を利用するにはCommunityの契約が必要です'}</p><a href="/community/contracts">Communityを契約する</a></>}{error&&<p role="alert">{error}<button type="button" onClick={()=>setRetry(x=>x+1)}>再確認</button></p>}{c.community&&c.community!=='none'&&enabled&&<><label>連携するCommunity<select aria-label="連携するCommunity" value={link?.community_id??''} onChange={e=>setLink({community_id:e.target.value,mapping_id:'',room_ids:[]})}><option value="">選択してください</option>{choices.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>{community&&<label>Academyとの連携設定<select aria-label="Academyとの連携設定" value={link?.mapping_id??''} onChange={e=>setLink({community_id:community.id,mapping_id:e.target.value,room_ids:[]})}><option value="">選択してください</option>{community.mappings.map((m,i)=><option key={m.id} value={m.id}>連携 {i+1}</option>)}</select></label>}{mapping&&mapping.rooms.map(r=><label key={r.id} className={styles['radio-line']}><input type="checkbox" checked={link?.room_ids.includes(r.id)} onChange={e=>setLink({...link!,room_ids:e.target.checked?[...link!.room_ids,r.id]:link!.room_ids.filter(id=>id!==r.id)})}/>{r.name}</label>)}</>}</section>;
}
