'use client';
import {useEffect,useState} from 'react';
import {getAfterCourseCapabilities,type AfterCourseCapabilities} from '@/lib/academy2/after-course-capabilities';
import type {SalesPlanDraftConfiguration as Config} from '@/lib/academy2/sales-plan-drafts';
import {useLocalReviewVersion} from '@/lib/academy2/local-review';
import styles from './SalesPlanDraftEditor.module.css';
export function ReviewPaymentSettings({headquartersId,configuration:c,patch}:{headquartersId:string;configuration:Config;patch:(v:Partial<Config>)=>void}){
 const reviewVersion=useLocalReviewVersion();
 const [caps,setCaps]=useState<AfterCourseCapabilities|null>(null),[error,setError]=useState(''),[retry,setRetry]=useState(0);useEffect(()=>{let live=true;getAfterCourseCapabilities(headquartersId).then(v=>{if(live){setCaps(v);setError('');}}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[headquartersId,retry,reviewVersion]);const card=caps?.card_contract==='active'&&caps.card_ready;
 const toggle=(id:'card'|'bank'|'external')=>patch({payment_methods:c.payment_methods?.includes(id)?c.payment_methods.filter(x=>x!==id):[...(c.payment_methods??[]),id]});
 return <section className={styles.wizard}><h3>支払い方法</h3>{caps?.local_review&&<p>ローカル専用の決済確認です。実課金は行いません。</p>}<p role="status">{card?'カード決済 利用可能 ✓':!caps&&!error?'カード決済の契約・接続状態を確認中…':'Academyカード決済を利用するには決済設定が必要です'}</p>{!card&&<a href={`/academy/h/${headquartersId}/manage/settings`}>決済設定を確認する</a>}{c.kind==='月額レッスン'?<><p>月額レッスンはAcademyカード決済の継続課金が必須です。未契約では公開できません。</p><button type="button" disabled={!card} aria-pressed={c.payment_methods?.length===1&&c.payment_methods[0]==='card'} onClick={()=>patch({payment_methods:['card']})}>カード決済（毎月継続）</button>{c.payment_methods?.some(x=>x!=='card')&&<p>既存の支払い設定を保持しています。月額の受付にはカード決済への切替が必要です。</p>}</>:<div className={styles.wizardCards}>{([['card','カード決済'],['bank','銀行振込'],['external','外部決済サービス']] as const).map(([id,text])=><button key={id} type="button" disabled={id==='card'&&!card&&!c.payment_methods?.includes(id)} aria-pressed={c.payment_methods?.includes(id)??false} onClick={()=>toggle(id)}>{text}</button>)}</div>}{c.payment_methods?.includes('onsite')&&<p>既存の当日支払い設定を保持しています。</p>}{c.payment_methods?.includes('external')&&<div className={styles.wizard}><label>外部決済サービス名<input value={c.external_payment_details?.service_name??''} maxLength={200} onChange={e=>patch({external_payment_details:{service_name:e.target.value,instructions:c.external_payment_details?.instructions??''}})}/></label>{(c.purchase_mode==='staged'?c.course_ids:['plan']).map(id=><label key={id}>決済URL{id==='plan'?'':`（講座 ${c.course_ids.indexOf(id)+1}）`}<input aria-label={`外部決済URL ${id}`} type="url" value={c.external_payment_urls?.[id]??''} onChange={e=>patch({external_payment_urls:{...c.external_payment_urls,[id]:e.target.value}})}/></label>)}<label>受講者への案内文<textarea maxLength={4000} value={c.external_payment_details?.instructions??''} onChange={e=>patch({external_payment_details:{service_name:c.external_payment_details?.service_name??'',instructions:e.target.value}})}/></label><p>Academyでは入金を自動確認できません。本部で入金確認してください。</p></div>}{error&&<p role="alert">{error}<button type="button" onClick={()=>setRetry(x=>x+1)}>再確認</button></p>}</section>;
}
