"use client";
import type {SalesPlanDraftConfiguration} from '@/lib/academy2/sales-plan-drafts';
import {PlanConditionPicker} from './PlanConditionPicker';
import styles from './SalesPlanDraftEditor.module.css';
type After=NonNullable<SalesPlanDraftConfiguration['after']>;
export function SalesPlanAfterFields({headquartersId,kind,configuration:c,patch}:{headquartersId:string;kind:'record_completion'|'skill_certification'|'commercial_license'|'instructor_license';configuration:SalesPlanDraftConfiguration;patch:(v:Partial<SalesPlanDraftConfiguration>)=>void}){
 const after:After=c.after??{skill_certification:false,commercial_license:false,instructor_license:false};const set=(v:Partial<After>)=>patch({after:{...after,...v}});
 if(kind==='record_completion')return <PlanConditionPicker headquartersId={headquartersId} kind="completion" label="修了条件" value={after.completion_condition_id} onChange={id=>set({completion_condition_id:id})}/>;
 if(kind==='skill_certification')return <PlanConditionPicker headquartersId={headquartersId} kind="skill" label="認定条件の文書" value={after.skill_definition_id} onChange={id=>set({skill_definition_id:id})}/>;
 const prerequisite=!after.skill_certification&&<>{after.required_certification_id&&<p>既存の前提資格設定を引き継ぎます。条件文書を選んでも資格設定は変更しません。</p>}<PlanConditionPicker headquartersId={headquartersId} kind="skill" label="前提とするスキルの条件文書" value={after.required_skill_condition_id} onChange={id=>set({required_skill_condition_id:id})}/></>;
 if(kind==='commercial_license')return <>{prerequisite}<PlanConditionPicker headquartersId={headquartersId} kind="commercial" label="商用利用の対象技術・継続条件" value={after.commercial_condition_id} onChange={id=>set({commercial_condition_id:id})}/></>;
 const dues=c.dues??{enabled:false,interval:'year' as const,amount:null};const opening=c.opening_license??{enabled:false,amount:null,kit:'none' as const};
 return <>{prerequisite}<label className={styles['radio-line']}><input type="checkbox" checked={!!after.instructor_registration_required} onChange={e=>set({instructor_registration_required:e.target.checked})}/>講師登録を条件にする</label><PlanConditionPicker headquartersId={headquartersId} kind="instructor" label="講師として教えるための契約条件" value={after.instructor_condition_id} onChange={id=>set({instructor_condition_id:id})}/><PlanConditionPicker headquartersId={headquartersId} kind="manual" label="講師マニュアル" value={after.instructor_manual_id} onChange={id=>set({instructor_manual_id:id})}/><label className={styles['radio-line']}><input type="checkbox" checked={!!after.instructor_sales_page_required} onChange={e=>set({instructor_sales_page_required:e.target.checked})}/>営業ページの準備を条件にする</label><label className={styles['radio-line']}><input type="checkbox" checked={dues.enabled} onChange={e=>patch({dues:{...dues,enabled:e.target.checked}})}/>会費あり</label>{dues.enabled&&<div className={styles['cert-grid']}><label>会費の間隔<select value={dues.interval} onChange={e=>patch({dues:{...dues,interval:e.target.value as 'month'|'year'}})}><option value="month">月ごと</option><option value="year">年ごと</option></select></label><label>会費（税込）<input type="number" min={0} value={dues.amount??''} onChange={e=>patch({dues:{...dues,amount:e.target.value===''?null:Number(e.target.value)}})}/></label></div>}<label className={styles['radio-line']}><input type="checkbox" checked={opening.enabled} onChange={e=>patch({opening_license:{...opening,enabled:e.target.checked}})}/>開講ライセンスを設定する</label>{opening.enabled&&<div className={styles['cert-grid']}><label>開講ライセンス料（税込）<input type="number" min={0} value={opening.amount??''} onChange={e=>patch({opening_license:{...opening,amount:e.target.value===''?null:Number(e.target.value)}})}/></label><label>開講用キット<select value={opening.kit} onChange={e=>patch({opening_license:{...opening,kit:e.target.value as 'none'|'included'|'separate_order'}})}><option value="none">なし</option><option value="included">ライセンス料に含む</option><option value="separate_order">別途注文する</option></select></label></div>}<label className={styles.field}>コミュニティへの参加<select value={c.community??'none'} onChange={e=>patch({community:e.target.value as 'none'|'optional'|'required'})}><option value="none">設定しない</option><option value="optional">任意</option><option value="required">必須</option></select></label><p>ここでは販売条件を保存します。講師登録の完了、契約同意、会費の請求、開講権限の付与は別の手続きです。</p></>;
}
