"use client";
import {useEffect,useState} from 'react';
import type {SalesPlanDraftConfiguration as Config} from '@/lib/academy2/sales-plan-drafts';
import type {PlanExpiry,PlanRenewal} from '@/lib/academy2/sales-plan.d.mts';
import {getAfterCourseCapabilities,type AfterCourseCapabilities} from '@/lib/academy2/after-course-capabilities';
import {SalesPlanAfterFields} from './SalesPlanAfterFields';
import {InstructorManualEditor} from './InstructorManualEditor';
import {PlanCommunitySettings} from './PlanCommunitySettings';
import {listPlanConditions,type PlanConditionDocument} from '@/lib/academy2/plan-condition-documents';
import {PlanConditionPicker} from './PlanConditionPicker';
import styles from './SalesPlanDraftEditor.module.css';
const emptyAfter:NonNullable<Config['after']>={skill_certification:false,commercial_license:false,instructor_license:false};
const yen=(n:number|null|undefined)=>n==null?'未設定':`${n.toLocaleString('ja-JP')}円`;
export function AfterCourseSummary({configuration:c}:{configuration:Config}){
 const a=c.after??emptyAfter;
 return <section className={styles.note} aria-label="受講後の設定結果"><b>受講後の設定</b><p>修了：{a.record_completion===false?'なし':'あり'} ／ 証書：{a.certificate?{digital:'デジタル',physical:'現物を発送',both:'デジタル＋現物'}[a.certificate.delivery]:'なし'}<br/>認定：{a.skill_certification?(a.qualification?.name||'名称未設定'):'なし'} ／ 商用利用：{a.commercial_license?'可':'なし'} ／ 講師活動：{a.instructor_license?'条件を満たした後に可':'なし'}</p>{a.instructor_license&&<p>登録料：{a.registration_fee?.enabled?yen(a.registration_fee.amount):'なし'}<br/>会費：{c.dues?.enabled?`${c.dues.interval==='month'?'月額':'年額'}${yen(c.dues.amount)}`:'なし'}<br/>開講ライセンス：{c.opening_license?.enabled?yen(c.opening_license.amount):'なし'}<br/>Community：{{none:'なし',optional:'任意',required:'必須'}[c.community??'none']}</p>}</section>;
}
function Expiry({label,value,onChange,fixed=true}:{label:string;value:PlanExpiry;onChange:(v:PlanExpiry)=>void;fixed?:boolean}){
 return <div className={styles['cert-grid']}><label>{label}<select value={value.kind} onChange={e=>onChange({...value,kind:e.target.value as PlanExpiry['kind']})}><option value="none">なし</option><option value="months">指定月数</option><option value="years">指定年数</option>{fixed&&<option value="date">指定日まで</option>}</select></label>{['months','years'].includes(value.kind)&&<label>{value.kind==='months'?'有効月数':'有効年数'}<input type="number" min={1} step={1} value={value.count??''} onChange={e=>onChange({...value,count:e.target.value?Number(e.target.value):null})}/></label>}{value.kind==='date'&&<label>有効期限の日付<input type="date" value={value.date??''} onChange={e=>onChange({...value,date:e.target.value})}/></label>}</div>;
}
function Renewal({label,value,onChange,instructor=false}:{label:string;value:PlanRenewal;onChange:(v:PlanRenewal)=>void;instructor?:boolean}){
 const choices=instructor?[['hq_review','本部確認'],['update_course','更新講座'],['minimum_events','最低開催回数'],['other','その他']]:[['retraining','再受講'],['update_course','更新講座'],['hq_review','本部確認'],['other','その他']];
 return <section><label>{label}<select value={value.enabled?'yes':'no'} onChange={e=>onChange({...value,enabled:e.target.value==='yes'})}><option value="no">なし</option><option value="yes">あり</option></select></label>{value.enabled&&<>{choices.map(([key,text])=><label key={key} className={styles['radio-line']}><input type="checkbox" checked={value.conditions.includes(key)} onChange={e=>onChange({...value,conditions:e.target.checked?[...value.conditions,key]:value.conditions.filter(x=>x!==key)})}/>{text}</label>)}{value.conditions.includes('minimum_events')&&<label>最低開催回数<input type="number" min={1} step={1} value={value.minimum_events??''} onChange={e=>onChange({...value,minimum_events:e.target.value?Number(e.target.value):null})}/></label>}{value.conditions.includes('other')&&<label>その他の更新条件<textarea maxLength={4000} value={value.other??''} onChange={e=>onChange({...value,other:e.target.value})}/></label>}</>}</section>;
}
export function SalesPlanAfterStep({headquartersId,configuration:c,patch,onSave}:{headquartersId:string;configuration:Config;patch:(v:Partial<Config>)=>void;onSave:()=>Promise<unknown>}){
 const a=c.after??emptyAfter,set=(v:Partial<NonNullable<Config['after']>>)=>patch({after:{...a,...v}});
 const [manualOpen,setManualOpen]=useState(false),[legacyManual,setLegacyManual]=useState<PlanConditionDocument|null>(null),[manualError,setManualError]=useState('');
 const [caps,setCaps]=useState<AfterCourseCapabilities|null>(null),[error,setError]=useState(''),[retry,setRetry]=useState(0);
 useEffect(()=>{let live=true;setCaps(null);setError('');getAfterCourseCapabilities(headquartersId).then(v=>{if(live)setCaps(v)}).catch(e=>{if(live)setError(e.message)});return()=>{live=false};},[headquartersId,retry]);
 useEffect(()=>{let live=true;setLegacyManual(null);setManualError('');if(a.instructor_manual_id)listPlanConditions(headquartersId,'manual').then(rows=>{if(live){const found=rows.find(x=>x.id===a.instructor_manual_id);setLegacyManual(found??null);if(!found)setManualError('旧マニュアル文書の内容を確認できませんでした。保存済みの参照は保持しています。');}}).catch(()=>{if(live)setManualError('旧マニュアル文書を読み込めませんでした。保存済みの参照は保持しています。');});return()=>{live=false};},[headquartersId,a.instructor_manual_id,retry]);
 const card=caps?.card_contract==='active'&&caps.card_ready;
 const settings=`/academy/h/${headquartersId}/manage/settings`;
 const q=a.qualification??{name:'',expiry:{kind:'none' as const},renewal:{enabled:false,conditions:[]}};
 const policy=a.instructor_policy??{rights:[],expiry:{kind:'none' as const},renewal:{enabled:false,conditions:[]},website_listing:false};
 const fee=a.registration_fee??{enabled:false,amount:null,payment_method:'academy_card' as const};
 const dues=c.dues??{enabled:false,interval:'year' as const,amount:null};
 const opening=c.opening_license??{enabled:false,amount:null,kit:'none' as const};
 const rights=[['teach','この講座を教える'],['materials','本部教材を使う'],['manual','講師マニュアルを見る'],['sales_page','営業ページを使う'],['website','本部HPに掲載する'],['community','Communityに参加する'],['assignments','担当依頼を受ける'],['kit','講師価格でキットを購入する'],['other','その他']];
 function feeNotice(name:string){return !card&&<div className={styles.note}><p>{name}の回収にはAcademyカード決済の契約が必要です</p><a href={settings}>決済設定を確認する</a>{!caps&&!error&&<p role="status">契約状態を確認中…</p>}</div>}
 function feeQuestion(label:string,enabled:boolean,onChange:(v:boolean)=>void){return <label>{label}<select value={enabled?'yes':'no'} onChange={e=>onChange(e.target.value==='yes')}><option value="no">なし</option><option value="yes" disabled={!card}>あり</option></select></label>}
 return <div className={`${styles['after-list']} ${styles.afterQuestions}`}>
 <section><h3>1. 修了を記録しますか？</h3><label>修了の記録<select value={a.record_completion===false?'no':'yes'} onChange={e=>set({record_completion:e.target.value==='yes'})}><option value="yes">あり</option><option value="no">なし</option></select></label>{a.record_completion!==false&&<div className={styles.conditional}><SalesPlanAfterFields headquartersId={headquartersId} kind="record_completion" configuration={c} patch={patch}/></div>}</section>
 <section><h3>2. 証書を発行しますか？</h3><label>証書の発行方法<select value={a.certificate?.delivery??'none'} onChange={e=>{if(e.target.value==='none'){const next={...a};delete next.certificate;patch({after:next})}else set({certificate:{kind:a.certificate?.kind??'completion',name_rule:a.certificate?.name_rule??'',delivery:e.target.value as 'digital'|'physical'|'both'}})}}><option value="none">発行しない</option><option value="digital">デジタル</option><option value="physical">現物を発送</option><option value="both">デジタル＋現物</option></select></label>{a.certificate&&<div className={styles.conditional}><label>証書記載名のルール<input value={a.certificate.name_rule} onChange={e=>set({certificate:{...a.certificate!,name_rule:e.target.value}})}/></label><label>証書の種類<select value={a.certificate.kind} onChange={e=>set({certificate:{...a.certificate!,kind:e.target.value as 'completion'|'certification'|'other'}})}><option value="completion">修了証</option><option value="certification">認定証・デュプロマ</option><option value="other">その他</option></select></label><p>証書の発行だけで、資格や講師として活動する権限は付きません。</p></div>}</section>
 <section><h3>3. 認定資格を付与しますか？</h3><label>認定資格<select value={a.skill_certification?'yes':'no'} onChange={e=>set({skill_certification:e.target.value==='yes'})}><option value="no">なし</option><option value="yes">あり</option></select></label>{a.skill_certification&&<div className={styles.conditional}><label>認定資格名<input maxLength={200} value={q.name} onChange={e=>set({qualification:{...q,name:e.target.value}})}/></label><SalesPlanAfterFields headquartersId={headquartersId} kind="skill_certification" configuration={c} patch={patch}/><Expiry label="認定資格の有効期限" value={q.expiry} onChange={expiry=>set({qualification:{...q,expiry}})}/><Renewal label="認定資格の更新制度" value={q.renewal} onChange={renewal=>set({qualification:{...q,renewal}})}/></div>}</section>
 {(a.skill_certification||a.commercial_license||a.instructor_license)&&<section><h3>4. 認定後にできること</h3><p>資格だけを認定する場合は、追加の権限を選ばずに進めます。</p>{(['commercial_license','instructor_license'] as const).map(key=><div key={key}><label className={styles['radio-line']}><input type="checkbox" checked={a[key]} onChange={e=>set({[key]:e.target.checked,...(key==='instructor_license'&&e.target.checked?{instructor_registration_required:true}:{})})}/>{key==='commercial_license'?'認定した技術を商用利用できるようにする':'この講座を教えられるようにする'}</label>{a[key]&&key==='commercial_license'&&<div className={styles.conditional}><SalesPlanAfterFields headquartersId={headquartersId} kind={key} configuration={c} patch={patch}/></div>}</div>)}</section>}
 {a.instructor_license&&<section className={styles.conditional}><h3>講師制度の設定</h3><p>認定 → 本人の活動希望 → 講師登録申請 → 契約確認・同意 → 登録料の支払い（ある場合） → 必要条件の確認 → 講師ライセンス有効化 → 活動開始</p><p>登録料を支払っただけでは活動できません。必要な認定・本人の希望・登録・契約同意・料金・その他の条件を確認します。</p>
 <p>講師として活動するには、本人の講師登録が必要です。</p>{!a.skill_certification&&<>{a.required_certification_id&&<p>既存の前提資格を引き継ぎます。条件文書を選んでも、前提資格は変更しません。</p>}<PlanConditionPicker headquartersId={headquartersId} kind="skill" label="前提とするスキルの条件文書" value={a.required_skill_condition_id} onChange={id=>set({required_skill_condition_id:id})}/></>}<PlanConditionPicker headquartersId={headquartersId} kind="instructor" label="講師契約条件" value={a.instructor_condition_id} onChange={id=>set({instructor_condition_id:id})}/>
 <h3>講師ライセンスで利用できること</h3>{rights.map(([key,text])=><label key={key} className={styles['radio-line']}><input type="checkbox" checked={policy.rights.includes(key)} onChange={e=>set({instructor_policy:{...policy,rights:e.target.checked?[...policy.rights,key]:policy.rights.filter(x=>x!==key)}})}/>{text}</label>)}{policy.rights.includes('other')&&<label>その他の活動権限<textarea value={policy.other??''} maxLength={4000} onChange={e=>set({instructor_policy:{...policy,other:e.target.value}})}/></label>}
 <Expiry label="講師ライセンスの有効期限" value={policy.expiry} fixed={false} onChange={expiry=>set({instructor_policy:{...policy,expiry}})}/><Renewal label="講師ライセンスの更新制度" value={policy.renewal} instructor onChange={renewal=>set({instructor_policy:{...policy,renewal}})}/>
 <label className={styles['radio-line']}><input type="checkbox" checked={!!a.instructor_sales_page_required} onChange={e=>set({instructor_sales_page_required:e.target.checked})}/>営業ページの準備を条件にする</label><label className={styles['radio-line']}><input type="checkbox" checked={policy.website_listing} onChange={e=>set({instructor_policy:{...policy,website_listing:e.target.checked}})}/>本部HPの講師一覧に掲載する</label>
 <h3>講師マニュアル</h3>{a.instructor_manual_id&&<div><p>これまでのマニュアル文書は保持しています。教材本文への変換は自動では行いません。</p>{legacyManual&&<details><summary>旧マニュアル文書を確認（{legacyManual.title}／{legacyManual.version}）</summary><p style={{whiteSpace:'pre-wrap'}}>{legacyManual.body}</p></details>}{manualError&&<p role="alert">{manualError}<button type="button" onClick={()=>setRetry(x=>x+1)}>再確認</button></p>}</div>}<button type="button" onClick={()=>setManualOpen(true)}>{a.manual?'マニュアルを編集する':'マニュアルを作る'}</button>{' '}<button type="button" onClick={()=>setManualOpen(false)}>後で設定する</button>
 <h3>講師登録料（活動開始時の初回費用）</h3>{caps?.local_review&&<p>ローカル確認用の契約・接続状態です。実契約や実課金は行いません。</p>}{feeQuestion('講師登録料はありますか？',fee.enabled,enabled=>set({registration_fee:{...fee,enabled}}))}{feeNotice('講師登録料')}{fee.enabled&&<><label>登録料（税込）<input type="number" min={1} step={1} disabled={!card} value={fee.amount??''} onChange={e=>set({registration_fee:{...fee,amount:e.target.value?Number(e.target.value):null}})}/></label><p>支払い方法：Academyカード決済</p></>}
 <h3>講師会費（継続活動の費用）</h3>{feeQuestion('講師会費はありますか？',dues.enabled,enabled=>patch({dues:{...dues,enabled,payment_method:'academy_card'}}))}{feeNotice('講師会費')}{dues.enabled&&<fieldset disabled={!card}><label>会費の間隔<select value={dues.interval} onChange={e=>patch({dues:{...dues,interval:e.target.value as 'month'|'year'}})}><option value="month">月額</option><option value="year">年額</option></select></label><label>会費（税込）<input type="number" min={1} step={1} value={dues.amount??''} onChange={e=>patch({dues:{...dues,amount:e.target.value?Number(e.target.value):null}})}/></label><label>会費の請求基準日<select value={dues.billing_anchor??''} onChange={e=>patch({dues:{...dues,billing_anchor:e.target.value as 'application'|'first'|'specified'}})}><option value="">選択してください</option><option value="application">登録日基準</option><option value="first">毎月1日</option><option value="specified">指定日</option></select></label>{dues.billing_anchor==='specified'&&<label>会費の指定請求日<input type="number" min={1} max={31} value={dues.billing_day??''} onChange={e=>patch({dues:{...dues,billing_day:e.target.value?Number(e.target.value):null}})}/></label>}<label>会費の退会適用<select value={dues.cancellation??''} onChange={e=>patch({dues:{...dues,cancellation:e.target.value as 'before_next'|'end_of_period'}})}><option value="">選択してください</option><option value="before_next">次回請求前まで退会可</option><option value="end_of_period">支払い済み期間の終了時</option></select></label><label>会費未払い時の猶予日数<input type="number" min={0} max={365} value={dues.unpaid_grace_days??''} onChange={e=>patch({dues:{...dues,unpaid_grace_days:e.target.value?Number(e.target.value):null}})}/></label><p>支払い方法：Academyカード決済</p></fieldset>}
 <h3>開講ライセンス料（対象講座を開講する権利の費用）</h3>{feeQuestion('開講ライセンス料はありますか？',opening.enabled,enabled=>patch({opening_license:{...opening,enabled,payment_method:'academy_card'}}))}{feeNotice('開講ライセンス料')}{opening.enabled&&<fieldset disabled={!card}><label>開講ライセンス料（税込）<input type="number" min={1} step={1} value={opening.amount??''} onChange={e=>patch({opening_license:{...opening,amount:e.target.value?Number(e.target.value):null}})}/></label><label>開講ライセンス料の支払いタイミング<select value={opening.timing??''} onChange={e=>patch({opening_license:{...opening,timing:e.target.value as 'initial'|'per_event'|'renewal'}})}><option value="">選択してください</option><option value="initial">初回のみ</option><option value="per_event">開催ごと</option><option value="renewal">更新時</option></select></label><label>開講用キット<select value={opening.kit} onChange={e=>patch({opening_license:{...opening,kit:e.target.value as 'none'|'included'|'separate_order'}})}><option value="none">なし</option><option value="included">料金に含む</option><option value="separate_order">別途注文</option></select></label><p>支払い方法：Academyカード決済</p></fieldset>}
 {error&&<p role="alert">{error}<button type="button" onClick={()=>setRetry(x=>x+1)}>契約状態を再確認</button></p>}
 <p>保存するのは制度の条件です。講師登録や契約への同意、料金の請求、活動権限の付与は後続の手続きで行います。</p>
 </section>}
 {a.instructor_license&&<PlanCommunitySettings headquartersId={headquartersId} configuration={c} patch={patch}/>}
 {c.kind==='月額レッスン'&&<label>月額レッスンの修了・認定を確認するタイミング<select value={a.completion_timing??''} onChange={e=>set({completion_timing:e.target.value as 'period_end'|'lesson_complete'|'hq_review'})}><option value="">選択してください</option><option value="period_end">指定期間終了時</option><option value="lesson_complete">指定レッスン完了時</option><option value="hq_review">本部確認時</option></select></label>}
 <AfterCourseSummary configuration={c}/>
 {manualOpen&&<InstructorManualEditor blocks={a.manual?.blocks??[]} onChange={blocks=>set({manual:{blocks}})} onSave={onSave} onClose={()=>setManualOpen(false)}/>}
 </div>;
}
