"use client";
import type {SalesPlanDraft,SalesPlanDraftConfiguration} from '@/lib/academy2/sales-plan-drafts';
import type {Academy2Course} from '@/lib/academy2/courses';
import {PlanConditionPicker} from './PlanConditionPicker';
import {MonthlyPolicyFields} from './MonthlyPolicyFields';
import styles from './SalesPlanDraftEditor.module.css';
type Props={headquartersId:string;step:number;configuration:SalesPlanDraftConfiguration;courses:Academy2Course[];saved:SalesPlanDraft|null;patch:(value:Partial<SalesPlanDraftConfiguration>)=>void};
/** Kind-specific contract fields reuse UI05 spacing. Only course layout has a supplied exact HTML source. */
export function SalesPlanTypeFields({headquartersId,step,configuration:c,courses,saved,patch}:Props){
 const monthly=c.monthly??{months:[]};const updateMonth=(index:number,value:Partial<typeof monthly.months[number]>)=>patch({monthly:{...monthly,months:monthly.months.map((item,i)=>i===index?{...item,...value}:item)}});
 if(step===0&&c.kind==='全講座')return <div className={styles.conditional}><h3>対象講座群を選ぶ</h3><p>この販売プランに含める講座を選びます。選択した講座群を保存します。</p><button type="button" onClick={()=>patch({catalog_course_ids:courses.map(x=>x.id)})}>すべて選択</button>{courses.map(course=><label key={course.id}><input type="checkbox" checked={(c.catalog_course_ids??saved?.course_snapshot.map(x=>x.course_id)??[]).includes(course.id)} onChange={e=>{const ids=c.catalog_course_ids??saved?.course_snapshot.map(x=>x.course_id)??[];patch({catalog_course_ids:e.target.checked?[...ids,course.id]:ids.filter(id=>id!==course.id)});}}/>{course.name} / 参考価格 {course.reference_price==null?'未設定':`¥${course.reference_price.toLocaleString('ja-JP')}`}</label>)}</div>;
 if(step===0&&c.kind==='ワークショップ')return <div className={styles.conditional}><label>体験する内容<textarea value={c.workshop?.experience??''} onChange={e=>patch({workshop:{...c.workshop,experience:e.target.value}})}/></label><label>所要時間（分）<input type="number" min="1" value={c.workshop?.duration_minutes??''} onChange={e=>patch({workshop:{experience:c.workshop?.experience??'',...c.workshop,duration_minutes:e.target.value?Number(e.target.value):undefined}})}/></label><label>持ち物<input value={c.workshop?.bring??''} onChange={e=>patch({workshop:{experience:c.workshop?.experience??'',...c.workshop,bring:e.target.value}})}/></label><label>持ち帰れるもの・身につくこと<input value={c.workshop?.outcome??''} onChange={e=>patch({workshop:{experience:c.workshop?.experience??'',...c.workshop,outcome:e.target.value}})}/></label></div>;
 if(c.kind!=='月額レッスン')return null;
 if(step===0)return <div className={styles.conditional}><p>月ごとに公開する講座と教材の利用を選びます。キットは講座側の設定を使います。</p>{monthly.months.map((item,i)=><div className={styles['form-row']} key={i}><label>対象月<input type="month" value={item.month} onChange={e=>updateMonth(i,{month:e.target.value})}/></label>{courses.map(course=><label className={styles["radio-line"]} key={course.id}><input type="checkbox" checked={item.course_ids.includes(course.id)} onChange={()=>updateMonth(i,{course_ids:item.course_ids.includes(course.id)?item.course_ids.filter(id=>id!==course.id):[...item.course_ids,course.id]})}/>{course.name}</label>)}<label className={styles["radio-line"]}><input type="checkbox" checked={!!item.materials} onChange={e=>updateMonth(i,{materials:e.target.checked})}/>レッスン教材あり</label><p>キット・発送物は選んだ講座側の設定を参照します。</p><button onClick={()=>patch({monthly:{...monthly,months:monthly.months.filter((_,j)=>j!==i)}})}>この月を削除</button></div>)}<button onClick={()=>patch({monthly:{...monthly,months:[...monthly.months,{month:'',course_ids:[],materials:false,kit:false}]}})}>＋ 月を追加</button></div>;
 if(step===2)return <div className={styles.conditional}><label>受講期間<select value={monthly.period?.kind??''} onChange={e=>patch({monthly:{...monthly,period:e.target.value==='unlimited'?{kind:'unlimited'}:e.target.value==='months'?{kind:'months',count:1}:{kind:'calendar',start:'',end:''}}})}><option value="" disabled>選択してください</option><option value="unlimited">期間を決めない</option><option value="months">受講月数を決める</option><option value="calendar">開始月と終了月を決める</option></select></label>{monthly.period?.kind==='months'&&<label>受講月数<input type="number" min="1" value={monthly.period.count} onChange={e=>patch({monthly:{...monthly,period:{kind:'months',count:Number(e.target.value)}}})}/></label>}{monthly.period?.kind==='calendar'&&<><label>開始月<input type="month" value={monthly.period.start} onChange={e=>patch({monthly:{...monthly,period:{kind:'calendar',start:e.target.value,end:monthly.period?.kind==='calendar'?monthly.period.end:''}}})}/></label><label>終了月<input type="month" value={monthly.period.end} onChange={e=>patch({monthly:{...monthly,period:{kind:'calendar',start:monthly.period?.kind==='calendar'?monthly.period.start:'',end:e.target.value}}})}/></label></>}<label>過去の教材<select value={monthly.past_access??''} onChange={e=>patch({monthly:{...monthly,past_access:e.target.value as 'all_past'|'from_join_month'}})}><option value="" disabled>選択してください</option><option value="all_past">過去の教材も使える</option><option value="from_join_month">入会月以降の教材を使える</option></select></label><PlanConditionPicker headquartersId={headquartersId} kind="monthly_exit" label="退会・教材利用終了の条件" value={monthly.exit_policy_id} onChange={id=>patch({monthly:{...monthly,exit_policy_id:id}})}/><MonthlyPolicyFields monthly={monthly} isNewDraft={!saved} onChange={value=>patch({monthly:value})}/><p>継続課金の接続確認が終わるまで受付開始は保留されます。</p></div>;
 if(step===3)return <p className={styles.note}>月額レッスンはカードによる継続支払いが必要です。継続課金の接続確認が終わるまで受付は開始されません。</p>;
 if(step===4&&(c.after?.skill_certification||c.after?.commercial_license||c.after?.instructor_license))return <div className={styles.conditional}><label>認定のタイミング<select value={monthly.certification_timing??''} onChange={()=>patch({monthly:{...monthly,certification_timing:'plan_completion'}})}><option value="" disabled>選択してください</option><option value="plan_completion">販売プラン全体の修了時</option></select></label><PlanConditionPicker headquartersId={headquartersId} kind="completion" label="月額レッスン全体の修了条件" value={monthly.completion_condition_id} onChange={id=>patch({monthly:{...monthly,completion_condition_id:id}})}/></div>;
 return null;
}
